- regExp: "admin-.*\\.adoc+$"
  labels: ["AdminGuide"]
- regExp: "deployment-.*\\.adoc+$"
  labels: ["DeploymentGuide"]
- regExp: "workflows\\/.*\\.yml+$|book_.*\\.adoc+$|.*\\-docinfo\\.xml+$|common_.*\\.adoc+$|entities\\.adoc+$|attributes\\.adoc+$"
  labels: ["Overhead"]
- regExp: ".*cilium.*\\.adoc"
  labels: ['networking']
