= SUSE CaaS Platform Documentation

image:https://travis-ci.org/SUSE/doc-caasp.svg?branch=adoc["Build Status", link="https://travis-ci.org/SUSE/doc-caasp"]

This is the source for the official SUSE CaaS Platform documentation

Released versions of the documentation will be published at
https://www.suse.com/documentation/ once available.

== Contributing

.Allow maintainer updates for pull requests
[IMPORTANT]
When creating a Pull Request please allow maintainers to push commits into your fork.
See: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If you would like to contribute, please fork this repository and send pull requests.

Fork the `master` branch for requesting changes to the SUSE CaaS Platform 4.0 and higher documentation.

For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide]

Changes to already released versions of the documentation must be merged to a `maintenance/CaaSX` branch from the maintainer.

== Editing DocBook

To contribute to the documentation you will use AsciiDoc syntax.

* You can learn about AsciiDoc syntax at link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[]
** A much more detailed manual can be found link:https://asciidoctor.org/docs/user-manual/[here]
* For simple preview use the browser extensions for
** https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[Chrome]
** https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/[Firefox]
** Make sure you set the "security" setting in the Extension Preferences to `server`

* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). It's available as a
  SUSE rpm package from the the SUSE repository http://download.opensuse.org/repositories/Documentation:/Tools/[Documentation:Tools] or
  directly from https://github.com/openSUSE/suse-xsl/[Github].
* If you are running a (recent) version of openSUSE, you can install our documentation toolchain with the following command:
`sudo /sbin/OneClickInstallUI https://gitlab.nue.suse.com/susedoc/doc-ymp/raw/master/Documentation.ymp`
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** Learn more at https://opensuse.github.io/daps
