[[_cha.quick.configuration]]
= Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images

{productname}
is typically configured in two stages: first, during the installation process, and subsequently, using `cloud-init` and/or {dashboard}
 settings page.
During the initial installation, {productname}
 comes as preconfigured as possible. 

[[_sec.quick.configuration.second_stage]]
== Deployment Scenarios Requiring Second-stage Configuration


Second-stage configuration is typically used for large-scale clusters built using pre-installed virtual machine disk images.
Because these images are pre-installed, the installation program does not run, and so it is not possible to choose options interactively.
Therefore, they must be specified in configuration files. 

For smaller clusters of just a few nodes, `cloud-init` is generally not necessary, and so it is not described here in the {instquick}
 Guide.
For information on using ``cloud-init``, refer to the Configuration chapter in the {deploy}
. 

The following section describes the default values for the system configuration.
If you require different settings than these, follow the {deploy}
to build your cluster. 

[[_sec.quick.configuration.defaults]]
== Defaults


The following are the defaults for the first stage of configuration: 

timezone::
This is set to _UTC_ by default.
It is not recommended to change this, but it is possible using ``cloud-init``; see the {deploy}
. 

keyboard::
This is set to _us_ by default.
If desired, choose an alternative layout from the list on the first screen of the installation program. 

locale::
This is set to _en_US.utf8_ by default, but can be changed by ``cloud-init``. 
