[[_cha.user.pods]]
= Managing Pods
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Managing Pods
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images



[[_sec.user.pods.overview]]
== Overview


Pods are the computing units of {kube}
and consist of one or more containers.
A pod has its own IP address and storage resources.
To scale an application, multiple pods with the same containers can be started.
The pods are automatically distributed among the cluster nodes. 

A very good introduction to starting an application in a pod is available at {kubedoc}tutorials/kubernetes-basics/deploy-interactive/. 

For more information about pods, refer to {kubedoc}concepts/workloads/pods/pod-overview/. 

[[_sec.user.pods.create]]
== Creating Pods


To create a pod, first define it in a YAML file.
Usually, a pod has at least one container in it.
The used containers must be available in a container registry, for example __{suse}
 container image registry__. 

.Basic Pod with NGINX-Container
====
----
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
----
====


Then apply the YAML file with [command]``kubectl create -f
   `YAML_FILE```. 

[[_sec.user.pods.remove]]
== Killing Pods


To kill a running pod, use [command]``kubectl delete pod
   `POD_NAME```.
The `POD_NAME` refers to the `name` value of the `metadata` section.
By default, the pod is granted a grace period of 30 seconds to shut down.
After that, it will be killed. 

[[_sec.user.pods.list]]
== List Running Pods


To list running pods, run `kubectl get pods`. 