[[_cha.user.access]]
= Interacting with {productname}
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Interacting with SUSE CaaS Platform
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images

{productname}
manages your workloads as containers on a cluster of computer nodes.
The computer nodes can be physical or virtualized machines.
The core software component of this cluster is {kube}
. {kube}
takes care of balancing the workloads, starting and stopping applications in containers, configuring network access, and many other things. 

Users interact with {kube}
via an REST API. [command]``kubectl`` is an easy to use command line tool for this API.
To run workloads on {productname}
, you need to authenticate against the cluster and your user needs to be granted the required privileges. 

[[_sec.user.access.credentials]]
== Gaining Cluster Access


This section is intended for normal users.
If you are the admin, refer to <<_sec.admin.kubernetes.install_kubectl>>. 

To access the {kube}
cluster, execute the following steps: 


. Get your credentials consisting of an e-mail address and a password from your cluster administrator. You also need the _fully qualified domain name_ (__FQDN__) of the admin node. 
. Download the [path]``kubeconfig`` by visiting ``https://[replaceable]``ADMIN_NODE``/kubeconfig``. Log in with your credentials and store the [path]``kubeconfig`` as [path]``~/.kube/config`` . 
. Obtain the cluster root certificate and update your certificate store. On {sle} or {opensuse} , execute: 
+

----
{prompt.sudo}``cp CERTIFICATE_FILE /etc/pki/trust/anchors/`` {prompt.sudo}``update-ca-certificates`` 
----


[[_sec.user.access.kubectl]]
== Using [command]``kubectl``

[command]``kubectl`` is a command line user interface to the {kube}
 cluster.
By default, the authorization credentials are read from the file [path]``~/.kube/config``
. 

To perform a specific command, at least one of your assigned roles needs to have the required privilege.
The default syntax for [command]``kubectl`` commands is: 

----
{prompt.user}``kubectl COMMAND TYPE NAME FLAGS`` 
----

COMMAND::
The operation that is performed on the resource, for example ``create``, ``get``, or ``delete``. 

TYPE::
The resource type on which the operation is performed, for example ``pod``, ``service``, or ``namespace``. 

NAME::
The name of specific resources ([replaceable]``TYPE``). If omitted, the command is performed on all resources of a type. 

FLAGS::
This allows setting further details for the command, for example the {kube}
API server URL. 


Instead of running [command]``kubectl`` multiple times to perform all required changes, all changes can be collected in JSON or YAML files and applied at once.
This is done with the following syntax: 

----
{prompt.user}``kubectl ACTION -f FILE_NAME`` 
----


Replace [replaceable]``ACTION`` with ``create``, ``replace``, ``delete``, or ``get``.
Replace [replaceable]``FILE_NAME`` with the path to the YAML or JSON file or containing directory. 

For more details about [command]``kubectl``, refer to [command]``kubectl --help`` and https://v1-11.docs.kubernetes.io/docs/reference/kubectl/overview/. 

[command]``kubectl`` supports different modes: an imperative and a declarative mode.
For details, refer to https://v1-11.docs.kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/. 