//= Cluster Management

Cluster management refers to several processes in the lifecycle of a cluster an
its individual nodes: bootstrapping, joining, removing and resetting nodes.
For maximum automation and ease {productname} uses the `skuba` tool,
which simplifies Kubernetes cluster creation and reconfiguration.


include::deployment-bootstrap.adoc[Bootstrapping]


== Removing nodes

The `skuba node remove` command serves to *permanently* remove nodes.
Running this command will work even if the target virtual machine is down,
so it is the safest way to remove the node.

[source,bash]
skuba node remove <node-name>

If you wish to remove the node and want to add it again, the recommended approach is to
first drain the node using `kubectl`. This will also cordon the node,
so that it doesn't receive any new workloads.
When you want to bring the node back, you only have to uncordon it.
Refer to the official Kubernetes documentation for more information:
https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#use-kubectl-drain-to-remove-a-node-from-service


== Resetting nodes

The `skuba node reset` command enables you to reset a node to a state prior to join or bootstrap being run.
Use this command to retry a failed bootstrap or join on a node or if the node has to be evacuated from the cluster.

[source,bash]
skuba node reset --target <IP/FQDN> --sudo --user <user-name>


== Reconfiguring nodes

To reconfigure a node, for example to change the node role from worker to master,
you will need to use a combination of commands.

1. Run `skuba node remove <node-name>`.
2. Reinstall the node from scratch.
3. Run `skuba node join --role <desired-role> -user <user-name> --sudo --target <IP/FQDN> <node-name>`
