= Certificates

During the installation of {productname}, a CA (Certificate Authority) certificate is generated,
which is then used to authenticate and verify all communication. This process also creates
and distributes client and server certificates for the components.

== Communication Security
Communication is secured with TLS v1.2 using the AES 128 CBC cipher.
All certificates are 2048 bit RSA encrypted.

== Certificate Validity
The CA certificate is valid for 3650 days (10 years) by default.
Client and server certificates are valid for 365 days (1 year) by default.

== Certificate Location
Required CAs for {productname} are stored on all master nodes:

[%header,cols=3*]
|===
|Common Name
|Path
|Description

|kubernetes
|/etc/kubernetes/pki/ca.crt,key
|kubernetes general CA

|etcd-ca
|/etc/kubernetes/pki/etcd/ca.crt,key
|Etcd cluster

|kubelet-ca
|/var/lib/kubelet/pki/kubelet-ca.crt,key
|Kubelet components

|front-proxy-ca
|/etc/kubernetes/pki/front-proxy-ca.crt,key
|Front-proxy components
|===

The following certificates are managed by `kubeadm`:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Path (`/etc/kubernetes/pki`)
|Kind

|kubernetes
|
|ca.crt,key
|CA

|kube-apiserver
|kubernetes
|apiserver.crt,key
|Server

|kube-apiserver-etcd-client
|kubernetes
|apiserver-etcd-client.crt,key
|Client

|kube-apiserver-kubelet-client
|kubernetes
|apiserver-kubelet-client.crt,key
|Client

|etcd-ca
|
|etcd/ca.crt,key
|CA

|kube-etcd-healthcheck-client
|etcd-ca
|etcd/healthcheck-client.crt,key
|Client

|kube-etcd-peer
|etcd-ca
|etcd/peer.crt,key
|Server,Client

|kube-etcd-server
|etcd-ca
|etcd/server.crt,key
|Server,Client

|front-proxy-ca
|
|front-proxy-ca.crt,key
|CA

|front-proxy-client
|front-proxy-ca
|front-proxy-client.crt,key
|Client
|===

The following certificates are created by `skuba`:

* stored in the {kube} cluster as file format:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Path (`/var/lib/kubelet/pki`)
|Kind

|kubelet-ca
|
|kubelet-ca.crt,key
|CA
|===

* stored in the {kube} cluster as `Secret` resource:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Secret Resource Name
|Kind

|oidc-dex
|kubernetes
|oidc-dex-cert
|Server

|oidc-gangway
|kubernetes
|oidc-gangway-cert
|Server

|cilium-etcd-client
|etcd-ca
|cilium-secret
|Client
|===

== Monitoring Certificates

We use cert-exporter to monitor nodes' on-host certificates and addons' secret certificates. The cert-exporter collects the metrics of certificates expiration periodically (1 hour by default) and exposes them through the `/metrics` endpoint. Then, the Prometheus server can scrape these metrics from the endpoint periodically.

[source,bash]
----
helm repo add suse https://kubernetes-charts.suse.com
helm install suse/cert-exporter --name ${RELEASE_NAME}
----
Or if you have selected the Helm 3 alternative also see <<helm-tiller-install>>:
[source,bash]
----
helm repo add suse https://kubernetes-charts.suse.com
helm install ${RELEASE_NAME} suse/cert-exporter
----

=== Prerequisites

. To monitor certificates, we need to set up monitoring stack by following the <<monitoring-stack>> on how to deploy it.
. Label the skuba addon certificates
+
[source,bash]
----
kubectl label --overwrite secret oidc-dex-cert -n kube-system caasp.suse.com/skuba-addon=true
kubectl label --overwrite secret oidc-gangway-cert -n kube-system caasp.suse.com/skuba-addon=true
kubectl label --overwrite secret metrics-server-cert -n kube-system caasp.suse.com/skuba-addon=true
----
+
[NOTE]
====
You might see the following console output:
[source,bash]
----
secret/oidc-dex-cert not labeled
secret/oidc-gangway-cert not labeled
secret/metrics-server-cert not labeled
----
This is because `skuba` has already added the labels for you.
====

=== Prometheus Alerts

Use Prometheus alerts to reactively receive the status of the certificates, follow the <<alertmanager-configuration-example>> on how to configure the Prometheus Alertmanager and Prometheus Server.

=== Grafana Dashboards

Use Grafana to proactively monitor the status of the certificates, follow the <<adding-grafana-dashboards>> to install the Grafana dashboard to monitors certificates.

=== Monitor Custom Secret Certificates

You can monitor custom secret TLS certificates that you created manually or using link:https://cert-manager.io/[cert-manager].

For example:

. Monitor cert-manager issued certificates in the `cert-managert-test` namespace.
+
[source,bash]
----
helm install suse/cert-exporter \
    --name ${RELEASE_NAME} \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}"
----
Or if you have selected the Helm 3 alternative also see <<helm-tiller-install>>:
+
[source,bash]
----
helm install ${RELEASE_NAME} suse/cert-exporter \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}"
----

. Monitor certificates in all namespaces filtered by label selector.
+
[source,bash]
----
helm install suse/cert-exporter \
    --name ${RELEASE_NAME} \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=self-signed-cert \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].labelSelector="{key=value}"
----
Or if you have selected the Helm 3 alternative also see <<helm-tiller-install>>:
+
[source,bash]
----
helm install ${RELEASE_NAME} suse/cert-exporter \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=self-signed-cert \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].labelSelector="{key=value}"
----

. Deploy both 1. and 2. together.
+
[source,bash]
----
helm install suse/cert-exporter \
    --name ${RELEASE_NAME} \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}" \
    --set customSecret.certs[1].name=self-signed-cert \
    --set customSecret.certs[1].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[1].labelSelector="{key=value}"
----
Or if you have selected the Helm 3 alternative also see <<helm-tiller-install>>:
+
[source,bash]
----
helm install ${RELEASE_NAME} suse/cert-exporter \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}" \
    --set customSecret.certs[1].name=self-signed-cert \
    --set customSecret.certs[1].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[1].labelSelector="{key=value}"
----

. Monitor custom certificates only, disregarding node and addon certificates.
+
[source,bash]
----
helm install suse/cert-exporter \
    --name ${RELEASE_NAME} \
    --set node.enabled=false \
    --set addon.enabled=false \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}" \
    --set customSecret.certs[1].name=self-signed-cert \
    --set customSecret.certs[1].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[1].labelSelector="{key=value}"
----
Or if you have selected the Helm 3 alternative also see <<helm-tiller-install>>:
+
[source,bash]
----
helm install ${RELEASE_NAME} suse/cert-exporter \
    --set node.enabled=false \
    --set addon.enabled=false \
    --set customSecret.enabled=true \
    --set customSecret.certs[0].name=cert-manager \
    --set customSecret.certs[0].namespace=cert-manager-test \
    --set customSecret.certs[0].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[0].annotationSelector="{cert-manager.io/certificate-name}" \
    --set customSecret.certs[1].name=self-signed-cert \
    --set customSecret.certs[1].includeKeys="{ca.crt,tls.crt}" \
    --set customSecret.certs[1].labelSelector="{key=value}"
----

== Deployment with a Custom CA Certificate

[WARNING]
====
Please plan carefully when deploying with a custom CA certificate. This certificate
can not be reconfigured once deployed and requires a full re-installation of the
cluster to replace.
====

Administrators can provide custom CA certificates (root CAs or intermediate CAs)
during cluster deployment and decide which CA components to replace (multiple CA certificates) or if to replace all with a single CA certificate.

After you have run `skuba cluster init`, go to the `my-cluster` folder that has been generated,
Create a `pki` folder and put your custom CA certificate into the `pki` folder.

.Extracting Certificate And Key From Combined PEM File
[NOTE]
====
Some PKIs will issue certificates and keys in a combined `.pem` file.
In order to use the contained certificate, you must extract them into separate files using `openssl`.

. Extract the certificate:
+
[source,bash]
----
openssl x509 -in /path/to/file.pem -out /path/to/file.crt
----
. Extract the key:
+
[source,bash]
----
openssl rsa -in /path/to/file.pem -out /path/to/file.key
----
====

* Replacing the {kube} `apiserver` CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_APISERVER_CA_CERT_PATH> my-cluster/pki/ca.crt
cp <CUSTOM_APISERVER_CA_KEY_PATH> my-cluster/pki/ca.key
chmod 644 my-cluster/pki/ca.crt
chmod 600 my-cluster/pki/ca.key
----

* Replacing the `etcd` CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki/etcd
cp <CUSTOM_ETCD_CA_CERT_PATH> my-cluster/pki/etcd/ca.crt
cp <CUSTOM_ETCD_CA_KEY_PATH> my-cluster/pki/etcd/ca.key
chmod 644 my-cluster/pki/etcd/ca.crt
chmod 600 my-cluster/pki/etcd/ca.key
----

* Replacing the `kubelet` CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_KUBELET_CA_CERT_PATH> my-cluster/pki/kubelet-ca.crt
cp <CUSTOM_KUBELET_CA_KEY_PATH> my-cluster/pki/kubelet-ca.key
chmod 644 my-cluster/pki/kubelet-ca.crt
chmod 600 my-cluster/pki/kubelet-ca.key
----

* Replacing the `front-end proxy` CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_FRONTPROXY_CA_CERT_PATH> my-cluster/pki/front-proxy-ca.crt
cp <CUSTOM_FRONTPROXY_CA_KEY_PATH> my-cluster/pki/front-proxy-ca.key
chmod 644 my-cluster/pki/front-proxy-ca.crt
chmod 600 my-cluster/pki/front-proxy-ca.key
----

After this process, bootstrap the cluster with `skuba node bootstrap`.

== Replace Server Certificate signed by a Trusted CA Certificate

{productname} uses `oidc-dex` and `oidc-gangway` servers to do authentication and authorization.
Administrators might choose to replace these server's certificates by issuing a trusted CA certificate after cluster deployment.
This way, the user does not have to add specific certificates to their trusted keychain.

[WARNING]
====
The custom trusted CA certificate key is not handled by skuba.
Administrators must handle server certificate rotation manually before the certificate expires.
====

[WARNING]
====
The `oidc-dex` and `oidc-gangway` server certificate and key would be replaced when `skuba addon upgrade apply` contains dex or gangway addon upgrade.
Make sure to reapply your changes after running `skuba addon upgrade apply`, had you modified the default settings of oidc-dex and oidc-gangway addons.
====

* Replace the `oidc-dex` server certificate:

. Backup the original `oidc-dex` server certificate and key from secret resource.
+
[source,bash]
----
mkdir -p pki.bak
kubectl get secret oidc-dex-cert -n kube-system -o yaml | tee pki.bak/oidc-dex-cert.yaml > /dev/null

cat pki.bak/oidc-dex-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | tee pki.bak/oidc-dex.crt > /dev/null
cat pki.bak/oidc-dex-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | tee pki.bak/oidc-dex.key > /dev/null
----

. Get the original SAN IP address(es) and DNS(s), run:
+
[source,bash]
----
openssl x509 -noout -text -in pki.bak/oidc-dex.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in pki.bak/oidc-dex.crt | grep -oP '(?<=DNS:)[^,]+'
----

. Sign the `oidc-dex` server certificate with the trusted CA certificate.
+
Please refer to <<trusted-server-certificate>> on how to sign the trusted certificate. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.
+
Then, import your trusted certificate into the {kube} cluster.
The trusted CA certificates is `<TRUSTED_CA_CERT_PATH>`, trusted server certificate and key are `<SIGNED_OIDC_DEX_SERVER_CERT_PATH>` and `<SIGNED_OIDC_DEX_SERVER_KEY_PATH>`.

. Create a secret manifest file [path]`oidc-dex-cert.yaml` and update the secret data `ca.crt`, `tls.crt`, and `tls.key` with base64; encoded with trusted CA certificate, signed oidc-dex server certificate and key respectively.
+
----
apiVersion: v1
kind: Secret
metadata:
  name: oidc-dex-cert
  namespace: kube-system
  labels:
    caasp.suse.com/skuba-addon: "true"
type: kubernetes.io/tls
data:
  ca.crt: cat <TRUSTED_CA_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.crt: cat <SIGNED_OIDC_DEX_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.key: cat <SIGNED_OIDC_DEX_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo
----

. Apply the secret manifest file and restart `oidc-dex` pods.
+
[source,bash]
----
kubectl replace -f oidc-dex-cert.yaml
kubectl rollout restart deployment/oidc-dex -n kube-system
----

* Replace the `oidc-gangway` server certificate:

. Backup the original `oidc-gangway` server certificate and key from secret resource.
+
[source,bash]
----
mkdir -p pki.bak
kubectl get secret oidc-gangway-cert -n kube-system -o yaml | tee pki.bak/oidc-gangway-cert.yaml > /dev/null

cat pki.bak/oidc-gangway-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | tee pki.bak/oidc-gangway.crt > /dev/null
cat pki.bak/oidc-gangway-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | tee pki.bak/oidc-gangway.key > /dev/null
----

. Get the original SAN IP address(es) and DNS(s), run:
+
[source,bash]
----
openssl x509 -noout -text -in pki.bak/oidc-gangway.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in pki.bak/oidc-gangway.crt | grep -oP '(?<=DNS:)[^,]+'
----

. Sign the `oidc-gangway` server certificate with the trusted CA certificate.
+
Please refer to <<trusted-server-certificate>> on how to sign the trusted certificate. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.
+
Then, import your trusted certificate into the {kube} cluster.
The trusted CA certificates is `<TRUSTED_CA_CERT_PATH>`, trusted server certificate and key are `<SIGNED_OIDC_GANGWAY_SERVER_CERT_PATH>` and `<SIGNED_OIDC_GANGWAY_SERVER_KEY_PATH>`.

. Create a secret manifest file [path]`oidc-gangway-cert.yaml` and update the secret data `ca.crt`, `tls.crt`, and `tls.key` with base64; encoded with trusted CA certificate, signed `oidc-gangway` server certificate and key respectively.
+
----
apiVersion: v1
kind: Secret
metadata:
  name: oidc-gangway-cert
  namespace: kube-system
  labels:
    caasp.suse.com/skuba-addon: "true"
type: kubernetes.io/tls
data:
  ca.crt: cat <TRUSTED_CA_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.crt: cat <SIGNED_OIDC_GANGWAY_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.key: cat <SIGNED_OIDC_GANGWAY_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo
----

. Apply the secret manifest file and restart `oidc-gangway` pods.
+
[source,bash]
----
kubectl replace -f oidc-gangway-cert.yaml
kubectl rollout restart deployment/oidc-gangway -n kube-system
----

== Automatic Certificate Renewal

{productname} renews the control plane certificates and kubeconfigs automatically in two ways:

. *During node upgrade*:
when the node is upgraded, all the kubeadm managed certificates and kubeconfigs, and kubelet client certificates get rotated.

. *Via the `kucero` addon*:
if the administrator is not willing to upgrade the cluster, the `kucero` (KUbernetes control plane CErtificate ROtation) addon rotates all the kubeadm managed certificates and kubeconfigs, and kubelet client and server certificates.
`Kucero` consists of two components:
  .. A kubeadm checker/renewer in the form of a DaemonSet, which is deployed on master nodes. It's job is to periodically check and renew control plane kubeadm managed certificates/kubeconfigs.
  .. A kubelet server CSR signer controller, which signs the kubelet server CSR with a kubelet CA cert/key pair. The signed server certificates are stored in `/var/lib/kubelet/pki` and `/var/lib/kubelet/pki/kubelet-server-current.pem` is a symlink to the last generated server certificate.

[NOTE]
====
During the kubelet client certificate signing flow, kubelet sends the kubelet client CSR into the {kube} cluster, after which the `kube-controller-manager` signs the kubelet client CSR with the Kubernetes CA cert/key pair.

The kubelet client deafult configuration uses a `kubelet-client-current.pem` file in the
`/var/lib/kubelet/pki` folder. This file is a symlink to the latest generated certificate.
====

=== Control Plane Nodes Certificate Rotation

Certificates are rotated in two ways:

. *During node upgrade*:
when doing a control plane update, `skuba node upgrade apply` runs `kubeadm upgrade` commands behind the scenes. `kubeadm upgrade apply` and
`kubeadm upgrade node` renews and uses new `kubeadm` managed certificates on the node, including those stored in kubeconfig files, regardless of the remaining time for which the certificate was still valid.

. *Via the kucero addon:*
.. A kubeadm checker/renewer: kucero periodically checks (default interval is 1 hour) the kubeadm managed certificates/kubeconfigs, and rotates the certificates/kubeconfigs if the residual time is less than the total time (default 720 hours). Administrators can change the default time to renew the certificates/kubeconfigs by adding `--renew-before=<duration>`` (duration format is XhYmZs) to the kucero daemonset _or_ change the default polling period for checking the certificates/kubeconfigs by adding `--polling-period=<duration>` (duration format is XhYmZs).
.. A kubelet server CSR signer controller: kucero signs the kubelet server CSR using the kubelet CA cert/key pair located in control plane node.


=== Worker Node Certificate Rotation

The kubelet client certificate are signed by kube-controller-manager and the kubelet server certificates are signed by the kucero addon.

== Manual Certificate Renewal

[IMPORTANT]
====
If you are running multiple master nodes, you need to run the followings
commands sequentially on all master nodes.
====

=== Renewing Certificates Managed by `kubeadm`

. To SSH into the master node, renew all `kubeadm` certificates and reboot,
run the following:
+
[source,bash]
----
ssh <USERNAME>@<MASTER_NODE_IP_ADDRESS/FQDN>
sudo cp -r /etc/kubernetes/pki /etc/kubernetes/pki.bak
sudo kubeadm alpha certs renew all
sudo systemctl restart kubelet
----
+
. Copy the renewed `admin.conf` from one of the master nodes to your local environment:
+
[source,bash]
----
ssh <USERNAME>@<MASTER_NODE_IP_ADDRESS/FQDN>
sudo cat /etc/kubernetes/admin.conf
----

=== Renewing Certificates Created by `skuba`:

In the admin node, regenerate the certificates:

* Replace the `oidc-dex` server certificate:
+
. Backup the original `oidc-dex` server certificate and key from secret resource.
+
[source,bash]
----
mkdir -p my-cluster/pki.bak
kubectl get secret oidc-dex-cert -n kube-system -o yaml | tee my-cluster/pki.bak/oidc-dex-cert.yaml > /dev/null

cat my-cluster/pki.bak/oidc-dex-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | tee my-cluster/pki.bak/oidc-dex.crt > /dev/null
cat my-cluster/pki.bak/oidc-dex-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | tee my-cluster/pki.bak/oidc-dex.key > /dev/null
----

. Get the original SAN IP address(es) and DNS(s), run:
+
[source,bash]
----
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-dex.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-dex.crt | grep -oP '(?<=DNS:)[^,]+'
----

. Sign the `oidc-dex` server certificate with the default kubernetes CA certificate _or_ trusted CA certificate.
.. Default kubernetes CA certificate
+
Please refer to <<self-signed-server-certificate>> on how to sign the self signed server certificate. The default kubernetes CA certificate and key are located at `/etc/kubernetes/pki/ca.crt` and `/etc/kubernetes/pki/ca.key`. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.
+
.. Trusted CA certificate
+
Please refer to <<trusted-server-certificate>> on how to sign the trusted server certificate. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.

. Import your certificate into the {kube} cluster.
The CA certificate is `<CA_CERT_PATH>`, server certificate and key are `<SIGNED_OIDC_DEX_SERVER_CERT_PATH>` and `<SIGNED_OIDC_DEX_SERVER_KEY_PATH>`.

. Create a secret manifest file [path]`oidc-dex-cert.yaml` and update the secret data `ca.crt`, `tls.crt`, and `tls.key` with base64; encoded with CA certificate, signed `oidc-dex` server certificate and key respectively.
+
----
apiVersion: v1
kind: Secret
metadata:
  name: oidc-dex-cert
  namespace: kube-system
  labels:
    caasp.suse.com/skuba-addon: "true"
type: kubernetes.io/tls
data:
  ca.crt: cat <CA_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.crt: cat <SIGNED_OIDC_DEX_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.key: cat <SIGNED_OIDC_DEX_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo
----

. Apply the secret manifest file and restart `oidc-dex` pods.
+
[source,bash]
----
kubectl replace -f oidc-dex-cert.yaml
kubectl rollout restart deployment/oidc-dex -n kube-system
----

* Replace the `oidc-gangway` server certificate:
+
. Backup the original `oidc-gangway` server certificate and key from secret resource.
+
[source,bash]
----
mkdir -p my-cluster/pki.bak
kubectl get secret oidc-gangway-cert -n kube-system -o yaml | tee my-cluster/pki.bak/oidc-gangway-cert.yaml > /dev/null

cat my-cluster/pki.bak/oidc-gangway-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | tee my-cluster/pki.bak/oidc-gangway.crt > /dev/null
cat my-cluster/pki.bak/oidc-gangway-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | tee my-cluster/pki.bak/oidc-dgangwayex.key > /dev/null
----

. Get the original SAN IP address(es) and DNS(s), run:
+
[source,bash]
----
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-gangway.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-gangway.crt | grep -oP '(?<=DNS:)[^,]+'
----

. Sign the `oidc-gangway` server certificate with the default kubernetes CA certificate _or_ trusted CA certificate.
.. Default kubernetes CA certificate
+
Please refer to <<self-signed-server-certificate>> on how to sign the self signed server certificate. The default kubernetes CA certificate and key are located at `/etc/kubernetes/pki/ca.crt` and `/etc/kubernetes/pki/ca.key`. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.
+
.. Trusted CA certificate
+
Please refer to <<trusted-server-certificate>> on how to sign the trusted server certificate. The `server.conf` for IP.1 is the original SAN IP address if present, DNS.1 is the original SAN DNS if present.

. Import your certificate into the {kube} cluster.
The CA certificates is `<CA_CERT_PATH>`, server certificate and key are `<SIGNED_OIDC_GANGWAY_SERVER_CERT_PATH>` and `<SIGNED_OIDC_GANGWAY_SERVER_KEY_PATH>`.

. Create a secret manifest file [path]`oidc-gangway-cert.yaml` and update the secret data `ca.crt`, `tls.crt`, and `tls.key` with base64; encoded with CA certificate, signed `oidc-gangway` server certificate and key respectively.
+
----
apiVersion: v1
kind: Secret
metadata:
  name: oidc-gangway-cert
  namespace: kube-system
  labels:
    caasp.suse.com/skuba-addon: "true"
type: kubernetes.io/tls
data:
  ca.crt: cat <CA_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.crt: cat <SIGNED_OIDC_GANGWAY_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
  tls.key: cat <SIGNED_OIDC_GANGWAY_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo
----

. Apply the secret manifest file and restart `oidc-gangway` pods.
+
[source,bash]
----
kubectl replace -f oidc-gangway-cert.yaml
kubectl rollout restart deployment/oidc-gangway -n kube-system
----

* Replace the `kubelet` server certificate:
+
[IMPORTANT]
====
You need to generate `kubelet` server certificate for all the nodes on one of control plane nodes.
The `kubelet` CA certificate key only exists on the control plane nodes.
Therefore, after generating re-signed `kubelet` server certificate/key for worker nodes, you have to copy each `kubelet` server certificate/key from the control plane node to the corresponding worker node.
====
. Backup the original `kubelet` certificates and keys.
+
[source,bash]
----
sudo cp -r /var/lib/kubelet/pki /var/lib/kubelet/pki.bak
----
+
. Sign each node `kubelet` server certificate with the CA certificate/key `/var/lib/kubelet/pki/kubelet-ca.crt` and `/var/lib/kubelet/pki/kubelet-ca.key`, make sure that the signed server certificate SAN is the same as the origin.
To get the original SAN IP address(es) and DNS(s), run:
+
[source,bash]
----
openssl x509 -noout -text -in /var/lib/kubelet/pki.bak/kubelet.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /var/lib/kubelet/pki.bak/kubelet.crt | grep -oP '(?<=DNS:)[^,]+'
----
+
. Finally, update the `kubelet` server certificate and key file `/var/lib/kubelet/kubelet.crt` and `/var/lib/kubelet/kubelet.key` respectively, and restart `kubelet` service.
+
[source,bash]
----
sudo cp <CUSTOM_KUBELET_SERVER_CERT_PATH> /var/lib/kubelet/pki/kubelet.crt
sudo cp <CUSTOM_KUBELET_SERVER_KEY_PATH> /var/lib/kubelet/pki/kubelet.key
chmod 644 /var/lib/kubelet/pki/kubelet.crt
chmod 600 /var/lib/kubelet/pki/kubelet.key

sudo systemctl restart kubelet
----

== How To Generate Certificates

[#trusted-signed-certificate]
=== Trusted 3rd-Party Signed Certificate

[#trusted-server-certificate]
==== Trusted Server Certificate

. Generate a private key by following the steps below from a terminal window:
+
[source,bash]
----
openssl genrsa -aes256 -out server.key 2048
----
+
Type the pass phrase to protect the key and press [Enter]
+
Re-enter the pass phrase.
. Create a file _server.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CZ // <1>
ST = CZ // <2>
L = Prague // <3>
O = example // <4>
OU = com // <5>
CN = server.example.com // <6>
emailAddress = admin@example.com // <7>

[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
IP.1 = <SERVER-IP-ADDRESS> // <8>
DNS.1 = <SERVER-FQDN> // <9>
----
<1> Country Name (2 letter code).
<2> State or Province Name (full name).
<3> Locality Name (eg, city).
<4> Organization Name (eg, company).
<5> Organizational Unit Name (eg, section).
<6> Common Name (e.g. server FQDN or YOUR name)
<7> Email Address
<8> Server IP address if present. Add more IP.X below if the server has more than one IP address.
Remove IP.1 if the server uses FQDN.
<9> Server FQDN if present. Add more DNS.X below if the server has more than one domain name.
Remove DNS.1 if the server uses an IP address.

. Generate a certificate signing request (CSR)
+
[source,bash]
----
openssl req -new -key server.key -config server.conf -out server.csr
----
Enter the pass phrase of the private key created in Step 1.
+
Check the certificate signing request (CSR)
+
[source,bash]
----
openssl req -text -noout -verify -in server.csr
----

. Sign the certificate
+
Send the certificate signing request (CSR) to the 3rd party for signing.
You should receive the following files in return:
+
.. Server certificate (public key)
.. Intermediate CA and/or bundles that chain to the Trusted Root CA

[#trusted-client-certificate]
==== Trusted Client Certificate

. Generate a private key by following the steps below from a terminal window:
+
[source,bash]
----
openssl genrsa -aes256 -out client.key 2048
----
+
Type the pass phrase to protect the key and press [Enter]
+
Re-enter the pass phrase.
. Create a file _client.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CZ // <1>
ST = CZ // <2>
L = Prague // <3>
O = example // <4>
OU = com // <5>
CN = client.example.com // <6>
emailAddress = admin@example.com // <7>

[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
----
<1> Country Name (2 letter code).
<2> State or Province Name (full name).
<3> Locality Name (eg, city).
<4> Organization Name (eg, company).
<5> Organizational Unit Name (eg, section).
<6> Common Name (e.g. client FQDN or YOUR name)
<7> Email Address

. Generate a certificate signing request (CSR)
+
[source,bash]
----
openssl req -new -key client.key -config client.conf -out client.csr
----
Enter the pass phrase of the private key created in Step 1.
+
Check the certificate signing request (CSR)
+
[source,bash]
----
openssl req -text -noout -verify -in client.csr
----

. Sign the certificate
+
Send the certificate signing request (CSR) to the 3rd party for signing.
You should receive the following files in return:
+
.. Client certificate (public key)
.. Intermediate CA and/or bundles that chain to the Trusted Root CA

[#self-signed-certificate]
=== Self-signed Server Certificate

[NOTE]
====
In the case that you decide to use self-signed certificates, make sure that the Certificate Authority
used for signing is configured securely as a trusted Certificate Authority on the clients.
====

In some cases you want to create self-signed certificates for testing.
If you are using proper trusted 3rd-party CA signed certificates, skip the following steps and refer to <<trusted-server-certificate>>.

[#self-signed-ca-certificate]
==== Self-signed CA Certificate

. Create a file _ca.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_ca
prompt = no

[req_distinguished_name]
C = CZ // <1>
ST = CZ // <2>
L = Prague // <3>
O = example // <4>
OU = com // <5>
CN = Root CA // <6>
emailAddress = admin@example.com // <7>

[v3_ca]
basicConstraints = critical,CA:TRUE
keyUsage = critical,digitalSignature,keyEncipherment,keyCertSign
----
<1> Country Name (2 letter code).
<2> State or Province Name (full name).
<3> Locality Name (eg, city).
<4> Organization Name (eg, company).
<5> Organizational Unit Name (eg, section).
<6> Common Name (e.g. server FQDN or YOUR name)
<7> Email Address

. Sign the CA certificate
+
[source,bash]
----
openssl genrsa -out ca.key 2048
openssl req -key ca.key -new -x509 -days 3650 -sha256 -config ca.conf -out ca.crt
----

[#self-signed-server-certificate]
==== Self-signed Server Certificate

. Create a file _server.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CZ // <1>
ST = CZ // <2>
L = Prague // <3>
O = example // <4>
OU = com // <5>
CN = example.com // <6>
emailAddress = admin@example.com // <7>

[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
IP.1 = <SERVER-IP-ADDRESS> // <8>
DNS.1 = <SERVER-FQDN> // <9>
----
<1> Country Name (2 letter code).
<2> State or Province Name (full name).
<3> Locality Name (eg, city).
<4> Organization Name (eg, company).
<5> Organizational Unit Name (eg, section).
<6> Common Name (e.g. server FQDN or YOUR name)
<7> Email Address
<8> Server IP address if present. Add more IP.X below if the server has more than one IP address.
Remove IP.1 if the server uses FQDN.
<9> Server FQDN if present. Add more DNS.X below if the server has more than one domain name.
Remove DNS.1 if the server uses an IP address.

. Generate the certificate
+
[source,bash]
----
openssl genrsa -out server.key 2048
openssl req -key server.key -new -sha256 -out server.csr -config server.conf
openssl x509 -req -CA ca.crt -CAkey ca.key -CAcreateserial -in server.csr -out server.crt -days 365 -extensions v3_req -extfile server.conf
----
+
Check the signed certificate
+
[source,bash]
----
openssl x509 -text -noout -in server.crt
----

[#self-signed-client-certificate]
==== Self-signed Client Certificate

. Create a file _client.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CZ // <1>
ST = CZ // <2>
L = Prague // <3>
O = example // <4>
OU = com // <5>
CN = client.example.com // <6>
emailAddress = admin@example.com // <7>

[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
----
<1> Country Name (2 letter code).
<2> State or Province Name (full name).
<3> Locality Name (eg, city).
<4> Organization Name (eg, company).
<5> Organizational Unit Name (eg, section).
<6> Common Name (e.g. server FQDN or YOUR name)
<7> Email Address

. Generate the certificate
+
[source,bash]
----
openssl genrsa -out client.key 2048
openssl req -key client.key -new -sha256 -out client.csr -config client.conf
openssl x509 -req -CA ca.crt -CAkey ca.key -CAcreateserial -in client.csr -out client.crt -days 365 -extensions v3_req -extfile client.conf
----
+
Check the signed certificate
+
[source,bash]
----
openssl x509 -text -noout -in client.crt
----
