//= Cluster Management

Cluster management refers to several processes in the lifecycle of a cluster an its individual nodes: bootstrapping, joining, removing and resetting nodes.
For maximum automation and ease {productname} uses the skuba tool, which simplifies Kubernetes cluster creation and reconfiguration.


== Prerequisites

To create and manage clusters you first need to:

- install skuba on your local workstation
- have virtual machines running and have their IP/FQDN ready.
//TODO: other prerequisites, see deployment guide


== Bootstrapping the cluster

Bootstrapping the cluster is the initial process of starting up a minimal viable cluster
and joining the first master node. The first master node needs to be bootstrapped, later nodes can simply be joined.

[TIP]
====
If you used terraform to set up your virtual machines,
you can print the relevant IP addresses,
which you will need in this section by running:
`terraform output`
====


=== Initializing the cluster

Before bootstrapping any nodes to the cluster,
you need to create an empty cluster or in other words initialize a directory for your cluster.
This is done using the `skuba cluster init` command and the `control-plane` flag:

[source,bash]
skuba cluster init --control-plane <LB IP/FQDN> <cluster-name>

- The `--control-plane` flag specifies the IP/FQDN of your load balancer.
If you do not use a load balancer use the IP/FQDN of your first master node.
- Substitute `<cluster-name>` for a suitable name for your cluster and hence the resulting directory.


=== Bootstrapping the cluster

To add the first master node use the `skuba node bootstrap` command:

[source,bash]
skuba node bootstrap --user <user-name> --sudo --target <IP/FQDN> <master-node>

The mandatory flags for this command are `--user`, `--sudo` and `--target`.
Provide the following information:
- `--sudo` is for running the command with superuser privileges,
this is required for all node operations.
- `<user-name>` is the instance user name defined in the `terraform.tfvars` file.
- `<IP/FQDN>` is the IP address or FQDN of the relevant virtual machine.
- Substitute `<master-node>` for a unique master node name.


== Adding nodes

Once you have added the first master node to the cluster,
use the `skuba node join` command to add more nodes.

[source,bash]
skuba node join --role <master/worker> --user <user-name> --sudo --target <IP/FQDN> <node-name>

The mandatory flags for the join command are `--role`, ``--user`, `--sudo` and `--target`.

- `--role` serves to specify if the node is a *master* or *worker*
- `--sudo` is for running the command with superuser privileges.
- `<user-name>` is the instance user name defined in the `terraform.tfvars` file.
- `<IP/FQDN>` is the IP address or FQDN of the relevant virtual machine.
- Substitute `<node-name>` for a unique node name.

For example to add a *new master node* you would run something like this:

[source,bash]
skuba node join --role master --user sles --sudo --target 10.86.2.165 master2

To add a *new worker node*, the process is essentially the same:

[source,bash]
skuba node join --role worker --user sles --sudo --target 10.86.2.164 worker1

[TIP]
====
Use `skuba cluster status` to check that nodes have been successfully joined.
====


== Removing nodes

The `skuba node remove` command serves to *permanently* remove nodes.
Running this command will work even if the target virtual machine is down,
so it is the safest way to remove the node.

[source,bash]
skuba node remove <node-name>

If you wish to remove the node and want to add it again, the recommended approach is to
first drain the node using `kubectl`. This will also cordon the node,
so that it doesn't receive any new workloads.
When you want to bring the node back, you only have to uncordon it.
Refer to the official Kubernetes documentation for more information:
https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#use-kubectl-drain-to-remove-a-node-from-service


== Resetting nodes

The `skuba node reset` command enables you to reset a node to a state prior to join or bootstrap being run.
Use this command to retry a failed bootstrap or join on a node or if the node fails.

[source,bash]
skuba node reset --target <IP/FQDN> --sudo --user <user-name>


== Reconfiguring nodes

To reconfigure a node, for example to change the node role from worker to master,
you will need to use a combination of commands.

1. Run `skuba node remove <node-name>`.
2. Reinstall the node from scratch.
3. Run `skuba node join --role <desired-role> -user <user-name> --sudo --target <IP/FQDN> <node-name>`
