== Deployment On AWS

Use Helm CLI to install Velero deployment.

=== {kube} cluster on AWS and _without_ backup persistent volume.

For the case that the {kube} cluster does not use AWS EBS.

The backup location on AWS S3.

. The backup bucket name _BUCKET_NAME_. (The bucket name in AWS S3 object storage)
. The backup region name _REGION_NAME_. (The region name for the AWS S3 object storage. For example, `us-east-1` for AWS US East (N. Virginia))
. The Velero installed namespace _NAMESPACE_, the default namespace is `velero`. (optional)
+
[source,bash]
----
helm install \
    --name velero \
    --namespace <NAMESPACE> \
    --set-file credentials.secretContents.cloud=credentials-velero \
    --set configuration.provider=aws \
    --set configuration.backupStorageLocation.name=default \
    --set configuration.backupStorageLocation.bucket=<BUCKET_NAME> \
    --set configuration.backupStorageLocation.config.region=<REGION_NAME> \
    --set snapshotsEnabled=false \
    --set initContainers[0].name=velero-plugin-for-aws \
    --set initContainers[0].image=registry.suse.com/caasp/v4/velero-plugin-for-aws:1.0.1 \
    --set initContainers[0].volumeMounts[0].mountPath=/target \
    --set initContainers[0].volumeMounts[0].name=plugins \
    suse/velero
----
+
[NOTE]
====
If Velero installed other than default namespace `velero`, setup velero config config to the Velero installed namespace.
----
velero client config set namespace=<NAMESPACE>
----
====

=== {kube} cluster on AWS and _with_ backup persistent volume.

For the case that the {kube} cluster uses external storage (AWS EBS).

The backup location on AWS S3.

. The backup bucket name _BUCKET_NAME_. (The bucket name in AWS S3 object storage)
. The backup region name _REGION_NAME_. (The region name for the AWS S3 object storage. For example, `us-east-1` for AWS US East (N. Virginia))
. The Velero installed namespace _NAMESPACE_, the default namespace is `velero`. (optional)
+
[source,bash]
----
helm install \
    --name velero \
    --namespace <NAMESPACE> \
    --set-file credentials.secretContents.cloud=credentials-velero \
    --set configuration.provider=aws \
    --set configuration.backupStorageLocation.name=default \
    --set configuration.backupStorageLocation.bucket=<BUCKET_NAME> \
    --set configuration.backupStorageLocation.config.region=<REGION_NAME> \
    --set snapshotsEnabled=true \
    --set configuration.volumeSnapshotLocation.name=default \
    --set configuration.volumeSnapshotLocation.config.region=<REGION_NAME> \
    --set initContainers[0].name=velero-plugin-for-aws \
    --set initContainers[0].image=registry.suse.com/caasp/v4/velero-plugin-for-aws:1.0.1 \
    --set initContainers[0].volumeMounts[0].mountPath=/target \
    --set initContainers[0].volumeMounts[0].name=plugins \
    suse/velero
----
+
[NOTE]
====
If Velero installed other than default namespace `velero`, setup velero config config to the Velero installed namespace.
----
velero client config set namespace=<NAMESPACE>
----
====

[NOTE]
For troubleshooting a velero deployment, refer to link:https://velero.io/docs/v1.3.1/debugging-install/[Velero: Debugging Installation Issues]
