[#sec-admin-security-role]
= Role Management

{productname}
uses _role-based access control_ authorization for {kube}.
Roles define, which _subjects_ (users or groups) can use which _verbs_ (operations) on which __resources__.
The following sections provide an overview of the resources, verbs and how to create roles.
Roles can then be assigned to users and groups.

[#sec-admin-security-role-verb]
== List of Verbs


This section provides an overview of the most common _verbs_ (operations) used for defining roles.
Verbs correspond to sub-commands of `kubectl`.

create::
Create a resource.

delete::
Delete resources.

deletecollection::
Delete a collection of a resource (can only be invoked using the {kube} API).

get::
Display individual resource.

list::
Display collections.

patch::
Update an API object in place.

proxy::
Allows running `kubectl` in a mode where it acts as a reverse proxy.

update::
Update fields of a resource, for example annotations or labels.

watch::
Watch resource.


[#sec-admin-security-role-resource]
== List of Resources


This section provides an overview of the most common _resources_ used for defining roles.

Autoscaler::
{kubedoc}tasks/run-application/horizontal-pod-autoscale/

ConfigMaps::
{kubedoc}tasks/configure-pod-container/configure-pod-configmap/

Cronjob::
{kubedoc}concepts/workloads/controllers/cron-jobs/

DaemonSet::
{kubedoc}concepts/workloads/controllers/daemonset/

Deployment::
{kubedoc}concepts/workloads/controllers/deployment/

Ingress::
{kubedoc}concepts/services-networking/ingress/

Job::
{kubedoc}concepts/workloads/controllers/jobs-run-to-completion/

Namespace::
{kubedoc}concepts/overview/working-with-objects/namespaces/

Node::
{kubedoc}concepts/architecture/nodes/

Pod::
{kubedoc}concepts/workloads/pods/pod-overview/

Persistent Volumes::
{kubedoc}concepts/storage/persistent-volumes/

Secrets::
{kubedoc}concepts/configuration/secret/

Service::
{kubedoc}concepts/services-networking/service/

ReplicaSets::
{kubedoc}concepts/workloads/controllers/replicaset/


[#sec-admin-security-role-create]
== Creating Roles


Roles are defined in YAML files.
To apply role definitions to {kube}, use `kubectl apply -f YAML_FILE`.
The following examples provide an overview about different use cases of roles.

.Simple Role for Core Resource
====
This example allows to `get`, `watch` and `list` all `pods` in the namespace `default`.

----
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-pods <1>
  namespace: default <2>
rules:
- apiGroups: [""] <3>
  resources: ["pods"] <4>
  verbs: ["get", "watch", "list"] <5>
----
<1> Name of the role. This is required to associate the rule with
    a group or user. For details, refer to
    <<sec-admin-security-role-create_binding>>.

<2> Namespace the new group should be allowed to access. Use `default`
for {kube}' default namespace.

<3> {kube} API groups. Use `""` for the core group. Use
`kubectl api-resources` to list all API groups.

<4> {kube} resources. For a list of available resources, refer to
 <<sec-admin-security-role-resource>>.

<5> {kube} verbs. For a list of available verbs, refer to
<<sec-admin-security-role-verb>>.

====

.Cluster Role for Creation of Pods
====
This example creates a cluster role to allow `create pods` clusterwide.
Note the `ClusterRole` value for [option]`kind`.

----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-create-pods <1>
rules:
- apiGroups: [""] <2>
  resources: ["pods"] <3>
  verbs: ["create"] <4>
----
<1>  a group or user. For details, refer to <<sec-admin-security-role-create_binding>>.

<2> {kube} API groups. Use `""` for the core group. Use
`kubectl api-resources` to list all API groups.

<3> {kube} resources. For a list of available resources, refer to <<sec-admin-security-role-resource>>.

<4> {kube} verbs. For a list of available verbs, refer to <<sec-admin-security-role-verb>>.

====

[#sec-admin-security-role-create_binding]
== Create Role Bindings


To bind a group or user to a role, create a YAML file that contains the role binding description.
Then apply the binding with `kubectl apply -f YAML_FILE`.
The following examples provide an overview about different use cases of role bindings.

[#q]
.Binding a Group to a Role
====
This example shows how to bind a group to a defined role.

----
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <ROLE_BINDING_NAME> <1>
  namespace: <NAMESPACE> <2>
subjects:
- kind: Group
  name: <LDAP_GROUP_NAME> <3>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: <ROLE_NAME> <4>
  apiGroup: rbac.authorization.k8s.io
----
<1> Defines a name for this new role binding.

<2> Name of the namespace to which the binding applies.

<3> Name of the LDAP group to which this binding applies.

<4> Name of the role used. For defining rules, refer to
<<sec-admin-security-role-create>>.

====

[#ex-admin-security-groups-cluster-role]
.Binding a Group to a Cluster Role
====
This example shows how to bind a group to a defined cluster role.

----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <CLUSTER_ROLE_BINDING_NAME> <1>
subjects:
- kind: Group
  name: <CLUSTER_GROUP_NAME> <2>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: <CLUSER_ROLE_NAME> <3>
  apiGroup: rbac.authorization.k8s.io
----

<1> Defines a name for this new cluster role binding.

<2> Name of the LDAP group to which this binding applies.

<3> Name of the role used. For defining rules, refer to <<sec-admin-security-role-create>>.


====

[IMPORTANT]
====
When creating new Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings, it is important to keep in mind the `Principle of Least Privilege`:

_"define rules such that the account bound to the Role or ClusterRole has the minimum
amount of permissions needed to fulfill its purpose and no more."_

For instance, granting the `admin` ClusterRole to most accounts is most likely unnecessary,
when a reduced-scope role would be enough fulfill the account's purpose.
This helps reduce the attack surface if an account is compromised.

It is also recommended to periodically review your Roles and ClusterRoles to ensure they are still required and are not overly-permissive.
====
