//= Troubleshooting

This chapter summarizes frequent problems that can occur while using {productname}
and their solutions.

Additionally, {suse} support collects problems and their solutions online at link:https://www.suse.com/support/kb/?id=SUSE_CaaS_Platform[] .

== The `supportconfig` tool

As a first step for any troubleshooting/debugging effort, you need to find out
where the problem is caused. For this purpose we ship the `supportconfig` tool
and plugin with {productname}. With a simple command you can collect and compile
a variety of details about your cluster to enable {suse} support to pinpoint
the potential cause of an issue.

In case of problems, a detailed system report can be created with the
`supportconfig` command line tool. It will collect information about the system such as:

* Current Kernel version
* Hardware information
* Installed packages
* Partition setup
* Cluster and node status

[TIP]
====
A full list of of the data collected by `supportconfig` can be found under
https://github.com/SUSE/supportutils-plugin-suse-caasp/blob/master/README.md.
====

To collect all relevant logs run the `supportconfig` command on all the master
and worker nodes individually.

[source,bash]
----
supportconfig
tar -xvJf /var/log/nts_*.txz
cd nts*
cat kubernetes.txt crio.txt
----

The result is a TAR archive of files. Each of the tar files should be given a name that can be used to identify which
cluster node it was created on.

After opening a Service Request (SR), you can upload the TAR archives to Global Technical Support.

The data will help to locate the issue you reported and assist you in solving the problem.
For details, see https://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_adm_support.html.
