[[_cha.admin.misc]]
= Miscellaneous Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Miscellaneous Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images

[[_sec.admin.misc.timezone]]
== Configuring Timezone


To configure the timezone during deployment you can use [command]``cloud-init`` or [command]``{ay}`` during the initial installation procedure.
If you wish to change the timezone for an existing cluster, you must update it manually using [command]``Salt``. 

=== New Deployment

==== Using cloud-init

<<_sec.deploy.cloud_init.user_data.timezone>>

==== Using {ay}


Use a modified {ay}
control file as described in <<_sec.deploy.autoyast>>. 

=== Existing Deployment


To change the timezone on an existing cluster you must use [command]``Salt`` to remove the [path]``/etc/localtime``
 symlink and replace it with the desired timezone file from [path]``/usr/share/zoneinfo``
 in its place.
SSH into the Admin node and run: 

----
{prompt.user}``docker exec -it $(docker ps -q -f name="salt-master") \
salt -P 'roles:(admin|kube-master|kube-minion)' \
cmd.run "ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime"`` 
----

[[_sec.admin.misc.issue_generator]]
== The [command]``issue-generator`` Command


On {suse}{mos}
, [path]``/etc/issue``
 is generated by [command]``issue-generator``. 

This allows {mos}
to display a dynamic message above the login prompt, which is generated from the contents of several different files. 

Files in [path]``/etc/issue.d``
 override files with the same name in [path]``/usr/lib/issue.d``
 and [path]``/run/issue.d``
.
Files in [path]``/run/issue.d``
 override files with the same name in [path]``/usr/lib/issue.d``
. 

Packages should install their configuration files in [path]``/usr/lib/issue.d``
.
Files in [path]``/etc/issue.d``
 are reserved for the local administrator, who may use this logic to override the files installed by vendor packages. 

All configuration files are sorted by their filename in lexicographic order, regardless of which of the directories they reside in. 

If you run the command without any arguments, all the input files will be applied. 

Which network interfaces are shown can be configured in the file [path]``/etc/sysconfig/issue-generator``
. 

To disable the display of ssh keys, use the following command: 

----
{prompt.root}``systemctl disable issue-add-ssh-keys.service`` 
----