= Centralized Logging

Centralized Logging is a means of collecting logs from CaaS Platform for centralized management.
It forwards system and Kubernetes cluster logs to a specified external logging service,
for example, Rsyslog server.

Collecting logs in a central location can serve for audit or debug purposes or to analyze and visually present data.

== Types of logs

You can log the following groups of services, see the Usage section

Kubernetes System Components::
* Kubelet
* Cri-o

Kubernetes Control Plane Components::
* API Server
* Controller Manager
* Scheduler
* Cilium
* Kube-proxy
* all resources in the kube-system namespaces

Kubernetes Namespaces Pods::
* All namespaces in cluster except kube-system

OS Components::
* Kernel
* Audit
* Zypper
* Network (wicked)

Centralized logging is also restricted to the following protocols: UDP, TCP, TCP + TLS, TCP + mTLS.


== Queuing

Centralized Logging supports a configurable buffered queue.
This can be used to improve log processing throughput and eliminate possible data loss,
for instance after log agents shutdown, restart or in case of an unresponsive remote server.

//TODO: how is this queue configured?

== Log formats

The two supported syslog message formats are *RFC 5424* and *RFC 3164*.

[NOTE]
====
The Kubernetes cluster metadata is included in the RFC 5424 message.
====

Example RFC 3164
----
2019-05-30T09:11:21.968458+00:00 worker1 k8s.system/crio[12080] level=debug msg="Endpoint successfully created" containerID=caa46f14a68e766b877af01442e58731845bb45d8ce1f856553440a02c958b2f eventUUID=e2405f2a-82ba-11e9-9a06-fa163eebdfd6 subsys=cilium-cni
----

Example RFC 5424
----
<133>1 2019-05-30T08:28:38.784214+00:00 master0 k8s.pod/kube-system/kube-apiserver-master0/kube-apiserver - - [kube_meta namespace_id=1e030def-81db-11e9-a62b-fa163e1876c9 container_name=kube-apiserver creation_timestamp=2019-05-29T06:29:31Z host=master0 namespace_name=kube-system master_url=https://kubernetes.default.svc.cluster.local:443 pod_id=4aaf10f9-81db-11e9-a62b-fa163e1876c9 pod_name=kube-apiserver-master0] 2019-05-30T08:28:38.783780355+00:00 stderr F I0530 08:28:38.783710       1 log.go:172] http: TLS handshake error from 172.28.0.19:45888: tls: client offered only unsupported versions: [300]
----

//TODO: Here I would line breaks for better readability,
// so that the user doesn't have to scroll through the entire line.
// Where would it logically make sense to add these?

== Installing Helm and Tiller

In order to successfully use Centralized Logging, you first need to install `Helm` and `Tiller`.
Helm is used to install the log agents and provide custom logging settings.

- As of {productname} {productversion},
Helm is not part of the {productname} package repository, so to use Centralized Logging,
install the {productname} 3 package to install the Helm client:

//TODO: where do I have to be to run these commands?

[source,bash]
----
sudo zypper addrepo http://download.suse.de/ibs/SUSE/Updates/SUSE-CAASP/3.0/x86_64/update/SUSE:Updates:SUSE-CAASP:3.0:x86_64.repo
sudo zypper refresh
sudo zypper install -y helm

helm init --client-only
----

The official Helm installation can also be used to setup the Helm client and server side.

//TODO: link to official docs or provide specific steps.

////
Note: what follows here are the instutions to be included after the Helm package has been integrated into v4:
To install Helm, use the common zypper command:
----
sudo zypper install helm
----

Then initialize the Helm client by running:
----
helm init --client-only
----
////


- As of {productname} {productversion},
Tiller is not part of the {productname} package repository,
so to install the {productname} 3 Tiller container image:

[source,bash]
----
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --tiller-image registry.suse.com/sles12/tiller:2.8.2 --service-account tiller
----

//TODO: What do we expect to happen here? Expected output after `helm init ...`

////
Note: When Helm is included in v4, Tiller server will be automatically installed after CaaS Platform setup.
So we probably  just need to mention that we use it and that it's installed automatically.
////

== Deployment

After you have successfully installed it,
use Helm CLI to install log agents on each node,
and provide customized settings via specific command options.

The only three mandatory parameters for a successful deployment of Centralized Logging
are:

* `*server.host*`, default value = rsyslog-server.default.svc.cluster.local
* `*server.port*`, default value = 514
* `*server.protocol*`, default value = TCP

See <<Optional settings>> for the facultative parameters and their default values.

- Running the following will create the minimal working setup:

[source,bash]
----
helm repo add suse-charts https://kubernetes-charts.suse.com
helm install stable/log-agent-rsyslog --name ${RELEASE_NAME} --set server.host=${SERVER_HOST} --set server.port=${SERVER_PORT}
----

//TODO: one of the three mandatory settings is the server.protocol,
//but it's not set above. Where is it set?


After this step, all of the log agents will initialize then start to forward logs from each host to the configured remote Rsyslog server.

- To check the installation progress, use the `helm status` command:
----
helm status ${RELEASE_NAME}
----

- To uninstall log agents, use the `helm delete` command:
----
helm delete --purge ${RELEASE_NAME}
----

//TODO: include optional settings and their descriptions.
//TODO: work the notes about Queue files etc.

== Optional settings
