== Disable automatic updates

Nodes added to a cluster have the service `skuba-update.timer`, which is responsible for running automatic updates, activated by default. To disable the automatic updates on a node simply `ssh` to it and then disable the skuba-update service on that node:
----
systemctl disable --now skuba-update.timer
----

== Completely disable reboots

If you would like to take care of reboots manually, either as a temporary measure or permanently, you can disable them by creating a lock:

----
kubectl -n kube-system annotate ds kured weave.works/kured-node-lock='{"nodeID":"manual"}'
----

This command modifies an annotation (`annotate`) on the daemonset (`ds`) named `kured`.
You must replace `"nodeID"` with the ID of the cluster node that you wish to lock out of automatic reboots.

== Manual unlock

In exceptional circumstances, such as a node experiencing a permanent failure whilst rebooting, manual intervention may be required to remove the cluster lock:

----
kubectl -n kube-system annotate ds kured weave.works/kured-node-lock-
----

This command modifies an annotation (`annotate`) on the daemonset (`ds`) named `kured`.
