[#caasp-migrate-4.5]
== Migration to {productname} 4.5

1) The server should be connected to servers like SCC or RMT. Other migration scenarios are covered in the SLES upgrade guide.

[NOTE]
====
In order to reconnect your system to the registration server, run:
`SUSEConnect -r <your SCC key> SUSEConnect -p sle-module-containers/15.1/x86_64 -r <your SCC key>`
====

2) You also need the new `zypper migration` plugin. This plugin is used to perform the needed tasks in order to migrate the node itself to the latest version of {platform}, such as updating the repositories to the new ones, and calling `zypper dup`. This plugin is provided by the `zypper-migration-plugin` package. Therefore, install the `zypper-migration-plugin` package:

----
zypper -n in zyppper-migration-plugin
----

3) Then, run the newly installed `zypper-migration` plugin (on the management node first, then on the rest of the nodes):

----
zypper migration
----

[NOTE]
====
If you want migration to progress non-interactive, you can add flags: `--non-interactive --auto-agree-with-licenses`
====
[NOTE]
====
That's how your `zypper lr -puU` should look like after the migration:
#  | Alias                                                                                           | Name                                                   | Enabled | GPG Check | Refresh | Priority | URI
---+-------------------------------------------------------------------------------------------------+--------------------------------------------------------+---------+-----------+---------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3 | Basesystem_Module_15_SP2_x86_64:SLE-Module-Basesystem15-SP2-Pool                                | SLE-Module-Basesystem15-SP2-Pool                       | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP2/x86_64/product?hX1p7bS7_tuQkHZxM7-dbakOLlixQ7LOIt3mQ3aCnOXYWbiNDMKvhkmVzZqC9Dw5cHyD8Wd-eatvCjg8Vl7h7wo9Muc-1MrQIl2fpTgEiqfFCXQgSlrdpOL_PiJ4W7FSDDO06I-A4qmy5Olb2iqWw1Zi_T36VETv

1 | Basesystem_Module_15_SP2_x86_64:SLE-Module-Basesystem15-SP2-Debuginfo-Pool                      | SLE-Module-Basesystem15-SP2-Debuginfo-Pool             | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP2/x86_64/product_debug?koYWSZIrnbVRtEIAoSFgAXmieWVwj4xoOWoX2Dz61ED_lgMHpJEr136bcfZgrtwC-ydGOZ8C0DYqocGsqfaykHXz8cRwzdKzWj9xfLCntat-7ay9bBlP3btc6SMb4bIByxTH0WmF8bh-y2H17WgUpuyDyqmIYA6glr3JGDz0
 
4 | Basesystem_Module_15_SP2_x86_64:SLE-Module-Basesystem15-SP2-Source-Pool                         | SLE-Module-Basesystem15-SP2-Source-Pool                | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Basesystem/15-SP2/x86_64/product_source?U_OLI1wBZM7IEtxSBkkbMepJ8GUInAm9YUUqBqfJiUSAFZgtzYdIyL9bZda2Wa24JcudnnHg3UzyCSyc-S8ijwrBW_qwKVYOY_P9qXYOqsV_yjb_459Nr8FNRifMquvU11NvrNBLwGtJoo0LKXahO-9Ws4PSVEBNnoihplwQhA

8 | Containers_Module_15_SP2_x86_64:SLE-Module-Containers15-SP2-Pool                                | SLE-Module-Containers15-SP2-Pool                       | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Containers/15-SP2/x86_64/product?9P6DJY5ljwJEMxNps7ZmUV97wsMbvM5heLJDJOUu70SJ3g70zOrvhy8N4D8ftfC3z_noXTvu90EKkZW6HRJ__e_W6fULJeLWz_cL7bDTWf7bVm6S0GjsTZm44bBBRBXxNfl4OK1mBR_Yj7hv8szE-ohCycMfg7cV

6 | Containers_Module_15_SP2_x86_64:SLE-Module-Containers15-SP2-Debuginfo-Pool                      | SLE-Module-Containers15-SP2-Debuginfo-Pool             | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Containers/15-SP2/x86_64/product_debug?f69t-aliqYTkMcqhqdqhIK6747qgBz386uZUSiggYyWVt3xAYmdGPMEkjD4Rq9JMH_6zlK-faRNZIvomPRWnQ6YEmFs8e4Ryi6RuyTdJCv0eR_yVGKkaZ6dlXJdDgGdUj8ncktDOODQgHmUEgnzcLMAAa2Rqdw_GbpZS181U

9 | Containers_Module_15_SP2_x86_64:SLE-Module-Containers15-SP2-Source-Pool                         | SLE-Module-Containers15-SP2-Source-Pool                | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Containers/15-SP2/x86_64/product_source?8LywQWnfxncZUdARjWYG7eflRjIZ-5199bLlSp1p54wKg-wREIg_-FokKnP7_-IvUmMFwwkVgz8uZPOp0qX8o-39dX-jpl-xzwj-Mmr52lX3hRSUkNOR66lqYRstVFtjEgDaaUNYNXyznfOFNpkr4Ks5qtEqN4VbmVSXRg53Xg

13 | Python_2_Module_15_SP2_x86_64:SLE-Module-Python2-15-SP2-Pool                                    | SLE-Module-Python2-15-SP2-Pool                         | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Python2/15-SP2/x86_64/product?SyKpU3T1YXUEhZ_7xZOO9exP6ocg7ORzi2Ha-G1MHp44MGizG47S023XCV4fz32xyR9HuzpLXHe0dh1oqwniQbho07YA9Gw22fANZmT0vfNnA7i4UkXvCErHi_M-HQW7r_aB7_cjgHaiPpgGzkMIkT55jpLj

11 | Python_2_Module_15_SP2_x86_64:SLE-Module-Python2-15-SP2-Debuginfo-Pool                          | SLE-Module-Python2-15-SP2-Debuginfo-Pool               | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Python2/15-SP2/x86_64/product_debug?5Y0ITHEMiQEQUSYcYGoGU5ZBlcTlEGQ7wOrbeEhNQISfG6YbR0iH8m6b5L0zi2Rg3slPOHTdXwcTqm2bH0J2hntl1qUgYwWqMpPYKzu993nSu5DuYtoO-hOmVfvbX5zH7IKV434Px3bCp626GubEyB_TID3r8fAfWZK7

14 | Python_2_Module_15_SP2_x86_64:SLE-Module-Python2-15-SP2-Source-Pool                             | SLE-Module-Python2-15-SP2-Source-Pool                  | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Python2/15-SP2/x86_64/product_source?M_wNUFAiI5AlVjvUpW4kfyocLLg0a9IiUy4VTu9xVSVXmsdNCnnSgepAVUOeY4_gsFdG2dYYuhyEpFNfSX7uSC12kb2nlQyBv1mRfCIaLwGpjbnJghZce5obnfqk2Qbv3qrRJ5Q9h4SF6t0JPKy5_cdi2jwJvqxOpAYkew

28 | Server_Applications_Module_15_SP2_x86_64:SLE-Module-Server-Applications15-SP2-Pool              | SLE-Module-Server-Applications15-SP2-Pool              | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Server-Applications/15-SP2/x86_64/product?KLnkCuU7s5EnNFqvAFo8Y1MqxsvOs4j4Rj28D3eZrJuQkNd7FlcwkaVTe4NrYZ0GzBct3CZWAXn62gfXmk9NW-IBHIpkyNxliIvkONG7jHQHTpKy3rzJJmWOZJ6bVmnADAXOJ5LdqPW1OuYxWRUCRo95DVoG4Duk51p0cH6RmgGV

26 | Server_Applications_Module_15_SP2_x86_64:SLE-Module-Server-Applications15-SP2-Debuginfo-Pool    | SLE-Module-Server-Applications15-SP2-Debuginfo-Pool    | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Server-Applications/15-SP2/x86_64/product_debug?8X6nST9rAAAAAAAAPq6AF8Rn9oN-lH5KUTqvmKlMFksSvaQjIneEo0OzVxSvJBz2wLce-ZjBF-ibKAnRbJfY8zn9-ZBNBqGNzJsKtJoHnQy57GyicVC4NaipFPfXkgnVikj34xVlQhD2AVYpyURPmAWB4D7-CxQ0_4FnsGQvoFgPTcG7b_AY

29 | Server_Applications_Module_15_SP2_x86_64:SLE-Module-Server-Applications15-SP2-Source-Pool       | SLE-Module-Server-Applications15-SP2-Source-Pool       | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Module-Server-Applications/15-SP2/x86_64/product_source?8dBG3rJwJONGiVOke1bHqlewE36Z90iqWtZGrN2RM3zK5RY1vLv6L4I0vDsTXdkYiAtaMg6HDZ65XdPATVDqLp8b_PPaUd1Hlw-bA-i0QozNP5900hg7X4w-spCNHVOrSMU1MWC5mX6UKcSKgBH9Zvoz-SgXvTeUoOZBQhaIjldRIh7MssIqGw

23 | SUSE_Linux_Enterprise_Server_15_SP2_x86_64:SLE-Product-SLES15-SP2-Pool                          | SLE-Product-SLES15-SP2-Pool                            | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SLE-Product-SLES/15-SP2/x86_64/product?1rdLQEXzIC-SfnjdNnuVt5Q3wEjVmIOQohlZh85AIzPC9gNQPI_0s99BIFxnpWh2mUcM9lZqucDZ-ZNV_ov3s8KDavX9cbKP5g7x7NupaD_GuTwYOEPCg3-ea6ciT_B3lsjSnxmTAUWJ6iDSsQCaE3_0ew

21 | SUSE_Linux_Enterprise_Server_15_SP2_x86_64:SLE-Product-SLES15-SP2-Debuginfo-Pool                | SLE-Product-SLES15-SP2-Debuginfo-Pool                  | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Product-SLES/15-SP2/x86_64/product_debug?DEJ_osfdmL1MAfOiclT8H6vBi_h5f6SxGop56CIt0FOGVKm9K9_zM669bDR3Zw7qspO9jmussIXVqy3TAWT2Gr6JpgfFQu0siGiHt1kQD2yzuWBYGakL82unIzZQQBVXRMu1cn9u89LEdnfxKwOP7lueTVTc-z6d2w

24 | SUSE_Linux_Enterprise_Server_15_SP2_x86_64:SLE-Product-SLES15-SP2-Source-Pool                   | SLE-Product-SLES15-SP2-Source-Pool                     | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SLE-Product-SLES/15-SP2/x86_64/product_source?zwmZGg5_IyuT1XaFSkCejncI18HEM1DM2IOwPlKCnQ2rd7QA1nU1vasbIbm73udHL5vZDQOwbi8onM5LA5b_qCa1jwuIeswc_uIYOxm7okgN-PIKydsJ6YsZpb2Q2q2da42E8q2ATburCGEelTtrkPPCf7giplu4VoY

18 | SUSE_CaaS_Platform_4.5_x86_64:SUSE-CAASP-4.5-Pool                                               | SUSE-CAASP-4.5-Pool                                    | Yes     | (  ) No   | No      |   99     | https://updates.suse.com/SUSE/Products/SUSE-CAASP/4.5/x86_64/product?U7uEHmtifptumxyZyeUA-a0_Kg8vhmJBguxWK-J4DXGjzChr-SKadYLXWGhLl9KKev1eziwZ1m3Kbcmyctbd73G47aAsnB2YL-32_ZqZkEnF5yf7JmIoea3C9P33nK1iwrYX4KG7kPez6w

16 | SUSE_CaaS_Platform_4.5_x86_64:SUSE-CAASP-4.5-Debuginfo-Pool                                     | SUSE-CAASP-4.5-Debuginfo-Pool                          | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SUSE-CAASP/4.5/x86_64/product_debug?_29jqZIv-Nl5xc-18-Btge2e9_YR5VOVSvDoMNrJ1WjKr4ab6GhdbjeSghb1jTZsXIgzdF6boZZCt2uh7P95W_3p34-JBKWN3_C5q26e5h27rtmHmciTKMuq7LC96RwaIA1vc4ESachOElZL4jBhgA

19 | SUSE_CaaS_Platform_4.5_x86_64:SUSE-CAASP-4.5-Source-Pool                                        | SUSE-CAASP-4.5-Source-Pool                             | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Products/SUSE-CAASP/4.5/x86_64/product_source?bBnl1QfBQvH3bR011A4xCr1thcs7SHKT4PL8SWRW5PlulXfWza1YIIlbtzNBNzmA9AMBQ8OoMA-c2RfcFO6K97maRnYz5WILXXGPu46-FTFk8WIhQfyhqWGu02UKRVlWh_QY-Ucbt0_lo47M5DSsjkk

5 | Basesystem_Module_15_SP2_x86_64:SLE-Module-Basesystem15-SP2-Updates                             | SLE-Module-Basesystem15-SP2-Updates                    | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Basesystem/15-SP2/x86_64/update?nAN-s5RNUpqMEovUwXaa1ZUyeL7Off_iVNUzRsKkajXL5i7LuB81-R11LPplk9kjXKT-fgfKl7axLA0rSWpuj5OPG_uFsLP-pTUJsHCunbha2QLBBZVEHJpxk_rqibBzxyacADIpHwyZIXpXkd-vSL1jhcDnfw

2 | Basesystem_Module_15_SP2_x86_64:SLE-Module-Basesystem15-SP2-Debuginfo-Updates                   | SLE-Module-Basesystem15-SP2-Debuginfo-Updates          | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Basesystem/15-SP2/x86_64/update_debug?y9AoKsxaCmN2kaUGZi12rs7mApr6a-4QckvfLzUNxFBZWdaVh8DDaUvaaXnJdV6lB8flX_BHz1YsDpDwHQJgjSur8-p_bmdGpmwl2WrgC9f1TSL20ZDylcTej1Y1QCtoIrHHEGS3zn94Qcel6-uzj6isE59gbEF-VxbRWg

10 | Containers_Module_15_SP2_x86_64:SLE-Module-Containers15-SP2-Updates                             | SLE-Module-Containers15-SP2-Updates                    | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Containers/15-SP2/x86_64/update?tjUUwydhnenfLykBjSF6P8PYOpSpiIG3HwiQTSe_WU7HzisPAi5KcqFiwiDNyPYiTMPJ_d8Irq8JLSJs5gxuZuctaVo56_2AFdmfMJfmEG2mLp-M4h-nYL2S9YaPlwFT2VSj5ygveIe20Zd02A5q0J0VFd84Iw
 7 | Containers_Module_15_SP2_x86_64:SLE-Module-Containers15-SP2-Debuginfo-Updates                   | SLE-Module-Containers15-SP2-Debuginfo-Updates          | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Containers/15-SP2/x86_64/update_debug?ltoEXKOcqUskN4N_hPAVOotWYxg2Dc0xvjgoHfhLqxg8mXIT8rV8JMk6XeA6JfdS0OEkuozNvL-WETvE1tOks-dPY40FGOtSWyiO7YRychuMq5KhMmLqCUz7o5UOn59L56qHgoZvjWYhsQV3A-S-1IkynDlAYJFc8HLiwA

15 | Python_2_Module_15_SP2_x86_64:SLE-Module-Python2-15-SP2-Updates                                 | SLE-Module-Python2-15-SP2-Updates                      | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Python2/15-SP2/x86_64/update?-HLGCe4JPgMXnGLHLdq0WFGndccHvZE-gnDbLn-ksYvQrNDg8SsMKXewqa40-j22_XZLSLwnAyGGc9cEeuAp3IULhkA4OQpLiGbgKck3mKOQG9XxaqEEciIEGCFuHgLgoURkr28W613RRWIzfhuv1lplIA

12 | Python_2_Module_15_SP2_x86_64:SLE-Module-Python2-15-SP2-Debuginfo-Updates                       | SLE-Module-Python2-15-SP2-Debuginfo-Updates            | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Python2/15-SP2/x86_64/update_debug?E-V-jDIFd6tZeAn6DmVH1BiUrVjfTWFBbbe48Scyzwggmx07jXODACnhNRBJEa-QulUAK1MzzFZcwTfMI-0gJUmLGd3_P1zv7I-gZ9HW6MzuZeFA_xAqObZ9J-74qCYgvKiv1nhCmcCj8CA45JcXyizdxvtiDBRpjQ

30 | Server_Applications_Module_15_SP2_x86_64:SLE-Module-Server-Applications15-SP2-Updates           | SLE-Module-Server-Applications15-SP2-Updates           | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Server-Applications/15-SP2/x86_64/update?jyRSqiSIsebiRngVbEYwxps4Foc0Bapd1IQ5WeQ9IMb2ENStNL5n1Ks4CWObrTCUW3tgwcdX_L4gNFwNg60W044FApU2naEoExJTvKQNxtSbftAdAWgAknv_Se6kkfyduEdKKtpZYbiRHvUhMp3lQObxMv0O_qz0S8ZvvO-PlA

27 | Server_Applications_Module_15_SP2_x86_64:SLE-Module-Server-Applications15-SP2-Debuginfo-Updates | SLE-Module-Server-Applications15-SP2-Debuginfo-Updates | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SLE-Module-Server-Applications/15-SP2/x86_64/update_debug?qZi-i6YdE-QlC6d_DrIDYdUFbxyetXwv3FfAa-va7juYwyENZWamlx-aZAJ75aH18SKf7qL-3aHCG_uX1YlAEoZOlO6msU0Gn8MgAd1omUXxz4ZbxA1djdLegeUn7D-jCjVO0rbpx6bQqk6bENNAcH7PG13FHmYxlqTWvRZJedAf0lZEDQ

25 | SUSE_Linux_Enterprise_Server_15_SP2_x86_64:SLE-Product-SLES15-SP2-Updates                       | SLE-Product-SLES15-SP2-Updates                         | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SLE-Product-SLES/15-SP2/x86_64/update?RWdp0LX0btK6bo6Md8Bqfvc7GyaTDk9wfAIJmGmMfDdWLz0eZ3bObCa8CG5fyXDbB-Gv8slui8wRxTgkCysTPsQu-bmF1QHDfFfNnyo5BYkKsOrnHyYTknDFqig74aJq64ABuvZHusPn7jjXnNnffaA

22 | SUSE_Linux_Enterprise_Server_15_SP2_x86_64:SLE-Product-SLES15-SP2-Debuginfo-Updates             | SLE-Product-SLES15-SP2-Debuginfo-Updates               | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SLE-Product-SLES/15-SP2/x86_64/update_debug?z8EWTEsqkORKcsP-8sUzTHJxioLBCaGf_rx_T717bK3kxvq0WXKGFBYU6OLUChPqgiX5aT4xmrUzWQxN-hokH7wLUxJdKk3Vew8N6tuuVf-QtlpjoNBd4f6jmAyTEUkChL5cQ7S4RaOWIT-JezT0oGfCVHpbRuA

20 | SUSE_CaaS_Platform_4.5_x86_64:SUSE-CAASP-4.5-Updates                                            | SUSE-CAASP-4.5-Updates                                 | Yes     | (  ) No   | Yes     |   99     | https://updates.suse.com/SUSE/Updates/SUSE-CAASP/4.5/x86_64/update?AAAAAAAAAAAAAAAA-LEMuj9nkfRSEHzHvPhMWQLnBEUeWWQSCmroKIOEt1VZXYjAxTxzS_9MtOM4f6YE0UGa9TKQyjuEWg2Uebrse5mf0dNPTn5smIGDDogkZFfqbaQpFA5ZJdcJp2U

17 | SUSE_CaaS_Platform_4.5_x86_64:SUSE-CAASP-4.5-Debuginfo-Updates                                  | SUSE-CAASP-4.5-Debuginfo-Updates                       | No      | ----      | ----    |   99     | https://updates.suse.com/SUSE/Updates/SUSE-CAASP/4.5/x86_64/update_debug?8hISr90DSbvRIZmfwdgu7riosAdM7KT6Js9koCjb8hHslH6jsEXvgDwDSYOPtU5QgoIc_WofutI4_mO-kRajV-RvYGV-8woQVCrLCuQG9VevKLTKv_P7_zYXCdAq4bqRm0LGTH3qjJb0yUEHGvw`
====

4) Check if `skuba` was indeed upgraded for 4.5:

----
skuba version
----

[IMPORTANT]
====
The version must be >= `skuba-2.1`. `skuba 2` corresponds to {productname} 4.5, while `skuba 1.0-1.4` corresponds to {productname} 4.
====

5) And now run the skuba cluster upgrade commands as it's done below.

- First, check if there are any addons or components to upgrade before you upgrade the nodes:
----
skuba cluster upgrade plan
skuba addon upgrade plan
skuba addon upgrade apply
----

- Then, check with `cluster status` if all nodes have the same kubernetes version (which must be 1.17.x):
----
skuba cluster status
----

[NOTE]
====
If not all nodes are properly upgraded to the same Kubernetes version, then the ones with an older Kubernetes version must be upgraded before migrating according to the previous documentation.
====

- Finally, if all nodes have the same kubernetes version, you first upgrade the cri-o config:
----
skuba cluster upgrade localconfig
----

- Run `skuba node upgrade`:
----
skuba node upgrade apply —-user sles —-sudo —-target <IP of the node you’ve migrated>
----

- Done! Before repeating the same cycle with the rest of the nodes, **please make sure** that all the components of the kubernetes stack **are running** on the freshly upgraded node. You can do this with the following command:
----
kubectl get all -n kube-system
----

6) After upgrading all the nodes, make sure you run another addon upgrade across the cluster:

----
skuba addon upgrade plan
skuba addon upgrade apply
----

After following all these instructions you should be running {productname} 4.5. Take a look at the release notes of this release to further inspect the new features that this release brings. Enjoy!
