= Configure kubelet

[WARNING]
====
Modifying the file `/etc/sysconfig/kubelet` directly is not supported.

The changes made to this file will not persist through an update/upgrade of the software.
Please follow the instructions below to change the configuration for `kubelet` persistently.
====

[NOTE]
====
This procedure does not override the default configuration but amends the changes
from the "drop-in" configuration.

Please refer to: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
====

If you wish to modify the configuration for `kubelet` you must use the "drop-in"
configuration feature of systemd. The steps need to be performed on each cluster
node whose `kubelet` you wish to reconfigure.

. Create an appropriate `.conf` file (e.g. `resource-handling.conf`) in `/usr/lib/systemd/system/kubelet.service.d/` with your desired changes.
.
. Reload the service definitions
+
----
sudo systemctl daemon-reload
----
. Restart kubelet
+
----
sudo systemctl restart kubelet
----
