[[_cha.admin.monitoring]]
= Monitoring
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Monitoring
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images

[[_sec.admin.monitoring.stack]]
== Monitoring Stack On {kube}

.Monitoring Example
[IMPORTANT]
====
This is not an officially supported recommendation and does not claim complete coverage of any use case in a production environment. 

The described monitoring approach in this document is a generalized example of one way of monitoring a {productname}
cluster. 

Please apply best practices to develop your own monitoring approach using the described examples and available health checking endpoints. 
====


This document aims to describe monitoring in a {kube}
environment. 

The monitoring stack consists of a metrics server, a visualization platform, and an ingress controller for authentication. 

*Prometheus Server & Alertmanager*

Prometheus is an open-source monitoring system with a dimensional data model, flexible query language, efficient time series database and modern alerting approach. 

https://prometheus.io/docs/alerting/alertmanager/[Prometheus
   Alertmanager] handles client alerts, sanitizes duplicates and noise and routes them to configuratble receivers. 

*Grafana*

Grafana is an open-source system for querying, analysing and visualizing metrics. 

*NGINX Ingress Controller*

Deploying NGINX Ingress Controller allows us to provide TLS termination to our services and to provide basic authentication to the Prometheus Expression browser/API. 

=== Prerequisites


. Monitoring namespace 
+ 
We will deploy our monitoring stack in its own namespace and therefore create one. 
+

----
{prompt.user}``kubectl create namespace monitoring`` 
----
. Create DNS entries 
+ 
In this example, we will use a worker node with IP `192.168.1.113` to expose our services. 
+ 
You should configure proper DNS names in any production environment.
These values are only for example purposes. 
+

----
monitoring.example.com                      IN  A       192.168.1.113
prometheus.example.com                      IN  CNAME   monitoring.example.com
prometheus-alertmanager.example.com         IN  CNAME   monitoring.example.com
grafana.example.com                         IN  CNAME   monitoring.example.com
----
+
Or add this entry to /etc/hosts 
+

----
192.168.1.113 prometheus.example.com prometheus-alertmanager.example.com grafana.example.com
----
. Create certificates 
+ 
You will need SSL certificates for the shared resources.
If you are deploying in a pre-defined network environment, please get proper certificates from your network administrator.
In this example, the domains are named after the components they represent. ``prometheus.example.com``, `prometheus-alertmanager.example.com` and `grafana.example.com`


[[_nginx_ingress_controller]]
=== NGINX Ingress Controller

.Procedure: Configure And Deploy NGINX Ingress Controller
. Choose which networking configuration the Ingress controller should have. Create a file [path]``nginx-ingress-config-values.yaml`` with one of the following examples as content. 
** **NodePort**: The services will be publicly exposed on each node of the cluster, including master nodes, at port `30080` for `HTTP` and `30443` for ``HTTPS``. 
+

----
# Enable the creation of pod security policy
podSecurityPolicy:
  enabled: true

# Create a specific service account
serviceAccount:
  create: true
  name: nginx-ingress

# Publish services on port HTTP/30080
# Publish services on port HTTPS/30443
# These services are exposed on each node
controller:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
----
** **ClusterIP with external IP(s)**: The services will be exposed on specific nodes of the cluster, at port `80` for `HTTP` and port `443` for ``HTTPS``. 
+

----
# Enable the creation of pod security policy
podSecurityPolicy:
  enabled: true

# Create a specific service account
serviceAccount:
  create: true
  name: nginx-ingress

# Publish services on port HTTP/80
# Publish services on port HTTPS/443
# These services are exposed on the node with IP 192.168.1.113
controller:
  service:
    externalIPs:
      - 192.168.1.113
----
. Deploy the upstream helm chart and pass along our configuration values file. 
+

----
{prompt.user}``helm install --name nginx-ingress stable/nginx-ingress \
--namespace monitoring \
--values nginx-ingress-config-values.yaml`` 
----
+
The result should be two running pods: 
+

----
{prompt.user}``kubectl -n monitoring get po`` NAME                                             READY     STATUS    RESTARTS   AGE
nginx-ingress-controller-74cffccfc-p8xbb         1/1       Running   0          4s
nginx-ingress-default-backend-6b9b546dc8-mfkjk   1/1       Running   0          4s
----


[[_tls]]
=== TLS


You must configure your certificates for the components as secrets in {kube}
.
Get certificates from your local certificate authority.
In this example we are using a single certificate shared by the components ``prometheus.example.com``, `prometheus-alertmanager.example.com` and ``grafana.example.com``. 

.Create Individual Secrets For Components
[NOTE]
====
Should you choose to secure each service with an individual certificate, you must repeat the step below for each component and adjust the name for the individual secret each time. 

In this example the name is ``monitoring-tls``. 
====

.Note Down Secret Names For Configuration
[IMPORTANT]
====
Please note down the names of the secrets you have created.
Later configuration steps require secret names to be specified. 
====

.Procedure: Create TLS secrets in {kube}
. {empty}
+

----
{prompt.user}``kubectl create -n monitoring secret tls monitoring-tls  \
--key  ./monitoring.key \
--cert ./monitoring.crt`` 
----


==== Using Self-signed Certificates (optional)


In some cases you will want to create self-signed certificates for testing of the stack.
This is not recommended.
If you are using proper CA signed certificates, you must skip this entirely. 

.Procedure: Create Self-signed Certificates
. {empty}
+
IMPORTANT: Do not use self-signed certificates in production environments.
There is severe risk of Man-in-the-middle attacks.
Use proper certificates signed by your CA. 
+

. Create a file _openssl.conf_ with the appropriate values 
+

----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
default_md = sha256
default_bits = 4096
prompt=no

[req_distinguished_name]
C = CZ
ST = CZ
L = Prague
O = example
OU = monitoring
CN = example.com
emailAddress = admin@example.com

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = prometheus.example.com
DNS.2 = prometheus-alertmanager.example.com
DNS.3 = grafana.example.com
----
+
This certificate uses Subject Alternative Names so it can be used for Prometheus and Grafana. 
. Generate certificate 
+

----
{prompt.user}``openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
-keyout ./monitoring.key -out ./monitoring.crt \
-config ./openssl.conf -extensions 'v3_req'`` 
----
. Add TLS secret to {kube}
+

----
{prompt.user}``kubectl create -n monitoring secret tls monitoring-tls  \
--key  ./monitoring.key \
--cert ./monitoring.crt`` 
----


[[_prometheus]]
=== Prometheus

.Prometheus Pushgateway
[NOTE]
====
Deploying Prometheus https://prometheus.io/docs/practices/pushing/[Pushgateway] is out of the scope of this document. 
====


. Configure Authentication 
+ 
We need to create a `basic-auth` secret so the NGINX Ingress Controller can perform authentication. 
+ 
Install [command]``htpasswd`` on your local workstation 
+

----
{prompt.sudo}``zypper in apache2-utils`` 
----
+
Create the secret file [path]``auth``
+
IMPORTANT: It is very important that the filename is [path]``auth``
.
During creation, a key in the configuration containing the secret is created that is named after the used filename.
The ingress controller will expect a key named ``auth``. 
+


+

----
htpasswd -c auth admin
New password:
Re-type new password:
Adding password for user admin
----
+
Create secret in {kube}
+

----
{prompt.user}``kubectl create secret generic -n monitoring prometheus-basic-auth --from-file=auth`` 
----
. Create a configuration file [path]``prometheus-config-values.yaml``
+ 
We need to configure the storage for our deployment.
Choose among the options and uncomment the line in the config file.
In production environments you must configure persistent storage. 
** Use an existing `PersistentVolumeClaim`
** Use a `StorageClass` (preferred) 

+

----
# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
    -  prometheus-alertmanager.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus-alertmanager.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 2Gi
    size: 2Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc

## AlertManager is configured through alertmanager.yml. This file and any others
## listed in alertmanagerFiles will be mounted into the alertmanager pod.
## See configuration options https://prometheus.io/docs/alerting/configuration/
#alertmanagerFiles:
#  alertmanager.yml:

# Create a specific service account
serviceAccounts:
  nodeExporter:
    name: prometheus-node-exporter

# Allow scheduling of node-exporter on master nodes
nodeExporter:
  hostNetwork: false
  hostPID: false
  podSecurityPolicy:
    enabled: true
    annotations:
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
      apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
      seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
      apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

# Disable Pushgateway
pushgateway:
  enabled: false

# Prometheus configuration
server:
  ingress:
    enabled: true
    hosts:
    - prometheus.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 8Gi
    size: 8Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc

## Prometheus is configured through prometheus.yml. This file and any others
## listed in serverFiles will be mounted into the server pod.
## See configuration options
## https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#serverFiles:
#  prometheus.yml:
----
. Deploy the upstream helm chart and pass our configuration values file. 
+

----
{prompt.user}``helm install --name prometheus stable/prometheus \
--namespace monitoring \
--values prometheus-config-values.yaml`` 
----
+
There need to be 3 pods running (3 node-exporter pods because we have 3 nodes). 
+

----
{prompt.user}kubectl -n monitoring get po | grep prometheus
NAME                                             READY     STATUS    RESTARTS   AGE
prometheus-alertmanager-5487596d54-kcdd6         2/2       Running   0          2m
prometheus-kube-state-metrics-566669df8c-krblx   1/1       Running   0          2m
prometheus-node-exporter-jnc5w                   1/1       Running   0          2m
prometheus-node-exporter-qfwp9                   1/1       Running   0          2m
prometheus-node-exporter-sc4ls                   1/1       Running   0          2m
prometheus-server-6488f6c4cd-5n9w8               2/2       Running   0          2m
----
. At this stage, the Prometheus Expression browser/API should be accessible, depending on your network configuration at `https://prometheus.example.com` or ``https://prometheus.example.com:30443``. 


[[_alertmanager_configuration]]
=== Alertmanager Configuration Example


The configuration sets one "receiver" to get notified by email when a node meets one of these conditions: 

* Node is unschedulable 
* Node runs out of disk space 
* Node has memory pressure 
* Node has disk pressure 


The first two are critical because the node can not accept new pods, the last two are just warnings. 

The Alertmanager configuration can be added to [path]``prometheus-config-values.yaml``
 by adding the `alertmanagerFiles` section. 

For more information on how to configure Alertmanager, refer to https://prometheus.io/docs/alerting/configuration[Prometheus:
    Alerting - Configuration]. 

.Procedure: Configuring Alertmanager
. Add the `alertmanagerFiles` section to your Prometheus configuration. 
+

----
alertmanagerFiles:
  alertmanager.yml:
    global:
      # The smarthost and SMTP sender used for mail notifications.
      smtp_from: alertmanager@example.com
      smtp_smarthost: smtp.example.com:587
      smtp_auth_username: admin@example.com
      smtp_auth_password: <password>
      smtp_require_tls: true

    route:
      # The labels by which incoming alerts are grouped together.
      group_by: ['node']

      # When a new group of alerts is created by an incoming alert, wait at
      # least 'group_wait' to send the initial notification.
      # This way ensures that you get multiple alerts for the same group that start
      # firing shortly after another are batched together on the first
      # notification.
      group_wait: 30s

      # When the first notification was sent, wait 'group_interval' to send a batch
      # of new alerts that started firing for that group.
      group_interval: 5m

      # If an alert has successfully been sent, wait 'repeat_interval' to
      # resend them.
      repeat_interval: 3h

      # A default receiver
      receiver: admin-example

    receivers:
    - name: 'admin-example'
      email_configs:
      - to: 'admin@example.com'
----
. Replace the empty set of rules `rules: {}` in the `serverFiles` section of the configuration file. 
+ 
For more information on how to configure alerts, refer to: https://prometheus.io/docs/alerting/notification_examples/[Prometheus:
Alerting - Notification Template Examples]
+

----
serverFiles:
  alerts: {}
  rules:
    groups:
    - name: caasp.node.rules
      rules:
      - alert: NodeIsNotReady
        expr: kube_node_status_condition{condition="Ready",status="false"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} is not ready'
      - alert: NodeIsOutOfDisk
        expr: kube_node_status_condition{condition="OutOfDisk",status="true"} == 1
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} has insufficient free disk space'
      - alert: NodeHasDiskPressure
        expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available disk space'
      - alert: NodeHasInsufficientMemory
        expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available memory'
----
. You should now be able to see you AlertManager at https://prometheus-alertmanager.example.com/. 


[[_grafana]]
=== Grafana


Starting from Grafana 5.0, it is possible to dynamically provision the data sources and dashbords via files.
In {kube}
, these files are provided via the utilization of ``ConfigMap``, editing a `ConfigMap` will result by the modification of the configuration without having to delete/recreate the pod. 

.Procedure: Configuring Grafana
. Configure provisoning 
+ 
Create the default datasource configuration file _grafana-datasources.yaml_ which point to our Prometheus server 
+

----
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      access: proxy
      orgId: 1
      isDefault: true
----
. Create the ConfigMap in {kube}
+

----
{prompt.user}``kubectl create -f grafana-datasources.yaml`` 
----
. Configure storage for the deployment 
+ 
Choose among the options and uncomment the line in the config file.
In production environments you must configure persistent storage. 
** Use an existing PersistentVolumeClaim 
** Use a StorageClass (preferred) 
** Create a file _grafana-config-values.yaml_ with the appropriate values 

+

----
# Configure admin password
adminPassword: <password>

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.example.com
  tls:
    - hosts:
      - grafana.example.com
      secretName: monitoring-tls

# Configure persistent storage
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  ## Use a StorageClass
  storageClassName: my-storage-class
  ## Create a PersistentVolumeClaim of 10Gi
  size: 10Gi
  ## Use an existing PersistentVolumeClaim (my-pvc)
  #existingClaim: my-pvc

# Enable sidecar for provisioning
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
----
. Deploy the upstream helm chart and pass our configuration values file 
+

----
{prompt.user}``helm install --name grafana stable/grafana \
--namespace monitoring \
--values grafana-config-values.yaml`` 
----
. The result should be a running Grafana pod 
+

----
{prompt.user}``kubectl -n monitoring get po | grep grafana`` NAME                                             READY     STATUS    RESTARTS   AGE
grafana-dbf7ddb7d-fxg6d                          3/3       Running   0          2m
----
+
At this stage, Grafana should be accessible, depending on your network configuration at `https://grafana.example.com` or `https://grafana.example.com:30443`
. Now you can deploy an existing https://grafana.com/dashboards[Grafana dashboard] or build your own. 


==== Adding Grafana Dashboards


There are two ways to add dashboards to Grafana: 

* Deploy an existing dashboard from https://grafana.com/dashboards[grafana.com]

.. Open the deployed Grafana in your browser and log in. 
.. On the home page of Grafana, hover your mousecursor over the menu:+[] button on the left sidebar and click on the menu:import[] menuitem. 
.. Select an existing dashboard for your purpose from https://grafana.com/dashboards. Copy the URL to the clipboard. 
.. Paste the URL (for example) `https://grafana.com/dashboards/3131` into the first input field to import the "Kubernetes All Nodes" Grafana Dashboard. After pasting in the url, the view will change to another form. 
.. Now select the "Prometheus" datasource in the `prometheus` field and click on the menu:import[] button. 
.. The browser will redirect you to your newly created dashboard. 


* Deploy a configuration file containing the dashboard definition. 

.. Create your dashboard defintion file as a ``ConfigMap``, for example [path]``grafana-dashboards-caasp-cluster.yaml`` . 
+

----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-caasp-cluster
  namespace: monitoring
  labels:
     grafana_dashboard: "1"
data:
  caasp-cluster.json: |-
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
[...]
continues with definition of dashboard JSON
[...]
----
.. Apply the `ConfigMap` to the cluster. 
+

----
{prompt.user}``kubectl apply -f grafana-dashboards-caasp-cluster.yaml`` 
----

+
You can find a couple of dashboard examples for {productname}
in the https://github.com/kubic-project/monitoring[Kubic project] on GitHub.
This repo provides dashboards to visualize {kube}
resources. 


[[_sec.admin.monitoring.health]]
== Health Checking


Although {kube}
takes care of a lot of the traditional deployment problems with its self-healing capabilities, it is considered good practice to monitor the availability and health of your services and applications to react to problems should they go beyond these automated measures. 

A very basic (visual) health check can be achieved by accessing https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#cadvisor[cAdvisor] on the admin node at port ``4194``.
It will show a basic statistics UI about the cluster resources. 

A complete set of instructions on how to monitor and maintain the health of you cluster is, however, beyond the scope of this document. 

There are three levels of health checks. 

* Cluster 
* Node 
* Application / Service 


[[_sec.admin.monitoring.health.cluster]]
=== Cluster Health Checks


The basic check if a cluster is working correctly is based on a few criteria: 

* Are all services running as expected? 
* Is there at least one {kube} master fully working? Even if the deployment is configured to be highly available, it's useful to know if `kube-controller-manager` is down on one of the machines. 


.Understanding cluster health
[NOTE]
====
For further information consider reading https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/[Kubernetes:
     Troubleshoot Clusters]
====

[[_sec.admin.monitoring.health.cluster.kubernetes]]
==== {kube} master


All components in {kube}
expose a `/healthz` endpoint.
The expected (healthy) response is a `200 HTTP` and a response body containing ``ok``. 

The minimal services for the master to work properly are: 

kube-apiserver::
The component that receives your requests from [command]``kubectl`` and from the rest of the {kube}
components. 
+
Endpoint: `https://[replaceable]``MASTER NODE
FQDN``:6444/healthz` (HTTPS) 
+

----
{prompt.user}``curl -i https://localhost:6444/healthz`` ok
----
kube-controller-manager::
The component that contains the control loop, driving current state to the desired state. 
+
Endpoint: `http://[replaceable]``MASTER NODE
FQDN``:10252/healthz` (HTTP) 
+

----
{prompt.user}``curl -i http://localhost:10252/healthz`` ok
----
kube-scheduler::
The component that schedules workloads to nodes. 
+
Endpoint: `http://[replaceable]``MASTER NODE
FQDN``:10251/healthz` (HTTP) 
+

----
{prompt.user}``curl -i http://localhost:10251/healthz`` ok
----

.High-Availability Environments
[NOTE]
====
In a HA environment you can monitor `kube-apiserver` on ``https://[replaceable]``MASTER NODE
      LOADBALANCER``:6443/healthz``. 

If any master node is running correctly you will receive a valid response. 

This does, however, not mean that all master nodes necessarily work correctly.
To ensure that all master nodes work properly, the health checks must be repeated individually for each master node deployed. 

This endpoint will return a successful HTTP response if the cluster is operational; otherwise it will fail.
It will for example check that it can access `etcd` too.
This should not be used to infer that the overall cluster health is ideal.
It will return a a successful response even when only minimal operational cluster health exists. 

To probe for full cluster health, you must perform individual health checking for all machines individually. 
====

[[_sec.admin.monitoring.cluster.health.etcd]]
==== ` etcd` Cluster


Check that all machines that have the `etcd` role on the cluster see the etcd cluster as healthy. 

----
{prompt.user}``docker exec -it $(docker ps -q -f name="salt-master") salt -G 'roles:etcd' \
cmd.run 'set -a; source /etc/sysconfig/etcdctl; etcdctl cluster-health'`` f69e7af2880f42d68dca26ca892cb945:
    member af7ffa9bb1cb7c67 is healthy: got healthy result from https://caasp-master:2379
    member cc40a990d09b4705 is healthy: got healthy result from https://caasp-worker-1:2379
    member fe9b5ee9e1cc3cf7 is healthy: got healthy result from https://caasp-worker-2:2379
    cluster is healthy
ab040b25c2584bc8904971c0acbb250f:
    member af7ffa9bb1cb7c67 is healthy: got healthy result from https://caasp-master:2379
    member cc40a990d09b4705 is healthy: got healthy result from https://caasp-worker-1:2379
    member fe9b5ee9e1cc3cf7 is healthy: got healthy result from https://caasp-worker-2:2379
    cluster is healthy
63008aabc75b471b9a1aa2f64e4d30eb:
    member af7ffa9bb1cb7c67 is healthy: got healthy result from https://caasp-master:2379
    member cc40a990d09b4705 is healthy: got healthy result from https://caasp-worker-1:2379
    member fe9b5ee9e1cc3cf7 is healthy: got healthy result from https://caasp-worker-2:2379
    cluster is healthy
----


More information on etcd cluster health can be found in <<_sec.admin.nodes.graceful_shutdown.etcd>>. 

[[_sec.admin.monitoring.cluster.health.components]]
==== Running Components


Check if the cluster has all required components running: 

----
{prompt.user}``kubectl cluster-info`` {kube}master is running at https://api.infra.caasp.local:6443
Dex is running at https://api.infra.caasp.local:6443/api/v1/namespaces/kube-system/services/dex:dex/proxy
KubeDNS is running at https://api.infra.caasp.local:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Tiller is running at https://api.infra.caasp.local:6443/api/v1/namespaces/kube-system/services/tiller:tiller/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----


You can optionally run [command]``kubectl cluster-info dump`` to obtain a much more detailed output 

[[_sec.admin.monitoring.health.node]]
=== Node Health Checks


The basic check if a node is healthy consists of checking if `kubelet` and the CNI (Container Networking Interface) are working properly. 

[[_sec.admin.monitoring.health.node.kubelet]]
==== `kubelet`


Is the `kubelet` up and working in this node? 

The `kubelet` has a port exposed `10250` on all machines; it's possible to perform an HTTP request to the endpoint to find out if the kubelet is healthy on that machine.
The expected (healthy) response is a `200 HTTP` and a response body containing ``ok``. 

Endpoint: `https://[replaceable]``NODE``:10250/healthz` (HTTPS) 

----
{prompt.user}``curl -i https://localhost:10250/healthz`` ok
----

[[_sec.admin.monitoring.health.node.cni]]
==== ` CNI`


Is CNI (Container Networking Interface) working as expected in this node? If not, `kube-dns` can not start.
Check if the `kube-dns` service is running. 

----
{prompt.user}``kubectl get deployments -n kube-system`` NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
dex             3         3         3            3           7d
kube-dns        3         3         3            3           7d
tiller-deploy   1         1         1            1           7d
----


If kube-dns is running and you are able to create pods then you can be certain that CNI and your CNI plugin are working correctly. 

There's also the https://kubernetes.io/docs/tasks/debug-application-cluster/monitor-node-health/[Monitor
     Node Health] check.
This is a `DaemonSet` that runs on every node, and reports to the `apiserver` back as `NodeCondition` and ``Events``. 

[[_sec.admin.monitoring.health.service]]
=== Service/Application Health Checks


If the deployed services contain a health endpoint, or if they contain an endpoint that can be used to determine if the service is up, you can use `livenessProbes` and/or ``readinessProbes``. 

.Health check endpoints vs. functional endpoints
[NOTE]
====
A proper health check is always preferred if designed correctly. 

Despite the fact that any endpoint could potentially be used to infer if your application is up, a specific health endpoint in your application is preferred.
Such an endpoint will only respond affirmatively when all your setup code on the server has finished and the application is running in a desired state. 
====

`livenessProbes` and `readinessProbes` share configuration options and probe types. 

initialDelaySeconds::
Number of seconds to wait before performing the very first liveness probe. 

periodSeconds::
Number of seconds that the kubelet should wait between liveness probes. 


successThreshold::
Number of minimum consecutive successes for the probe to be considered successful (Default: 1). 

failureThreshold::
Number of times this probe is allowed to fail in order to assume that the service is not responding (Default: 3). 

timeoutSeconds::
Number of seconds after which the probe times out (Default: 1). 


There are different options for the liveness probe to check: 

Command::
A command executed within a container; a retcode of 0 means success. 
+
All other return codes mean failure. 

TCP::
If a TCP connection can be established is considered success. 

HTTP::
Any HTTP response between `200` and `400` indicates success. 


[[_sec.admin.monitoring.health.service.livenessprobe]]
==== livenessProbe

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[livenessProbes] are used to detect running but misbehaving pods/a service that might be running (the process didn't die), but that is not responding as expected. 

Probes are executed by each `kubelet` against the pods that define them and that are running in that specific node. 

When a `livenessProbe` fails, {kube}
 will automatically restart the pod and increase the `RESTARTS` count for that pod. 

These probes will be executed every `periodSeconds` starting from ``initialDelaySeconds``. 

[[_sec.admin.monitoring.health.service.readinessprobe]]
==== readinessProbe

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes[readinessProbes] are used to wait for processes that take some time to start.
Despite the container running, it might be performing some time consuming initializatoin operations.
During this time, you don't want {kube}
 to route traffic to that specific pod; also, you don't want that container to be restarted because it will appear unresponsive. 

These probes will be executed every `periodSeconds` starting from `initialDelaySeconds` until the service is ready. 

They support the same kind of probes as the `livenessProbe`

Both probe types can be used at the same time.
The `livenessProbe` will ensure that if a service is running yet misbehaving, it will be restarted, and `readinessProbe` will ensure that {kube}
 won't route traffic to that specific pod until it's considered to be fully functional and running. 

[[_sec.admin.monitoring.health.general]]
=== General Health Checks


We recommend to apply other best practices from system administration to your monitoring and health checking approach.
These steps are not specific to {productname}
and are beyond the scope of this document.
To simplify performing tasks like disk usage checks, you can use ``salt``.
For more information see: <<_sec.admin.salt>>