= Azure Storage
The Azure cloud provider can be enabled with {productname} to allow {kube} pods to use Azure disks or Azure files as persistent volumes.

This chapter provides the volume usage and description.

Please refer to link:{docurl}single-html/caasp-deployment/#bootstrap[Cluster Bootstrap] on how to setup Azure cloud provider enabled cluster.

== Azure Disk

[[create_azure_disk]]
=== Create Disk
. Install Azure CLI on local machine.
+
For installation instructions, refer to link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[Install the Azure CLI].
. Create Azure disk. The `DISK_NAME` and `DISK_URI` will be used as `diskName` and `diskURI` in Kubernetes manifests for volume binding.
+
----
RESOURCE_GROUP="<RESOURCE_GROUP_NAME>"
DISK_NAME="<VOLUME_NAME>"
VOLUME_TYPE="<VOLUME_TYPE>"
VOLUME_SIZE="<VOLUME_SIZE>"

DISK_URI=`az disk create --resource-group ${RESOURCE_GROUP} --name ${DISK_NAME} --sku ${VOLUME_TYPE} --size-gb ${VOLUME_SIZE} --query id | cut -d'"' -f2`
----
<RESOURCE_GROUP_NAME> The Azure resource group name, for example my-cluster-resource-group.
+
<VOLUME_NAME> The Azure disk name, for example my-disk.
+
<VOLUME_TYPE> The Azure storage SKU. Default value = Premium_LRS. Accepted values are Premium_LRS, StandardSSD_LRS, Standard_LRS, UltraSSD_LRS.
+
<VOLUME_SIZE> The Azure disk size to create in GB, for example 10.


=== In-line Volume

. Create new Azure disk as described in <<create_azure_disk>>. The disk used in pod must exist before the resource is created.

. Create deployement - sample-disk-inline-deployment.yaml.
+
----
kubectl create -f sample-disk-inline-deployment.yaml
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-disk-inline-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          azureDisk:
            kind: Managed
            diskName: // <1>
            diskURI: // <2>
====
+
<1> The disk name, for example my-disk.
<2> The disk resource ID.

. Check pod is running.
+
----
kubectl get pod
...
NAME                                             READY   STATUS    RESTARTS   AGE
sample-disk-inline-deployment-549dc77d76-pwdqw   1/1     Running   0          3m42s
----


=== Persistent Volume
. Create new Azure disk as described in <<create_azure_disk>>. The disk used in pod must exist before the resource is created.
. Create persistent volume.
+
----
kubectl create -f sample-disk-pv.yaml
----
+
====
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: sample-static-pv
  spec:
    capacity:
      storage: 10Gi // <1>
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    azureDisk:
      kind: Managed
      diskName: my-disk // <2>
      diskURI: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group-name/providers/Microsoft.Compute/disks/my-disk // <3>
====
<1> The disk size available.
<2> The disk name.
<3> The disk resource ID.

. Create persistent volume claim.
+
----
kubectl create -f sample-disk-pv-pvc.yaml
----
+
====
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sample-disk-pv-pvc
    labels:
      app: sample
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi // <1>
====
<1> The required volume size.

. Create deployement.
+
----
kubectl create -f sample-disk-pv-deployment.yaml.
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-disk-pv-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data // <1>
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          persistentVolumeClaim:
            claimName: sample-disk-pv-pvc // <2>
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
====
+
<1> The volume mount path in deployed pod.
<2> The requested persistent volume claim name.

. Check persistent volume claim is bonded and pod is running.
+
----
kubectl get pvc
...
NAME                STATUS   VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
sample-disk-pv-pvc   Bound    sample-disk-pv   10Gi        RWO                           55s

kubectl get pod
...
NAME                                        READY   STATUS    RESTARTS   AGE
sample-disk-pv-deployment-549dc77d76-pwdqw   1/1     Running   0          3m42s
----

=== Storage Class
. Create storage class.
+
----
kubectl create -f sample-disk-sc.yaml
----
+
====
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: sample-disk-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: kubernetes.io/azure-disk
  parameters:
    skuName: Standard_LRS // <1>
    location: eastasia // <2>
====
<1> The Azure storage SKU tier. Default is empty.
<2> The Azure storage location. Default is empty.

. Create persistent volume claim - sample-dynamic-pvc.yaml.
+
----
kubectl create -f sample-disk-sc-pvc.yaml.
----
+
====
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sample-disk-sc-pvc
    labels:
      app: sample
  spec:
    storageClassName: sample-disk-sc // <1>
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi // <2>
====
<1> The name of the storage class created.
<2> The required volume size.

. Create deployment.
+
----
kubectl create -f sample-disk-sc-deployment.yaml
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-disk-sc-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data // <1>
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          persistentVolumeClaim:
            claimName: sample-disk-sc-pvc // <2>
====
<1> The volume mount path in deployed pod.
<2> The requested persistent volume claim name.

. Check persistent volume claim is bonded and pod is running.
+
----
kubectl get pvc
...
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
sample-disk-sc-pvc   Bound    pvc-0ca694b5-0084-4e36-bef1-5b2354158d79   10Gi       RWO            sample-disk-sc      70s

kubectl get pod
...
NAME                                         READY   STATUS    RESTARTS   AGE
sample-disk-sc-deployment-687765d5b5-67vnh   1/1     Running   0          20s
----

== Azure File
[IMPORTANT]
====
The `cifs-utils` package must be installed on all cluster nodes to successfully mount the Azure file share.
----
sudo zypper in cifs-utils
----
====

[[create_azure_fileshare_and_secret]]
=== Create File Share and Secret
[[create_azure_fileshare]]
. link:https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal[Create an Azure file share].

. Create Kuberentes file share secret.
+
----
RESOURCE_GROUP="<RESOURCE_GROUP_NAME>"
STORAGE_ACCOUNT="<STORAGE_ACCOUNT_NAME>"
SECRET="<SECRET_NAME>"

# get storage key
STORAGE_KEY=`az storage account keys list --resource-group ${RESOURCE_GROUP} --account-name ${STORAGE_ACCOUNT} --query "[0].value" -o tsv`
echo "Storage account name: "${STORAGE_ACCOUNT}
echo "Storage account key: "${STORAGE_KEY}

# create secret
kubectl create secret generic ${SECRET} --from-literal=azurestorageaccountname=${STORAGE_ACCOUNT} --from-literal=azurestorageaccountkey=${STORAGE_KEY}
----
<RESOURCE_GROUP_NAME> The Azure resource group name. Must be same value as in <<create_azure_fileshare>>.
+
<STORAGE_ACCOUNT_NAME> The Azure storage account name. Must be same value as in <<create_azure_fileshare>>.
+
<SECRET_NAME> The Kuberentes file share secret name, for example azure-file-secret.

=== In-line Volume
. Create new Azure file share and secret as described in <<create_azure_fileshare_and_secret>>. The file share and secret used in pod must exist before the resource is created.

. Create deployement.
+
----
kubectl create -f sample-file-inline-deployment.yaml
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-file-inline-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          azureFile:
            secretName: azure-file-secret // <1>
            shareName: my-cluster-file-share // <2>
            readOnly: false
====
+
<1> The Kubernetes file share secret name.
<2> The Azure file share name.

. Check pod is running.
+
----
kubectl get pod
...
NAME                                             READY   STATUS    RESTARTS   AGE
sample-file-inline-deployment-549dc77d76-pwdqw   1/1     Running   0          3m42s
----

=== Persistent Volume
. Create new Azure file share and secret as described in <<create_azure_fileshare_and_secret>>. The file share and secret used in pod must exist before the resource is created.
. Create persistent volume.
+
----
kubectl create -f sample-file-pv.yaml
----
+
====
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: sample-file-pv
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    azureFile:
        secretName: azure-file-secret // <1>
        shareName: my-cluster-file-share // <2>
        readOnly: false
====
<1> The Kubernetes file share secret name.
<2> The Azure file share name.

. Create persistent volume claim.
+
----
kubectl create -f sample-file-pv-pvc.yaml
----
+
====
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sample-file-pv-pvc
    labels:
      app: sample
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi // <1>
====
<1> The required volume size.

. Create deployement.
+
----
kubectl create -f sample-file-pv-deployment.yaml.
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-file-pv-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data // <1>
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          persistentVolumeClaim:
            claimName: sample-file-pv-pvc // <2>
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
====
+
<1> The volume mount path in deployed pod.
<2> The requested persistent volume claim name.

. Check persistent volume claim is bonded and pod is running.
+
----
kubectl get pvc
...
NAME                STATUS   VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
sample-file-pv-pvc   Bound    sample-file-pv   10Gi        RWO                           55s

kubectl get pod
...
NAME                                        READY   STATUS    RESTARTS   AGE
sample-file-pv-deployment-549dc77d76-pwdqw   1/1     Running   0          3m42s
----

=== Storage Class
. Creat RBAC for Azure file share.
+
----
kubectl create -f sample-file-rbac.yaml
----
+
====
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: system:azure-cloud-provider
  rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs:     ['get','create']
  ---
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: system:azure-cloud-provider
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:azure-cloud-provider
  subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
====
. Create storage class.
+
----
kubectl create -f sample-file-sc.yaml
----
+
====
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: sample-file-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: kubernetes.io/azure-file
  parameters:
    skuName: Standard_LRS // <1>
    location: eastasia // <2>
====
<1> The Azure storage SKU tier. Default is empty.
<2> The Azure storage location. Default is empty.

. Create persistent volume claim.
+
----
kubectl create -f sample-file-sc-pvc.yaml.
----
+
====
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sample-file-sc-pvc
    labels:
      app: sample
  spec:
    storageClassName: sample-file-sc // <1>
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi // <2>
====
<1> The name of the storage class created.
<2> The required volume size.

. Create deployment.
+
----
kubectl create -f sample-file-sc-deployment.yaml
----
+
====
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-deployment
    labels:
      app: sample
      tier: sample
  spec:
    selector:
      matchLabels:
        app: sample
        tier: sample
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: sample
          tier: sample
      spec:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        containers:
        - image: busybox
          name: sample
          volumeMounts:
          - name: sample-volume
            mountPath: /data // <1>
          command: [ "sleep", "infinity" ]
        volumes:
        - name: sample-volume
          persistentVolumeClaim:
            claimName: sample-file-sc-pvc // <2>
====
<1> The volume mount path in deployed pod.
<2> The requested persistent volume claim name.

. Check persistent volume claim is bonded and pod is running.
+
----
kubectl get pvc
...
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
sample-file-sc-pvc   Bound    pvc-0ca694b5-0084-4e36-bef1-5b2354158d79   10Gi       RWO            sample-file-sc      70s

kubectl get pod
...
NAME                                         READY   STATUS    RESTARTS   AGE
sample-file-sc-deployment-687765d5b5-67vnh   1/1     Running   0          20s
----
