= Cluster migration

== Using Backups and Restores

Velero can help you migrate your resources from one cluster to another, as long as you point each Velero instance hosted by the same cloud provider to the same cloud object storage location. If you need help on deployment Velero to your cluster and install CLI to deployment node, please refer to doc link:{docurl}/caasp-deployment/single-html[Disaster Recovery].

> Note that Velero does not support the migration of persistent volumes across cloud providers.

=== Backup Procedure

_(Source Cluster)_ Assuming you haven't already been checkpointing your data with the Velero schedule operation, you need to first back up your entire cluster (replacing <BACKUP-NAME> as desired):

```
velero backup create <BACKUP-NAME>
```

The default TTL is 30 days (720 hours); you can use the --ttl flag to change this as necessary.

_(Destination Cluster)_ Configure BackupStorageLocations and VolumeSnapshotLocations, pointing to the locations used by Source Cluster, using velero backup-location create and velero snapshot-location create. Make sure to configure the BackupStorageLocations as read-only by using the --access-mode=ReadOnly flag for velero backup-location create.

_(Destination Cluster)_ Make sure that the Velero Backup object is created. Velero resources are synchronized with the backup files in cloud storage.

```
velero backup describe <BACKUP-NAME>
```

Note: The default sync interval is 1 minute, so make sure to wait before checking. You can configure this interval with the --backup-sync-period flag to the Velero server.

_(Destination Cluster)_ Once you have confirmed that the right Backup (<BACKUP-NAME>) is now present, you can restore everything with:

```
velero restore create --from-backup <BACKUP-NAME>
```

== Verify both clusters

Check that the second cluster is behaving as expected:

_(Destination Cluster)_ Run:

```
velero restore get
```

Then run:

```
velero restore describe <RESTORE-NAME-FROM-GET-COMMAND>
```

If you encounter issues, make sure that Velero is running in the same namespace in both clusters.