= Horizontal Pod Autoscaler

Horizontal Pod Autoscaler (HPA) is a tool that automatically increases or decreases the number of pods in a replication controller, deployment, replica set or stateful set, based on metrics collected from pods.

In order to leverage HPA, `skuba` now supports an addon `metrics-server`.
The link:https://github.com/kubernetes-sigs/metrics-server[metrics-server] addon is first installed into the {kube} cluster. After that, HPA fetches metrics from the aggregated API `metrics.k8s.io` and according to the user configuration determines whether to increase or decrease the scale of a replication controller, deployment, replica set or stateful set.

The HPA `metrics.target.type` can be one of the following:

- *Utilization*: the value returned from the metrics server API is calculated as the average resource utilization across all relevant pods and subsequently compared with the `metrics.target.averageUtilization`.
- *AverageValue*: the value returned from the metrics server API is divided by the number of all relevant pods, then compared to the `metrics.target.averageValue`.
- *Value*: the value returned from the metrics server API is directly compared to the `metrics.target.value`.

[NOTE]
====
The metrics supported by `metrics-server` are the *CPU* and *memory* of a pod or node.
====

[IMPORTANT]
====
API versions supported by the HPA:

- CPU metric: `autoscaling/v1`,`autoscaling/v2beta2`
- Memory metric: `autoscaling/v2beta2`.
====

== Usage

It is useful to first find out about the available resources of your cluster.

* To display resource (CPU/Memory) usage for nodes, run:
+
[source,bash]
----
$ kubectl top node
----
+
the expected output should look like the following:
+
[source,bash]
----
NAME        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
master000   207m         10%    1756Mi          45%
worker000   100m         10%    602Mi           31%
----

* To display resource (CPU/Memory) usage for pods, run:
+
[source,bash]
----
$ kubectl top pod
----
+
the expected output should look like the following:
+
[source,bash]
----
NAME                                CPU(cores)   MEMORY(bytes)
cilium-9fjw2                        32m          216Mi
cilium-cqnq5                        43m          227Mi
cilium-operator-7d6ddddbf5-2jwgr    1m           46Mi
coredns-69c4947958-2br4b            2m           11Mi
coredns-69c4947958-kb6dq            3m           11Mi
etcd-master000                      21m          584Mi
kube-apiserver-master000            20m          325Mi
kube-controller-manager-master000   6m           105Mi
kube-proxy-x2965                    0m           24Mi
kube-proxy-x9zlv                    0m           19Mi
kube-scheduler-master000            2m           46Mi
kured-45rc2                         1m           25Mi
kured-cptk4                         0m           25Mi
metrics-server-79b8658cd7-gjvhs     1m           21Mi
oidc-dex-55fc689dc-f6cfg            1m           20Mi
oidc-gangway-7b7fbbdbdf-85p6t       1m           18Mi
----
+
[NOTE]
====
The option flag `--sort-by=cpu`/`--sort-by=memory` has an sorting issue at the moment. It will be fixed in the future.
====

=== Using Horizontal Pod Autoscaler (HPA)

You can set the HPA to scale according to various metrics.
These include *average CPU utilization*, *average CPU value*, *average memory utilization* and *average memory value*. The following sections show the recommended configuration for each of the aforementioned options.

==== Creating an HPA Using Average CPU Utilization

The following code is an example of what this type of HPA can look like:

TODO::
  Where does this configuration go? (which config file?)

```
# deployment
kubectl autoscale deployment <deployment-name> \
    --min=<min_replicas_number> \
    --max=<max_replicas_number> \
    --cpu-percent=<percent>

# replication controller
kubectl autoscale replicationcontrollers <replicationcontrollers-name> \
    --min=<min_replicas_number> \
    --max=<max_replicas_number> \
    --cpu-percent=<percent>
```

You could for example use the following values:

```
kubectl autoscale deployment oidc-dex \
    --name=avg-cpu-util \
    --min=1 \
    --max=10 \
    --cpu-percent=50
```
The example output below shows autoscaling for the oidc-dex deployment. The HPA increases the minimum number of pods to 1 and will increase the pods up to 10, if the average CPU utilization of the pods reaches 50%. For more details about the inner workings of the scaling, refer to link:https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details[The Kubernetes documentation on the horizontal pod autoscale algorithm].

To check the current status of the HPA run:
```
kubectl get hpa
```

Example output:
```
NAME       REFERENCE             TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
oidc-dex   Deployment/oidc-dex   0%/50%          1         10        3          115s
```

[NOTE]
====
To calculate pod CPU utilization HPA divides the total CPU usage of all containers by the total number of CPU requests:

POD CPU UTILIZATION = TOTAL CPU USAGE OF ALL CONTAINERS / NUMBER OF CPU REQUESTS

For example:

- Container1 requests 0.5 CPU and uses 0 CPU.
- Container2 requests 1 CPU and uses 2 CPU.

The CPU utilization will be (0+2)/(0.5+1)*100 (%)=133 (%)

If a replication controller, deployment, replica set or stateful set does not specify the CPU request, the output of `kubectl get hpa` TARGETS will be unknown.
====

==== Creating an HPA Using the Average CPU Value

. Create a yaml manifest file `hpa-avg-cpu-value.yaml` with the following content:
+
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: avg-cpu-value // <1>
  namespace: kube-system // <2>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment // <3>
    name: example // <4>
  minReplicas: 1 // <5>
  maxReplicas: 10 // <6>
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 500Mi <7>
```
<1> Name of the HPA.
<2> Namespace of the HPA.
<3> Specifies the kind of object to scale (a replication controller, deployment, replica set or stateful set).
<4> Specifies the name of the object to scale.
<5> Specifies the minimum number of replicas.
<6> Specifies the maximum number of replicas.
<7> The average value of the requested CPU that each pod uses.

. Apply the yaml manifest by running:
+
```
kubectl apply -f hpa-avg-cpu-value.yaml
```

. Check the current status of the HPA:
+
```
kubectl get hpa

NAME            REFERENCE               TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
avg-cpu-value   Deployment/php-apache   1m/500Mi   1         10        1          39s
```

==== Creating an HPA Using Average Memory Utilization

. Create a yaml manifest file `hpa-avg-memory-util.yaml` with the following content:
+
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: avg-memory-util // <1>
  namespace: kube-system // <2>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment // <3>
    name: example // <4>
  minReplicas: 1 // <5>
  maxReplicas: 10 // <6>
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50 <7>
```
<1> Name of the HPA.
<2> Namespace of the HPA.
<3> Specifies the kind of object to scale (a replication controller, deployment, replica set or stateful set).
<4> Specifies the name of the object to scale.
<5> Specifies the minimum number of replicas.
<6> Specifies the maximum number of replicas.
<7> The average utilization of the requested memory that each pod uses.

. Apply the yaml manifest by running:
+
```
kubectl apply -f hpa-avg-memory-util.yaml
```

. Check the current status of the HPA:
+
```
kubectl get hpa

NAME              REFERENCE            TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
avg-memory-util   Deployment/example   5%/50%           1         10        1          4m54s
```
+
[NOTE]
====
HPA calculates pod memory utilization as: total memory usage of all containers / total memory requests.
If a deployment or replication controller does not specify the memory request, the ouput of `kubectl get hpa` TARGETS is <unknown>.
====

==== Creating an HPA Using Average Memory Value

. Create a yaml manifest file `hpa-avg-memory-value.yaml` with the following content:
+
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: avg-memory-value // <1>
  namespace: kube-system // <2>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment // <3>
    name: example // <4>
  minReplicas: 1 // <5>
  maxReplicas: 10 // <6>
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi <7>
```
<1> Name of the HPA.
<2> Namespace of the HPA.
<3> Specifies the kind of object to scale (a replication controller, deployment, replica set or stateful set).
<4> Specifies the name of the object to scale.
<5> Specifies the minimum number of replicas.
<6> Specifies the maximum number of replicas.
<7> The average value of the requested memory that each pod uses.

. Apply the yaml manifest by running:
+
```
kubectl apply -f hpa-avg-memory-value.yaml
```

. Check the current status of the HPA:
+
```
kubectl get hpa

NAME                     REFERENCE            TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
avg-memory-value         Deployment/example   11603968/500Mi   1         10        1          6m24s
```
