= Certificates

During the installation of {productname}, a CA (Certificate Authority) certificate is generated,
which is then used to authenticate and verify all communication. This process also creates
and distributes client and server certificates for the components.

== Communication Security
Communication is secured with TLS v1.2 using the AES 128 CBC cipher.
All certificates are 2048 bit RSA encrypted.

== Certificate Validity
The CA certificate is valid for 3650 days (10 years) by default.
Client and server certificates are valid for 365 days (1 year) by default.

== Certificate Location
Required CAs for {productname} are stored on all master nodes:

[%header,cols=3*]
|===
|Common Name
|Path
|Description

|kubernetes
|/etc/kubernetes/pki/ca.crt,key
|kubernetes general CA

|etcd-ca
|/etc/kubernetes/pki/etcd/ca.crt,key
|Etcd cluster

|kubelet-ca
|/var/lib/kubelet/pki/ca.crt,key
|Kubelet components

|front-proxy-ca
|/etc/kubernetes/pki/front-proxy-ca.crt,key`
|Front-proxy components
|===

The following certificates are managed by `kubeadm`:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Path (`/etc/kubernetes/pki`)
|Kind

|kubernetes
|
|ca.crt,key
|CA

|kube-apiserver
|kubernetes
|apiserver.crt,key
|Server

|kube-apiserver-etcd-client
|kubernetes
|apiserver-etcd-client.crt,key
|Client

|kube-apiserver-kubelet-client
|kubernetes
|apiserver-kubelet-client.crt,key
|Client

|etcd-ca
|
|etcd/ca.crt,key
|CA

|kube-etcd-healthcheck-client
|etcd-ca
|etcd/healthcheck-client.crt,key
|Client

|kube-etcd-peer
|etcd-ca
|etcd/peer.crt,key
|Server,Client

|kube-etcd-server
|etcd-ca
|etcd/server.crt,key
|Server,Client

|front-proxy-ca
|
|front-proxy-ca.crt,key
|CA

|front-proxy-client
|front-proxy-ca
|front-proxy-client.crt,key
|Client
|===

The following certificates are created by `skuba`:

* stored in the {kube} cluster as file format:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Path (`/var/lib/kubelet/pki`)
|Kind

|kubelet-ca
|
|kubelet-ca.crt,key
|CA

|<node-name>
|kubelet-ca
|kubelet.crt,key
|Server
|===

* stored in the {kube} cluster as `Secret` resource:

[%header,cols=4*]
|===
|Common Name
|Parent CA
|Secret Resource Name
|Kind

|oidc-dex
|kubernetes
|oidc-dex-cert
|Server

|oidc-gangway
|kubernetes
|oidc-gangway-cert
|Server

|cilium-etcd-client
|etcd-ca
|cilium-secret
|Client
|===

== Deployment with a Custom CA Certificate

[WARNING]
====
Please plan carefully when deploying with a custom CA certificate. This certificate
can not be reconfigured once deployed and requires a full re-installation of the
cluster to replace.
====

Administrators can provide custom CA certificates (root CAs or intermediate CAs) 
during cluster deployment and decide which CA components to replace (multiple CA certificates) or if to replace all with a single CA certificate.

After you have run `skuba cluster init`, go to the `my-cluster` folder that has been generated,
Create a `pki` folder and put your custom CA certificate into the `pki` folder.

* Replacing the {kube} apiserver CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_APISERVER_ROOTCA_CERT_PATH> my-cluster/pki/ca.crt
cp <CUSTOM_APISERVER_ROOTCA_KEY_PATH> my-cluster/pki/ca.key
chmod 644 my-cluster/pki/ca.crt
chmod 600 my-cluster/pki/ca.key
----

* Replacing the etcd CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki/etcd
cp <CUSTOM_ETCD_ROOTCA_CERT_PATH> my-cluster/pki/etcd/ca.crt
cp <CUSTOM_ETCD_ROOTCA_KEY_PATH> my-cluster/pki/etcd/ca.key
chmod 644 my-cluster/pki/etcd/ca.crt
chmod 600 my-cluster/pki/etcd/ca.key
----

* Replacing the kubelet CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_KUBELET_ROOTCA_CERT_PATH> my-cluster/pki/kubelet-ca.crt
cp <CUSTOM_KUBELET_ROOTCA_KEY_PATH> my-cluster/pki/kubelet-ca.key
chmod 644 my-cluster/pki/kubelet-ca.crt
chmod 600 my-cluster/pki/kubelet-ca.key
----

* Replacing the front-end proxy CA certificate:
+
[source,bash]
----
mkdir -p my-cluster/pki
cp <CUSTOM_FRONTPROXY_ROOTCA_CERT_PATH> my-cluster/pki/front-proxy-ca.crt
cp <CUSTOM_FRONTPROXY_ROOTCA_KEY_PATH> my-cluster/pki/front-proxy-ca.key
chmod 644 my-cluster/pki/front-proxy-ca.crt
chmod 600 my-cluster/pki/front-proxy-ca.key
----

After this process bootstrap the cluster with `skuba node bootstrap`.

=== Extracting Certificate And Key From Combined PEM File

Some PKIs will issue certificates and keys in a combined `.pem` file.
In order to use the contained certificate, you must extract them into separate files using `openssl`.

. Extract the certificate:
+
[source,bash]
----
openssl x509 -in /path/to/file.pem -out /path/to/file.crt
----
. Extract the key:
+
[source,bash]
----
openssl rsa -in /path/to/file.pem -out /path/to/file.key
----


== Automatic Certificate Renewal

{productname} renews all certificates automatically during the control plane
update, see <<handling_updates>>.

[NOTE]
====
It is a best practice to update your {kube} cluster frequently to stay secure.
====

== Manual Certificate Renewal

[IMPORTANT]
====
If you are running multiple master nodes, you need to run the followings
commands sequentially on all master nodes.
====

=== Renewing Certificates Managed by `kubeadm`

. To SSH into the master node, renew all `kubeadm` certificates and reboot,
run the following:
+
[source,bash]
----
ssh <USERNAME>@<MASTER_NODE_IP_ADDRESS/FQDN>
sudo cp -r /etc/kubernetes/pki /etc/kubernetes/pki.bak
sudo kubeadm alpha certs renew all
sudo reboot
----
+
. Copy the renewed `admin.conf` from one of the master nodes to your local environment:
+
[source,bash]
----
ssh <USERNAME>@<MASTER_NODE_IP_ADDRESS/FQDN>
sudo cat /etc/kubernetes/admin.conf
----

=== Renewing Certificates Created by `skuba`:

. Log in to the master node and regenerate the certificates:
+
* Replace the oidc-dex server certificate:
+
Backup the original oidc-dex server certificate and key from Secret resource.
+
[source,bash]
----
sudo mkdir -p /etc/kubernetes/pki.bak
sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf get secret oidc-dex-cert -n kube-system -o yaml | sudo tee /etc/kubernetes/pki.bak/oidc-dex-cert.yaml > /dev/null

cat /etc/kubernetes/pki.bak/oidc-dex-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | sudo tee /etc/kubernetes/pki.bak/oidc-dex.crt > /dev/null
cat /etc/kubernetes/pki.bak/oidc-dex-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | sudo tee /etc/kubernetes/pki.bak/oidc-dex.key > /dev/null
----
+
Sign the oidc-dex server certificate with the CA certificate/key `/etc/kubernetes/pki/ca.crt` and `/etc/kubernetes/pki/ca.key`, make sure that the signed server certificate SAN have to be the same as origin is. To get the origin SAN IP address(es) and DNS(s):
+
[source,bash]
----
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-dex.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-dex.crt | grep -oP '(?<=DNS:)[^,]+'
----
+
Finally, update the {kube} cluster secret data `tls.crt`, and `tls.key` with base64 encoded from signed oidc-dex server certificate and key respectively, and restart oidc-dex pods.
+
[source,bash]
----
cat <SIGNED_OIDC_DEX_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
cat <SIGNED_OIDC_DEX_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo

sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf edit secret oidc-dex-cert -n kube-system
sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf delete pod -lapp=oidc-dex -n kube-system
----

* Replace the oidc-gangway server certificate:
+
Backup the original oidc-gangway server certificate and key from Secret resource.
+
[source,bash]
----
sudo mkdir -p /etc/kubernetes/pki.bak
sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf get secret oidc-gangway-cert -n kube-system -o yaml | sudo tee /etc/kubernetes/pki.bak/oidc-gangway-cert.yaml > /dev/null

cat /etc/kubernetes/pki.bak/oidc-gangway-cert.yaml | grep tls.crt | awk '{print $2}' | base64 --decode | sudo tee /etc/kubernetes/pki.bak/oidc-gangway.crt > /dev/null
cat /etc/kubernetes/pki.bak/oidc-gangway-cert.yaml | grep tls.key | awk '{print $2}' | base64 --decode | sudo tee /etc/kubernetes/pki.bak/oidc-gangway.key > /dev/null
----
+
Sign the oidc-gangway server certificate with the CA certificate/key `/etc/kubernetes/pki/ca.crt` and `/etc/kubernetes/pki/ca.key`, make sure that the signed server certificate SAN have to be the same as origin is. To get the origin SAN IP address(es) and DNS(s):
+
[source,bash]
----
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-gangway.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /etc/kubernetes/pki.bak/oidc-gangway.crt | grep -oP '(?<=DNS:)[^,]+'
----
+
Finally, update the {kube} cluster secret data `tls.crt`, and `tls.key` with base64 encoded from signed oidc-gangway server certificate and key respectively, and restart oidc-gangway pods.
+
[source,bash]
----
cat <SIGNED_OIDC_GANGWAY_SERVER_CERT_PATH> | base64 | awk '{print}' ORS='' && echo
cat <SIGNED_OIDC_GANGWAY_SERVER_KEY_PATH> | base64 | awk '{print}' ORS='' && echo

sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf edit secret oidc-gangway-cert -n kube-system
sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf delete pod -lapp=oidc-gangway -n kube-system
----

* Replace the kubelet server certificate:
+
[IMPORTANT]
====
You need to generate kubelet server certificate for all the nodes on one of control plane nodes, because the kubelet CA certificate key only exists on the control plane nodes. Therefore, after generating re-signed kubelet server certificate/key for worker nodes, you have to copy each kubelet server certificate/key from the control plane node to the corresponding worker node.
====
Backup the original kubelet certificates and keys.
+
[source,bash]
----
sudo cp -r /var/lib/kubelet/pki /var/lib/kubelet/pki.bak
----
+
Sign each node kubelet server certificate with the CA certificate/key `/var/lib/kubelet/pki/kubelet-ca.crt` and `/var/lib/kubelet/pki/kubelet-ca.key`, make sure that the signed server certificate SAN have to be the same as origin is. To get the origin SAN IP address(es) and DNS(s):
+
[source,bash]
----
openssl x509 -noout -text -in /var/lib/kubelet/pki.bak/kubelet.crt | grep -oP '(?<=IP Address:)[^,]+'
openssl x509 -noout -text -in /var/lib/kubelet/pki.bak/kubelet.crt | grep -oP '(?<=DNS:)[^,]+'
----
+
Finally, update the kubelet server certificate and key file `/var/lib/kubelet/kubelet.crt` and `/var/lib/kubelet/kubelet.key` respectively, and restart kubelet service.
+
[source,bash]
----
sudo cp <CUSTOM_KUBELET_SERVER_CERT_PATH> /var/lib/kubelet/pki/kubelet.crt
sudo cp <CUSTOM_KUBELET_SERVER_KEY_PATH> /var/lib/kubelet/pki/kubelet.key
chmod 644 /var/lib/kubelet/pki/kubelet.crt
chmod 600 /var/lib/kubelet/pki/kubelet.key

sudo systemctl restart kubelet
----
