== Configuring HTTP/HTTPS Proxy for {crio}

In some cases you must configure the container runtime to use a proxy to pull
container images.

The {crio} runtime uses the system-wide proxy configuration, defined at `/etc/sysconfig/proxy`.

This file can be edited a number of ways.
It can be pre-configured at build time via AutoYaST, as described in the
https://documentation.suse.com/sles/15-SP1/single-html/SLES-autoyast/#Configuration-Network-Proxy[AutoYaST documentation].
On an existing system, the file can be edited via YaST by running `yast2 proxy`.

If preferred, it can alternatively be edited manually as described in the SUSE https://www.suse.com/support/kb/doc/?id=7006845[Knowledge Base]
article

[NOTE]
====
{crio} and skuba both support four types of comma-separated entries in the `NO_PROXY` variable:

* An exact IP address (`1.2.3.4`)
* CIDR IP range (`1.2.3.4/16`)
* DNS domain name (`eg.com` matches `www.eg.com` and `eg.com`)
* Restricted DNS subdomain (`.eg.com` matches `www.eg.com` but not `eg.com`)

All standard programs should ignore unsupported values in that variable and continue to work (albeit without the configured proxy)
when encountering an unsupported value.
====

[TIP]
Not all programs on all systems will respect CIDR ranges or restricted subdomains.

After you have configured the system proxy for your environment, restart the container runtime with:

[source,bash]
----
systemctl restart crio
----
