
This chapter summarizes frequent problems that can occur while using {productname} and their solutions.

== Overview

This chapter is a collection of frequent problems that are reported for {productname}. Additionally, {suse} support collects problems and their solutions online at link:https://www.suse.com/support/kb/?id=SUSE_CaaS_Platform[] .

In case of problems, a detailed system report can be created with the `supportconfig` command line tool. It will collect information about the system such as: current kernel version, hardware, installed packages, partition setup, and much more. The result is a TAR archive of files. After opening a Service Request (SR), you can upload the TAR archive to Global Technical Support. It will help to locate the issue you reported and to assist you in solving the problem. For details, see link:https://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_adm_support.html[] .

== Collect all relevant logs

To collect all relevant logs run `supportconfig` command on the all master and worker nodes.

[source,bash]
----
supportconfig
tar -xvjf /var/log/nts_*.tbz
cd nts*
cat kubernetes.txt crio.txt 
----

