[#config-crio-container-registry]
== Configuring Container Registries for {crio}

[IMPORTANT]
====
The configuration example in this text uses `VERSION 2` of the {crio} registries
configuration syntax. It is not compatible with the `VERSION 1` syntax present
in some upstream examples.

Please refer to: https://raw.githubusercontent.com/containers/image/master/docs/containers-registries.conf.5.md
====

[TIP]
====
You can create and deploy a custom `registries.conf` during the initial bootstrap of the cluster with skuba.
Create the file `<CLUSTER_NAME>/addons/containers/registries.conf` and apply your changes there.
This file will be rolled out during node bootstrapping.
====

Every registry-related configuration needs to be done in the link:https://github.com/toml-lang/toml[TOML] file
`/etc/containers/registries.conf`. After any change of this file, CRI-O
needs to be restarted.

The configuration is a sequence of `\[[registry]]` entries. For example, a
single registry entry within that configuration could be added like this:

`/etc/containers/registries.conf`
[source,toml]
----
[[registry]]
blocked = false
insecure = false
location = "example.net/bar"
prefix = "example.com/foo/images"
mirror = [
    { location = "example-mirror-0.local", insecure = false },
    { location = "example-mirror-1.local", insecure = true, mirror-by-digest-only = true }
]

[[registry]]
blocked = false
insecure = false
location = "example.net/mymirror"
prefix = "example.com/mirror/images"
mirror = [
    { location = "example-mirror-2.local", insecure = false, mirror-by-digest-only = true },
    { location = "example-mirror-3.local", insecure = true }
]
unqualified-search = false
----

Given an image name, a single `\[[registry]]` TOML table is chosen based on its
`prefix` field.

A prefix is mainly a user-specified image name and can have one of the
following formats:

- `host[:port]`
- `host[:port]/namespace[/namespace…]`
- `host[:port]/namespace[/namespace…]/repo`
- `host[:port]/namespace[/namespace…]/repo[:tag|@digest]`

The user-specified image name must start with the specified `prefix` (and
continue with the appropriate separator) for a particular `\[[registry]]` TOML
table to be considered. Only the TOML entry with the longest match is used.

As a special case, the `prefix` field can be missing. If so, it defaults to the
value of the `location` field.

=== Per-namespace Settings

- `insecure` (`true` or `false`): By default, container runtimes require TLS
  when retrieving images from a registry. If `insecure` is set to `true`,
  unencrypted HTTP as well as TLS connections with untrusted certificates are
  allowed.

- `blocked` (`true` or `false`): If `true`, pulling images with matching names
  is forbidden.

=== Remapping and Mirroring Registries

The user-specified image reference is, primarily, a "logical" image name,
always used for naming the image. By default, the image reference also directly
specifies the registry and repository to use, but the following options can be
used to redirect the underlying accesses to different registry servers or
locations. This can be used to support configurations with no access to the
Internet without having to change Dockerfiles, or to add redundancy.

==== `location`

Accepts the same format as the `prefix` field, and specifies the physical
location of the `prefix`-rooted namespace. By default, this is equal to `prefix`
(in which case `prefix` can be omitted and the `\[[registry]]` TOML table can
just specify `location`).

===== Example

[source,toml]
----
prefix = "example.com/foo"
location = "internal-registry-for-example.net/bar"
----

Requests for the image `example.com/foo/myimage:latest` will actually work with
the `internal-registry-for-example.net/bar/myimage:latest` image.

==== `mirror`

An array of TOML tables specifying (possibly partial) mirrors for the
`prefix`-rooted namespace.

The mirrors are attempted in the specified order. The first one that can be
contacted and contains the image will be used (and if none of the mirrors
contains the image, the primary location specified by the `registry.location`
field, or using the unmodified user-specified reference, is tried last).

Each TOML table in the `mirror` array can contain the following fields, with
the same semantics as if specified in the `\[[registry]]` TOML table directly:

- `location`
- `insecure`

==== `mirror-by-digest-only`

Can be `true` or `false`. If `true`, mirrors will only be used during pulling
if the image reference includes a digest. Referencing an image by digest
ensures that the same one is always used (whereas referencing an image by a tag may
cause different registries to return different images if the tag mapping is out
of sync).

Note that if this is `true`, images referenced by a tag will only use the primary
registry, failing if that registry is not accessible.
