= FlexVolume Configuration

FlexVolume drivers are external (out-of-tree) drivers usually provided by a specific vendor.
They are executable files that are placed in a predefined directory in the cluster on both worker and master nodes.
Pods interact with FlexVolume drivers through the `flexvolume` in-tree plugin.

The vendor driver first has to be installed on each worker and master node in a Kubernetes cluster.
On {productname} {productmajor}, the path to install the drivers is `/usr/lib/kubernetes/kubelet-plugins/volume/exec/`.

If the drivers are deployed with `DaemonSet`, this will require changing
the FlexVolume directory path, which is usually stored as an environment
variable, for example for rook:

[source,bash]
FLEXVOLUME_DIR_PATH=/usr/lib/kubernetes/kubelet-plugins/volume/exec/

//For more information on DaemonSets, refer to cha.user.daemonset

For a general guide to the FlexVolume configuration, see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-storage/flexvolume.md
