== Backup

* Annotate Persistent Volume (_optional_)
+
If the persistent volume in the supported volume `snapshotter` provider, skip this procedure.
+
However, if we deploy the `restic` DaemonSet and want to backup the persistent volume by `restic`, we have to add annotation `backup.velero.io/backup-volumes=<VOLUME_NAME_1>,<VOLUME_NAME_2>,...` to the pods which have mounted the volume manually.
+
For example, we deploy an Elasticsearch cluster and want to backup the Elasticsearch cluster's data. Add the annotation to the Elasticsearch cluster pods:
+
[source,bash]
----
kubectl annotate pod/elasticsearch-master-0 backup.velero.io/backup-volumes=elasticsearch-master
kubectl annotate pod/elasticsearch-master-1 backup.velero.io/backup-volumes=elasticsearch-master
kubectl annotate pod/elasticsearch-master-2 backup.velero.io/backup-volumes=elasticsearch-master
----
+
[NOTE]
Velero currently does not provide a mechanism to detect persistent volume claims that are missing the `restic` backup annotation.
To solve this, there is a community provided controller link:https://github.com/bitsbeats/velero-pvc-watcher[velero-pvc-watcher] which integrates Prometheus to generate alerts for volumes that are not in the backup or backup-exclusion annotation.

* Manual Backup
+
[source,bash]
----
velero backup create <BACKUP_NAME>
----

* Scheduled Backup
+
The schedule template in cron notation, using UTC time. The schedule can also be expressed using `@every <duration>` syntax.
The duration can be specified using a combination of seconds (s), minutes (m), and hours (h), for example: `@every 2h30m`.
+
[source,bash]
----
# Create schedule template
# Create a backup every 6 hours
velero schedule create <SCHEDULE_NAME> --schedule="0 */6 * * *"

# Create a backup every 6 hours with the @every notation
velero schedule create <SCHEDULE_NAME> --schedule="@every 6h"

# Create a daily backup of the web namespace
velero schedule create <SCHEDULE_NAME> --schedule="@every 24h" --include-namespaces web

# Create a weekly backup, each living for 90 days (2160 hours)
velero schedule create <SCHEDULE_NAME> --schedule="@every 168h" --ttl 2160h0m0s
----
+
[options="header"]
|===
| Character Position | Character Period | Acceptable Values
|1 |Minute |`0-59,*`
|2 |Hour |`0-23,*`
|3 |Day of Month |`1-31,*`
|4 |Month |`1-12,*`
|5 |Day of Week |`0-7,*`
|===
+
[NOTE]
When creating multiple backups to different backup locations closely, you might hit the object storage server API rate limit issues. Now, the velero does not have a mechanism on retry backups when the rate limit occurred. Consider shifting the time to create multiple backups.

* Optional Flags

** Granularity
+
Without passing extra flags to `velero backup create`, Velero will backup the whole {kube} cluster.

*** Namespace
+
Pass flag `--include-namespaces` or `--exclude-namespaces` to specify which namespaces to include/exclude when backing up.
+
For example:
+
[source,bash]
----
# Create a backup including the nginx and default namespaces
velero backup create backup-1 --include-namespaces nginx,default

# Create a backup excluding the kube-system and default namespaces
velero backup create backup-1 --exclude-namespaces kube-system,default
----

*** Resources
+
Pass flag `--include-resources` or `--exclude-resources` to specifies which resources to include/exclude when backing up.
+
For example:
+
[source,bash]
----
# Create a backup including storageclass resource only
velero backup create backup-1 --include-resources storageclasses
----
+
[TIP]
Use `kubectl api-resources` to lists all API resources on the server.

*** Label Selector
+
Pass `--selector` to only back up resources matching the label selector.
+
[source,bash]
----
# Create a backup for the elasticsearch cluster only
velero backup create backup-1 --selector app=elasticsearch-master
----

** Location
+
Pass `--storage-location` to specify where to store the backup. 
For example, if we have an HA object storage server called default and secondary respectively.
+
[source,bash]
----
# Create a backup to the default storage server
velero backup create backup2default --storage-location default

# Create a backup to the secondary storage server
velero backup create backup2secondary --storage-location secondary
----

** Garbage Collection
+
Pass `--ttl` to specify how long the backup should be kept. After the specified time the backup will be deleted. 
The default time for a backup before deletion is 720 hours (30 days).

** Exclude Specific Items from Backup
+
You can exclude individual items from being backed up, even if they match the resource/namespace/label selectors defined in the backup spec. To do this, label the item as follows:
+
[source,bash]
----
kubectl label -n <ITEM_NAMESPACE> <RESOURCE>/<NAME> velero.io/exclude-from-backup=true
----

=== Backup Troubleshooting

* List Backups
+
[source,bash]
----
velero backup get
----

* Describe Backups
+
[source,bash]
----
velero backup describe <BACKUP_NAME_1> <BACKUP_NAME_2> <BACKUP_NAME_3>
----

* Retrieve Backup Logs
+
[source,bash]
----
velero backup logs <BACKUP_NAME>
----
