== Migration to {productname} 4.5

1) The OS must be connected to SCC. Otherwise the migration will not work.
In order to reconnect your OS to SCC, you run:

----
SUSEConnect -r <your SCC key> SUSEConnect -p sle-module-containers/15.1/x86_64 -r <your SCC key>
----

2) You also need the new `zypper migration` plugin. This plugin is used to perform the needed tasks in order to migrate the node itself to the latest version of {platform}, such as updating the repositories to the new ones, and calling `zypper dup`. This plugin is provided by the `zypper-migration-plugin` package. Therefore, install the `zypper-migration-plugin` package:

----
zypper -n in zyppper-migration-plugin
----

3) Then, run the newly installed `zypper-migration` plugin (on the management node first, then on the rest of the nodes):

----
zypper migration --non-interactive --auto-agree-with-licenses
----

4) Check if `skuba` was indeed upgraded for 4.5:

----
skuba version
----

[IMPORTANT]
====
The version must be >= `skuba-2.1`. `skuba 2` corresponds to {productname} 4.5, while `skuba 1.0-1.4` corresponds to {productname} 4.
====

5) And now run the skuba cluster upgrade commands as it's done below.

- First, check if there are any addons or components to upgrade before you upgrade the nodes:
----
skuba cluster upgrade plan
skuba addon upgrade plan
skuba addon upgrade apply
----

- Then, check with `cluster status` if all nodes have the same kubernetes version:
----
skuba cluster status
----

[NOTE]
====
If not all nodes are properly upgraded to the same Kubernetes version, then the ones with an older Kubernetes version must be upgraded before migrating according to the previous documentation.
====

- Finally, if all nodes have the same kubernetes version, you first upgrade the cri-o config:
----
skuba cluster upgrade localconfig
----

- Run `skuba node upgrade`:
----
skuba node upgrade apply —-user sles —-sudo —-target <IP of the node you’ve migrated>
----

- Done! Before repeating the same cycle with the rest of the nodes, **please make sure** that all the components of the kubernetes stack **are running** on the freshly upgraded node. You can do this with the following command:
----
kubectl get all -n kube-system
----

6) After upgrading all the nodes, make sure you run another addon upgrade across the cluster:

----
skuba addon upgrade plan
skuba addon upgrade apply
----

After following all these instructions you should be running {productname} 4.5. Take a look at the release notes of this release to further inspect the new features that this release brings. Enjoy!
