= Monitoring Stack

[IMPORTANT]
====
This is not an officially supported recommendation and does not claim complete coverage of any use case in a production environment.

The described monitoring approach in this document is a generalized example of one way of monitoring a {productname} cluster.

Please apply best practices to develop your own monitoring approach using the described examples and available health checking endpoints.
====

== Introduction

This document aims to describe monitoring in a {kube} cluster.

The monitoring stack consists of a metrics server, a visualization platform, and an ingress controller for authentication.

* *Prometheus*
+
Prometheus is an open-source metrics server with a dimensional data model, flexible query language, efficient time series database and modern alerting approach. The time series collection happens via a pull mode over HTTP.
+
The Prometheus consists of multiple components:
+
 ** Prometheus server: scrapes and stores data to time series database
 ** https://prometheus.io/docs/alerting/alertmanager/[Alertmanager] handles client alerts, sanitizes duplicates and noise and routes them to configuratble receivers.
 ** https://prometheus.io/docs/practices/pushing/[Pushgateway] is an intermediate service which allows you to push metrics from jobs which cannot be scraped.
+
[NOTE]
====
Deploying Prometheus https://prometheus.io/docs/practices/pushing/[Pushgateway] is out of the scope of this document.
====
 ** https://prometheus.io/docs/instrumenting/exporters/[Exporters] are libraries which help to exports existing metrics from 3rd-party system as Prometheus metric.

* *Grafana*
+
Grafana is an open-source system for querying, analysing and visualizing metrics.

* *NGINX Ingress Controller*
+
Deploying NGINX Ingress Controller allows us to provide TLS termination to our services and to provide basic authentication to the Prometheus Expression browser/API.

== Prerequisites

. Monitoring namespace
+
We will deploy our monitoring stack in its own namespace and therefore create one.
+

[source,bash]
----
kubectl create namespace monitoring
----
. Create DNS entries
+
In this example, we will use a worker node with IP `10.86.4.158`.
+
You should configure proper DNS names in any production environment.
These values are only for example purposes.
+
----
monitoring.example.com                      IN  A       10.86.4.158
prometheus.example.com                      IN  CNAME   monitoring.example.com
prometheus-alertmanager.example.com         IN  CNAME   monitoring.example.com
grafana.example.com                         IN  CNAME   monitoring.example.com
----
+
Or add this entry to /etc/hosts
+
----
10.86.4.158 prometheus.example.com prometheus-alertmanager.example.com grafana.example.com
----

. Create certificates
+
You will need SSL certificates for the shared resources.
If you are deploying in a predefined network environment, please get proper certificates from your network administrator.
In this example, the domains are named after the components they represent. `prometheus.example.com`, `prometheus-alertmanager.example.com` and `grafana.example.com`

== Installation

[IMPORTANT]
====
Please make sure you have the <<nginx-ingress>> installed and configured.
====

=== TLS

You must configure your certificates for the components as secrets in {kube} cluster. Get certificates from your local certificate authority.
In this example we are using a single certificate shared by the components `prometheus.example.com`, `prometheus-alertmanager.example.com` and `grafana.example.com`.

.Create Individual Secrets For Components
[NOTE]
====
Should you choose to secure each service with an individual certificate, you must repeat the step below for each component and adjust the name for the individual secret each time.

In this example the name is `monitoring-tls`.
====

.Note Down Secret Names For Configuration
[IMPORTANT]
====
Please note down the names of the secrets you have created.
Later configuration steps require secret names to be specified.
====

==== Trusted Certificates

Import trusted certificate to {kube} cluster. In this example, trusted certificate are `monitoring.key` and `monitoring.crt`.

[source,bash]
----
kubectl create -n monitoring secret tls monitoring-tls  \
--key  ./monitoring.key \
--cert ./monitoring.crt
----

==== Self-signed Certificates (optional)

In some cases you want to create self-signed certificates for testing of the stack. This is not recommended. If you are using proper CA signed certificates, you must skip this entirely.

[IMPORTANT]
Do not use self-signed certificates in production environments.
There is severe risk of Man-in-the-middle attacks.
Use proper certificates signed by your CA.

. Create a file _openssl.conf_ with the appropriate values
+
----
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
default_md = sha256
default_bits = 4096
prompt=no

[req_distinguished_name]
C = CZ
ST = CZ
L = Prague
O = example
OU = monitoring
CN = example.com
emailAddress = admin@example.com

[v3_req]
basicConstraints = CA:FALSE
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = prometheus.example.com
DNS.2 = prometheus-alertmanager.example.com
DNS.3 = grafana.example.com
----
+
This certificate uses Subject Alternative Names so it can be used for Prometheus and Grafana.

. Generate certificate
+
[source,bash]
----
openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
-keyout ./monitoring.key -out ./monitoring.crt \
-config ./openssl.conf -extensions 'v3_req'
----

. Add TLS secret to {kube} cluster
+
[source,bash]
----
kubectl create -n monitoring secret tls monitoring-tls  \
--key  ./monitoring.key \
--cert ./monitoring.crt
----

=== Prometheus

. Configure Authentication
+
We need to create a `basic-auth` secret so the NGINX Ingress Controller can perform authentication.
+

Install `htpasswd` on your local workstation
+
[source,bash]
----
zypper in apache2-utils
----
+

Create the secret file [path]`auth`
+
[source,bash]
----
htpasswd -c auth admin
New password:
Re-type new password:
Adding password for user admin
----
IMPORTANT: It is very important that the filename is [path]`auth`.
During creation, a key in the configuration containing the secret is created that is named after the used filename.
The ingress controller will expect a key named `auth`.
+

Create secret in {kube} cluster
+
[source,bash]
----
kubectl create secret generic -n monitoring prometheus-basic-auth --from-file=auth
----

. Create a configuration file [path]`prometheus-config-values.yaml`
+
We need to configure the storage for our deployment.
Choose among the options and uncomment the line in the config file.
In production environments you must configure persistent storage.

** Use an existing `PersistentVolumeClaim`
** Use a `StorageClass` (preferred)

+
----
# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
    -  prometheus-alertmanager.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus-alertmanager.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 2Gi
    size: 2Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc

## Alertmanager is configured through alertmanager.yml. This file and any others
## listed in alertmanagerFiles will be mounted into the alertmanager pod.
## See configuration options https://prometheus.io/docs/alerting/configuration/
#alertmanagerFiles:
#  alertmanager.yml:

# Create a specific service account
serviceAccounts:
  nodeExporter:
    name: prometheus-node-exporter

# Allow scheduling of node-exporter on master nodes
nodeExporter:
  hostNetwork: false
  hostPID: false
  podSecurityPolicy:
    enabled: true
    annotations:
      apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
      apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
      seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

# Disable Pushgateway
pushgateway:
  enabled: false

# Prometheus configuration
server:
  ingress:
    enabled: true
    hosts:
    - prometheus.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 8Gi
    size: 8Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc

## Prometheus is configured through prometheus.yml. This file and any others
## listed in serverFiles will be mounted into the server pod.
## See configuration options
## https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#serverFiles:
#  prometheus.yml:
----

. Deploy the upstream helm chart and pass our configuration values file.
+
[source,bash]
----
helm install --name prometheus stable/prometheus \
--namespace monitoring \
--values prometheus-config-values.yaml
----
+
There need to be 3 pods running (3 node-exporter pods because we have 3 nodes).
+
[source,bash]
----
kubectl -n monitoring get pod | grep prometheus
NAME                                             READY     STATUS    RESTARTS   AGE
prometheus-alertmanager-5487596d54-kcdd6         2/2       Running   0          2m
prometheus-kube-state-metrics-566669df8c-krblx   1/1       Running   0          2m
prometheus-node-exporter-jnc5w                   1/1       Running   0          2m
prometheus-node-exporter-qfwp9                   1/1       Running   0          2m
prometheus-node-exporter-sc4ls                   1/1       Running   0          2m
prometheus-server-6488f6c4cd-5n9w8               2/2       Running   0          2m
----

. At this stage, the Prometheus Expression browser/API should be accessible, depending on your network configuration
* NodePort: https://prometheus.example.com:30443
* External IPs: https://prometheus.example.com

=== Alertmanager Configuration Example

The configuration sets one "receiver" to get notified by email when a node meets one of these conditions:

* Node is unschedulable
* Node runs out of disk space
* Node has memory pressure
* Node has disk pressure

The first two are critical because the node cannot accept new pods, the last two are just warnings.

The Alertmanager configuration can be added to [path]`prometheus-config-values.yaml` by adding the `alertmanagerFiles` section.

For more information on how to configure Alertmanager, refer to https://prometheus.io/docs/alerting/configuration[Prometheus: Alerting - Configuration].

. Configuring Alertmanager
+
Add the `alertmanagerFiles` section to your Prometheus configuration.
+
----
alertmanagerFiles:
  alertmanager.yml:
    global:
      # The smarthost and SMTP sender used for mail notifications.
      smtp_from: alertmanager@example.com
      smtp_smarthost: smtp.example.com:587
      smtp_auth_username: admin@example.com
      smtp_auth_password: <PASSWORD>
      smtp_require_tls: true

    route:
      # The labels by which incoming alerts are grouped together.
      group_by: ['node']

      # When a new group of alerts is created by an incoming alert, wait at
      # least 'group_wait' to send the initial notification.
      # This way ensures that you get multiple alerts for the same group that start
      # firing shortly after another are batched together on the first
      # notification.
      group_wait: 30s

      # When the first notification was sent, wait 'group_interval' to send a batch
      # of new alerts that started firing for that group.
      group_interval: 5m

      # If an alert has successfully been sent, wait 'repeat_interval' to
      # resend them.
      repeat_interval: 3h

      # A default receiver
      receiver: admin-example

    receivers:
    - name: 'admin-example'
      email_configs:
      - to: 'admin@example.com'
----
. Replace the empty set of rules `rules: {}` in the `serverFiles` section of the configuration file.
+
For more information on how to configure alerts, refer to: https://prometheus.io/docs/alerting/notification_examples/[Prometheus:
Alerting - Notification Template Examples]
+
----
serverFiles:
  alerts: {}
  rules:
    groups:
    - name: caasp.node.rules
      rules:
      - alert: NodeIsNotReady
        expr: kube_node_status_condition{condition="Ready",status="false"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} is not ready'
      - alert: NodeIsOutOfDisk
        expr: kube_node_status_condition{condition="OutOfDisk",status="true"} == 1
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} has insufficient free disk space'
      - alert: NodeHasDiskPressure
        expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available disk space'
      - alert: NodeHasInsufficientMemory
        expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available memory'
----
. To apply the changed configuration, run:
+
----
helm upgrade prometheus stable/prometheus --namespace monitoring --values prometheus-config-values.yaml
----
. You should now be able to see your Alertmanager, depending on your network configuration
* NodePort: https://prometheus-alertmanager.example.com:30443
* External IPs: https://prometheus-alertmanager.example.com

=== Grafana

Starting from Grafana 5.0, it is possible to dynamically provision the data sources and dashboards via files.
In {kube} cluster, these files are provided via the utilization of `ConfigMap`, editing a `ConfigMap` will result by the modification of the configuration without having to delete/recreate the pod.

. Configure Grafana provisioning
+
Create the default datasource configuration file _grafana-datasources.yaml_ which point to our Prometheus server
+
----
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      access: proxy
      orgId: 1
      isDefault: true
----

. Create the ConfigMap in {kube} cluster
+
[source,bash]
----
kubectl create -f grafana-datasources.yaml
----

. Configure storage for the deployment
+
Choose among the options and uncomment the line in the config file.
In production environments you must configure persistent storage.

** Use an existing PersistentVolumeClaim
** Use a StorageClass (preferred)

+
Create a file _grafana-config-values.yaml_ with the appropriate values
+
----
# Configure admin password
adminPassword: <PASSWORD>

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.example.com
  tls:
    - hosts:
      - grafana.example.com
      secretName: monitoring-tls

# Configure persistent storage
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  ## Use a StorageClass
  storageClassName: my-storage-class
  ## Create a PersistentVolumeClaim of 10Gi
  size: 10Gi
  ## Use an existing PersistentVolumeClaim (my-pvc)
  #existingClaim: my-pvc

# Enable sidecar for provisioning
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
----

. Deploy the upstream helm chart and pass our configuration values file
+
[source,bash]
----
helm install --name grafana stable/grafana \
--namespace monitoring \
--values grafana-config-values.yaml
----

. The result should be a running Grafana pod
+
[source,bash]
----
kubectl -n monitoring get pod | grep grafana
NAME                                             READY     STATUS    RESTARTS   AGE
grafana-dbf7ddb7d-fxg6d                          3/3       Running   0          2m
----

+
At this stage, Grafana should be accessible, depending on your network configuration

* NodePort: https://grafana.example.com:30443
* External IPs: https://grafana.example.com

. Now you can add Grafana dashboards.

==== Adding Grafana Dashboards

There are three ways to add dashboards to Grafana:

* Deploy an existing dashboard from https://grafana.com/dashboards[Grafana dashboards]
  . Open the deployed Grafana in your browser and log in.
  . On the home page of Grafana, hover your mousecursor over the + button on the left sidebar and click on the import menuitem.
  . Select an existing dashboard for your purpose from Grafana dashboards. Copy the URL to the clipboard.
  . Paste the URL (for example) `https://grafana.com/dashboards/3131` into the first input field to import the "Kubernetes All Nodes" Grafana Dashboard. After pasting in the url, the view will change to another form.
  . Now select the "Prometheus" datasource in the `prometheus` field and click on the import button.
  . The browser will redirect you to your newly created dashboard.

* Use our https://github.com/SUSE/caasp-monitoring[pre-built dashboards] to monitor the {productname} system

+
[source,bash]
----
# monitor SUSE CaaS Platform cluster
kubectl apply -f https://raw.githubusercontent.com/SUSE/caasp-monitoring/master/grafana-dashboards-caasp-cluster.yaml
# monitor etcd
kubectl apply -f https://raw.githubusercontent.com/SUSE/caasp-monitoring/master/grafana-dashboards-caasp-etcd-cluster.yaml
# monitor namespaces
kubectl apply -f https://raw.githubusercontent.com/SUSE/caasp-monitoring/master/grafana-dashboards-caasp-namespaces.yaml
----

* Build your own dashboard
  Deploy your own dashboard by configuration file containing the dashboard definition.

  . Create your dashboard definition file as a `ConfigMap`, for example [path]`grafana-dashboards-caasp-cluster.yaml`.

+
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-caasp-cluster
  namespace: monitoring
  labels:
     grafana_dashboard: "1"
data:
  caasp-cluster.json: |-
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
[...]
continues with definition of dashboard JSON
[...]
----

  . Apply the `ConfigMap` to the cluster.
+
[source,bash]
----
kubectl apply -f grafana-dashboards-caasp-cluster.yaml
----

== Monitoring

=== Prometheus Jobs

The Prometheus upstream helm chart includes the following predefined jobs that will scrapes metrics from these jobs using service discovery.

* prometheus: Get metrics from prometheus server
* kubernetes-apiservers: Get metrics from {kube} apiserver
* kubernetes-nodes: Get metrics from {kube} nodes
* kubernetes-nodes-cadvisor: Get https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#cadvisor[cAdvisor] metrics reported from {kube} cluster
* kubernetes-service-endpoints: Get metrics from Services which have annotation `prometheus.io/scrape=true` in the metadata
* kubernetes-pods: Get metrics from Pods which have annotation `prometheus.io/port=true` in the metadata

If you wanna monitor new pods and services, you don't need to change `prometheus.yaml` but add annotation `prometheus.io/scrape=true`, `prometheus.io/port=<TARGET_PORT>` and `prometheus.io/path=<METRIC_ENDPOINT>` to your pods and services metadata. Prometheus will automatically scraped the target.

=== ETCD Cluster

ETCD server expose metrics on `/metrics` endpoint. Prometheus jobs does not scrapes it by default. Edit `prometheus.yaml` if you wanna monitor etcd cluster. Since etcd cluster run in https, so we need certificate to access the endpoint.

. At one of the master node, create etcd certificate to secret in monitoring namespace
+
[source,bash]
----
cd /etc/kubernetes

kubectl --kubeconfig=admin.conf -n monitoring create secret generic etcd-certs --from-file=/etc/kubernetes/pki/etcd/ca.crt --from-file=/etc/kubernetes/pki/etcd/healthcheck-client.crt --from-file=/etc/kubernetes/pki/etcd/healthcheck-client.key
----

. Edit the configuration file [path]`prometheus-config-values.yaml`, add `extraSecretMounts` part
+
----
# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
    -  prometheus-alertmanager.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus-alertmanager.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 2Gi
    size: 2Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc

## Alertmanager is configured through alertmanager.yml. This file and any others
## listed in alertmanagerFiles will be mounted into the alertmanager pod.
## See configuration options https://prometheus.io/docs/alerting/configuration/
#alertmanagerFiles:
#  alertmanager.yml:

# Create a specific service account
serviceAccounts:
  nodeExporter:
    name: prometheus-node-exporter

# Allow scheduling of node-exporter on master nodes
nodeExporter:
  hostNetwork: false
  hostPID: false
  podSecurityPolicy:
    enabled: true
    annotations:
      apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
      apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
      seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

# Disable Pushgateway
pushgateway:
  enabled: false

# Prometheus configuration
server:
  ingress:
    enabled: true
    hosts:
    - prometheus.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    tls:
      - hosts:
        - prometheus.example.com
        secretName: monitoring-tls
  persistentVolume:
    enabled: true
    ## Use a StorageClass
    storageClass: my-storage-class
    ## Create a PersistentVolumeClaim of 8Gi
    size: 8Gi
    ## Use an existing PersistentVolumeClaim (my-pvc)
    #existingClaim: my-pvc
  ## Additional Prometheus server Secret mounts
  # Defines additional mounts with secrets. Secrets must be manually created in the namespace.
  extraSecretMounts:
  - name: etcd-certs
    mountPath: /etc/secrets
    secretName: etcd-certs
    readOnly: true

## Prometheus is configured through prometheus.yml. This file and any others
## listed in serverFiles will be mounted into the server pod.
## See configuration options
## https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#serverFiles:
#  prometheus.yml:
----
. Upgrade prometheus helm deployment
+
[source,bash]
----
helm upgrade prometheus stable/prometheus \
--namespace monitoring \
--values prometheus-config-values.yaml
----
. First get all etcd cluster private IP address.
+
[source,bash]
----
kubectl get pods -n kube-system -l component=etcd -o wide
NAME           READY   STATUS    RESTARTS   AGE   IP             NODE      NOMINATED NODE   READINESS GATES
etcd-master0   1/1     Running   2          21h   192.168.0.6    master0   <none>           <none>
etcd-master1   1/1     Running   2          21h   192.168.0.20   master1   <none>           <none>
----
. Add new job for etcd, change the target ip address as your environment and change the target numbers if you have different etcd cluster members.
[source,bash]
+
----
kubectl edit -n monitoring configmap prometheus-server
----
+
----
scrape_configs:
  - job_name: etcd
    static_configs:
    - targets: ['192.168.0.6:2379','192.168.0.20:2379']
    scheme: https
    tls_config:
      ca_file: /etc/secrets/ca.crt
      cert_file: /etc/secrets/healthcheck-client.crt
      key_file: /etc/secrets/healthcheck-client.key
----
. Save the new configmap, the prometheus server will auto reload new configmap.
