= Centralized Logging

Centralized Logging is a means of collecting logs from CaaS Platform for centralized management.
It forwards system and Kubernetes cluster logs to a specified external logging service,
for example, Rsyslog server.

Collecting logs in a central location can serve for audit or debug purposes or to analyze and visually present data.

== Types of logs

You can log the following groups of services. See the <<Deployment>>
for more information on how to select and customize the logs.

Kubernetes System Components::
* Kubelet
* Cri-o

Kubernetes Control Plane Components::
* API Server
* Controller Manager
* Scheduler
* Cilium
* Kube-proxy
* all resources in the kube-system namespaces

Kubernetes Namespaces Pods::
* All namespaces in cluster except kube-system

OS Components::
* Kernel
* Audit
* Zypper
* Network (wicked)

Centralized logging is also restricted to the following protocols: UDP, TCP, TCP + TLS, TCP + mTLS.


== Log formats

The two supported syslog message formats are *RFC 5424* and *RFC 3164*.

[NOTE]
====
The Kubernetes cluster metadata is included in the RFC 5424 message.
====

Example RFC 3164
----
2019-05-30T09:11:21.968458+00:00 worker1 k8s.system/crio[12080] level=debug msg="Endpoint successfully created" containerID=caa46f14a68e766b877af01442e58731845bb45d8ce1f856553440a02c958b2f eventUUID=e2405f2a-82ba-11e9-9a06-fa163eebdfd6 subsys=cilium-cni
----

Example RFC 5424
----
<133>1 2019-05-30T08:28:38.784214+00:00 master0 k8s.pod/kube-system/kube-apiserver-master0/kube-apiserver - - [kube_meta namespace_id="1e030def-81db-11e9-a62b-fa163e1876c9" container_name="kube-apiserver" creation_timestamp="2019-05-29T06:29:31Z" host="master0" namespace_name="kube-system" master_url="https://kubernetes.default.svc.cluster.local:443" pod_id="4aaf10f9-81db-11e9-a62b-fa163e1876c9" pod_name="kube-apiserver-master0"] 2019-05-30T08:28:38.783780355+00:00 stderr F I0530 08:28:38.783710       1 log.go:172] http: TLS handshake error from 172.28.0.19:45888: tls: client offered only unsupported versions: [300]
----


== Installing Helm and Tiller

In order to successfully use Centralized Logging, you first need to install `Helm` and `Tiller`.
Helm is used to install the log agents and provide custom logging settings.

- As of {productname} {productversion},
Helm is part of the {productname} package repository, so to use Centralized Logging,
you only need to run the following command from
the location where you normally run `skuba` commands:

[source,bash]
----
sudo zypper install helm
----

- As of {productname} {productversion},
Tiller is not part of the {productname} package repository,
so to install the Tiller container image run:

[source,bash]
----
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

helm init --tiller-image registry.suse.com/caasp/v4/helm-tiller:{helm_tiller_version} --service-account tiller
----

////
Note: When Helm is included in v4, Tiller server will be automatically installed after CaaS Platform setup.
So we probably  just need to mention that we use it and that it's installed automatically.
////

== Deployment

After you have successfully installed it,
use Helm CLI to install log agents on each node,
and provide customized settings via specific command options.

The only three mandatory parameters for a successful deployment of Centralized Logging
are:

* `*server.host*`, default value = rsyslog-server.default.svc.cluster.local
* `*server.port*`, default value = 514
* `*server.protocol*`, default value = TCP

See <<Optional settings>> for the facultative parameters and their default values.

- Running the following will create the minimal working setup:

[source,bash]
----
helm repo add suse-charts https://kubernetes-charts.suse.com
helm install suse-charts/log-agent-rsyslog --name ${RELEASE_NAME} --set server.host=${SERVER_HOST} --set server.port=${SERVER_PORT}
----

[NOTE]
====
If not specified otherwise, Helm will install log agents with TCP as the default value for `server.protocol`.
====


After this step, all of the log agents will initialize then start to forward logs from each node to the configured remote Rsyslog server.

- To check the installation progress, use the `helm status` command:
----
helm status ${RELEASE_NAME}
----

- To uninstall log agents, use the `helm delete` command:
----
helm delete --purge ${RELEASE_NAME}
----


== Queuing

Centralized Logging supports a configurable buffered queue.
This can be used to improve log processing throughput and eliminate possible data loss,
for instance after log agents shutdown, restart or in case of an unresponsive remote server.
The queue files are located under `/var/lib/{RELEASE_NAME}-log-agent-rsyslog` on every node in the cluster.
Queue files remain even after the log agents are deleted.

The buffered queue can be enable/disable with following parameter:

`*queue.enabled*`, default value = false

Setting `queue.enabled` to `false` means that data will be stored in-memory only.
Setting the parameter to `true` will set the data store to a mixture of in-memory and in-disk.
Data will then store in memory until the queue is filled up, after which storing is switched to disk.
Enabling the queue also automatically saves the queue to disk at service shutdown.

Additional parameters to define queue size and its disk usage are:

`*queue.size*`, default value = 50000

This option sets the number of messages allowed for the in-memory queue.
This setting effects the Kubernetes cluster logs (`kubernetes-control-plane` and `kubernetes-user-name-space`).


`*queue.maxDiskSpace*`, default value = 2147483648

This option sets the maximum size allowed for disk storage (in bytes).
The storage is divided so that 20 percent of it is for journal logs and 80 percent for the remaining logs.


== Optional settings

[NOTE]
====
Options with empty default values are set as not specified.
====

|===
|Parameter |Function |Default value

| image.repository |specifies image repository to pull from|registry.suse.com/caasp/v4/rsyslog
|image.tag|specifies image tag to pull|8.39.0
|kubernetesPodAnnotationsEnabled|enables kubernetes meta annotations in pod logs|false
|kubernetesPodLabelsEnabled|enables kubernetes meta labels in pod logs| false
|logs.kubernetesControlPlane.enabled|enables Kubernetes control plane logs|true
|logs.kubernetesSystem.enabled|enables Kubernetes system logs (kubelet, crio)|true
|logs.kubernetesUserNamespaces.enabled|enables Kubernetes user namespaces logs|false
|logs.kubernetesUserNamespaces.exclude|excludes Kubernetes logs for specific namespaces|- ""
|logs.osSystem.enabled|enables OS logs (auditd, kernel, wicked, zypper)|true
|persistStateInterval|sets time interval (seconds) for data state persistency|100
|queue.enabled|enables Rsyslog queue|false
|queue.maxDiskSpace|sets maximum Rsyslog queue disk space in bytes|2147483648
|queue.size|sets Rsyslog queue size in bytes|50000
|resources.limits.cpu|sets CPU limits|
|resources.limits.memory|sets memory limits|512Mi
|resources.requests.cpu|sets CPU for request|100m
|resources.requests.memory|sets memory for request|512Mi
|resumeInterval|specifies time (seconds) after failure before retry is attempted|30
|resumeRetryCount|sets number of retries after first failure before the log is discarded. -1 is unlimited|-1
|server.tls.clientCert|sets TLS client certificate|
|server.tls.clientKey|sets TLS client key|
|server.tls.enabled|enables TLS|false
|server.tls.permittedPeer|sets a list of TLS/fingerprints or TLS/names with permission to access the server|
|server.tls.rootCa|specifies TLS root cetrificate authority|
|===
