= Pod Security Policies

[NOTE]
====
Please note that criteria for designing {psp} are not part of this document.
====

"Pod Security Policy" (stylized as `{psp}` and abbreviated "PSP") is a security
measure implemented by {kube} to control which specifications a pod must meet
to be allowed to run in the cluster. They control various aspects of execution of
pods and interactions with other parts of the software infrastructure.

You can find more general information about {psp} in the link:https://kubernetes.io/docs/concepts/policy/pod-security-policy/[Kubernetes Docs]

User access to the cluster is controlled via "Role Based Access Control (RBAC)".
Each {psp} is associated to one or more users or
service accounts so they are allowed to launch pods with the associated
specifications. The policies are associated to users or  service accounts via
role bindings.

[WARNING]
====
The default policies shipped with {productname} are not suitable for production
environments. Please create your own security policies with the appropriate
amount of permissions/restrictions.
====

== Default Policies

{productname} {productmajor} currently ships with two default policies:

* Privileged (full access everywhere)
* Unprivileged (only very basic access)

All pods running the containers for the basic {productname} software are
deployed into the `kube-system` namespace and run with the "privileged" policy.

All authenticated users and service accounts have a RoleBinding to run
pods using the privileged policy in the `kube-system` namespace.

Any other pods launched in any other namespace are, by default, deployed in
unprivileged mode.

[IMPORTANT]
====
You must configure RBAC rules and {psp} to provide proper functionality
and security.
====

== Policy Definition

The policy definitions are embedded in the link:https://github.com/SUSE/skuba/blob/master/pkg/skuba/actions/cluster/init/manifests.go[cluster bootstrap manifest (GitHub)].

During the bootstrap with `skuba`, the policy files will be stored on your
workstation in the cluster definition folder under `addons/psp`. These policy files
will be installed automatically to all cluster nodes.

The filenames of the files created are:

* `podsecuritypolicy-unprivileged.yaml`
+
and
* `podsecuritypolicy-privileged.yaml`.

=== Policy File Examples

This is the unprivileged policy as a configuration file. You can use this
as a basis to develop your own {psp}.

----
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: suse.caasp.psp.unprivileged
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
spec:
  # Privileged
  privileged: false
  # Volumes and File Systems
  volumes:
    # Kubernetes Pseudo Volume Types
    - configMap
    - secret
    - emptyDir
    - downwardAPI
    - projected
    - persistentVolumeClaim
    # Networked Storage
    - nfs
    - rbd
    - cephFS
    - glusterfs
    - fc
    - iscsi
    # Cloud Volumes
    - cinder
    - gcePersistentDisk
    - awsElasticBlockStore
    - azureDisk
    - azureFile
    - vsphereVolume
  allowedHostPaths:
    # Note: We don't allow hostPath volumes above, but set this to a path we
    # control anyway as a belt+braces protection. /dev/null may be a better
    # option, but the implications of pointing this towards a device are
    # unclear.
    - pathPrefix: /opt/kubernetes-hostpath-volumes
  readOnlyRootFilesystem: false
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # Privilege Escalation
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  # Capabilities
  allowedCapabilities: []
  defaultAddCapabilities: []
  requiredDropCapabilities: []
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: false
  hostPorts:
  - min: 0
    max: 65535
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suse:caasp:psp:unprivileged
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['suse.caasp.psp.unprivileged']
---
# Allow all users and serviceaccounts to use the unprivileged
# PodSecurityPolicy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse:caasp:psp:default
roleRef:
  kind: ClusterRole
  name: suse:caasp:psp:unprivileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
----

== Creating a PodSecurityPolicy

In order to properly secure and run your {kube} workloads you must configure
RBAC rules for your desired users and create {psp} that enable your respective
workloads and then link the user accounts to the {psp} using (Cluster)RoleBinding.

https://kubernetes.io/docs/concepts/policy/pod-security-policy/
