= Available Documentation
:imagesdir: ./images

(((help,SUSE manuals)))


We provide HTML and PDF versions of our books in different languages.
Documentation for our products is available at http://www.suse.com/documentation/, where you can also find the latest updates and browse or download the documentation in various formats.

The following documentation is available for this product:

Deployment Guide::
The {productname}
Deployment Guide gives you details about installation and configuration of {productname}
along with a description of architecture and minimum system requirements.

Quick Start Guide::
The {productname}
Quick Start guides you through the installation of a minimum cluster in the fastest way possible.

Admin Guide::
The {productname}
Admin Guide discusses authorization, updating clusters and individual nodes, monitoring, use of Helm and Tiller, the Kubernetes dashboard, and integration with SUSE Enterprise Storage.


ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]
