= Documentation Conventions
:imagesdir: ./images


The following notices and typographical conventions are used in this documentation: 

* [path]``/etc/passwd`` : directory names and file names 
* [replaceable]``PLACEHOLDER``: replace [replaceable]``PLACEHOLDER`` with the actual value 
* [var]``PATH``: the environment variable PATH 
* [command]``ls``, [option]``--help``: commands, options, and parameters 
* [username]``user`` : users or groups 
* [package]#package name# : name of a package 
* kbd:[Alt] , kbd:[+F1] : a key to press or a key combination; keys are shown in uppercase as on a keyboard 
* menu:File[] , menu:File[Save As] : menu items, buttons 
* This paragraph is only relevant for the {amd64} /{intel64} architecture. The arrows mark the beginning and the end of the text block. 
+ 
This paragraph is only relevant for the architectures `{zseries}` and ``{power}``.
The arrows mark the beginning and the end of the text block. 
* _Dancing Penguins_ (Chapter __Penguins__, {uarr} Another Manual): This is a reference to a chapter in another manual. 
* Commands that must be run with {rootuser} privileges. Often you can also prefix these commands with the [command]``sudo`` command to run them as non-privileged user. 
+

----
{prompt.root}``command`` {prompt.user}``sudo command`` 
----
* Commands that can be run by non-privileged users. 
+

----
{prompt.user}``command`` 
----
* Notices 
+
.Warning Notice
WARNING: Vital information you must be aware of before proceeding.
Warns you about security issues, potential loss of data, damage to hardware, or physical hazards. 
+


+
.Important Notice
IMPORTANT: Important information you should be aware of before proceeding. 
+


+
.Note Notice
NOTE: Additional information, for example about differences in software versions. 
+


+
.Tip Notice
TIP: Helpful information, like a guideline or a piece of practical advice. 
+

