== Network Security

=== Cilium

Cilium is open source software for transparently securing the network
connectivity between application services deployed using Linux container management platforms.
The main characteristic of Cilium is that it uses the extended Berkeley Packet Filter
as a mechanism for filtering incoming and outgoing packets in containers.
The Berkeley Packet Filter (BPF) is a bytecode interpreter inside the Linux kernel
which allows to write programs to analyze and filter network packets and to monitor system function
calls. Cilium translates network/security policies into BPF programs, which are loaded
into the kernel. This means that security policies can be applied and updated without any changes
to the application code or container configuration.

In {productname} {productversion}, Cilium {cilium_version} is deployed automatically with the platform installation.

Please refer to the official Cilium documentation for instructions on how to secure various parts of your infrastructure.

{productname} {productversion} also comes with the ability to perform layer 7 network filtering
powered by envoy. Layer 7 network filtering gives you greater control and security over your
data and services. To use layer 7 network filtering update cilium to the latest package!

The following chapters are specifically recommended for {productname} users.

General introduction to Cilium::
https://cilium.readthedocs.io/en/{cilium_docs_version}/intro/

Securing traffic for HTTP servers and APIs::
https://cilium.readthedocs.io/en/{cilium_docs_version}/gettingstarted/http/

Restricting the network traffic to specific DNS queries or domains::
https://cilium.readthedocs.io/en/{cilium_docs_version}/gettingstarted/dns/

Securing traffic for the Kafka protocol::
https://cilium.readthedocs.io/en/{cilium_docs_version}/gettingstarted/kafka/

Securing applications using gRPC::
https://cilium.readthedocs.io/en/v{cilium_docs_version}/gettingstarted/grpc/

Securing Cassandra databases::
https://cilium.readthedocs.io/en/v{cilium_docs_version}/gettingstarted/cassandra/

Securing Memcached::
https://cilium.readthedocs.io/en/{cilium_docs_version}/gettingstarted/memcached/

Making security policies on clusters on AWS::
https://cilium.readthedocs.io/en/{cilium_docs_version}/gettingstarted/aws/

Kubernetes Network Policies in Cilium::
https://cilium.io/blog/2018/09/19/kubernetes-network-policies/

Layer 7 networking examples::
https://cilium.readthedocs.io/en/{cilium_docs_version}/policy/language/#layer-7-examples

Envoy Extensions in Go::
https://cilium.readthedocs.io/en/{cilium_docs_version}/envoy/extensions/
