= Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Configuration
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images

{productname}
is typically configured in two stages, at first during the installation process and after installation you can configure your cluster by using ``cloud-init``.
The first stage configuration of {productname}
 comes as much preconfigured as possible.
The second stage is typically used for large scales clusters, if you have several machines, `cloud-init` is not necessary. 

Each configuration stage is described in the following sections. 

[[_installation.configuration]]
== Configuration


The defaults for the first stage configuration are the following: 

timezone::
is set to _UTC_ by default, but can be changed by ``cloud-init``. 

keyboard::
is set to _us_ by default, but can be changed during the installation process. 

locale::
is set to _en_US.utf8_ by default, but can be changed by ``cloud-init``. 


[[_cloud_init.configuration]]
== ` cloud-init` Configuration

`cloud-init` is used after the installation is complete.
You then define a set of configuration files that will be applied during the boot phase. 

The `cloud-init` configuration can be loaded from different data sources.
Currently there are preconfigured the following datasources and `cloud-init` searches in them for configuration in the following order: 

. the `LocalDisk` datasource 
. the `NoCloud` datasource 
. the `OpenStack` datasource - if there is a running OpenStack service, this datasource will be used. The configuration then depends on a particular setup and thus it is not covered by this manual. 


More details about the datasources are provided further. 

[[_localdisk.datasource]]
=== The `LocalDisk` Datasource


The `cloud-init` searches for the configuration files: [path]``meta-data``
, [path]``user-data``
 and optionally [path]``vendor-data``
 in the local directory: [path]``/cloud-init-config``
. 

[[_nocloud.datasource]]
=== The `NoCloud` Datasource


The `NoCloud` datasource enables you to read the `cloud-init` configuration without running a network service. `cloud-init` searches for the configuration files [path]``meta-data``
, [path]``user-data``
 in the root directory of a local file system formatted as `vfat` or `iso9660` with a label ``cidata``.
Typically it is an unpartitioned USB stick or disk or a DVD iso. 

Alternatively you can specify a remote location of the [path]``cloud.cfg``
, but you have to configure network first, e.g.
by using local configuration files.
The url is specified during boot time and must be in the format: ``cloud-init-url=http://[replaceable]``hostname.domain``/cloud.cfg``.
The content of the passed url is copied to [path]``/etc/cloud/cloud.cfg.d/91_kernel_cmdline_url.cfg``
 and it is not overwritten even though the url changes. 

[[_cloud.config.file]]
=== The [path]``cloud.cfg`` Configuration File


The [path]``cloud.cfg``
 is used to define a datasource and locations of other required configuration files.
Use the `\#cloud-config` syntax when defining the content. 

An example with `NoCloud` datasource follows: 

----
#cloud-config
    datasource:
     NoCloud:
     # default seedfrom is None
     # if found, then it should contain a url with:
     #    <url>user-data and <url>meta-data
     # seedfrom: http://my.example.com/<path>/
----

[[_meta_data.config.file]]
=== The [path]``meta-data`` Configuration File


The file [path]``meta-data``
 is a YAML formatted file that is intended to configure the system items like network, instance ID, etc.
The file typically contains the `instance-id` and `network-interfaces` options, each is described further. 

`instance-id`::
Defines the instance.
If you perform any changes to the configuration (either [path]``user-data``
or [path]``meta-data``
) you have to update this option with another value.
Thus the `cloud-init` recognizes if this the first boot of the particular instantiated host. 
+

----
instance-id: iid-example001
----
`network-interfaces`::
Here you can define the following options: 
** `auto` to start the network in that configuration automatically during the boot phase. 
** `iface` that defines the configured interfaces. 

+
A static network configuration then could look as follows: 
+

----
network-interfaces: |
  auto eth0
  iface eth0 inet static
  address 192.168.1.10
  network 192.168.1.0
  netmask 255.255.255.0
  broadcast 192.168.1.255
  gateway 192.168.1.1
----

[[_user_data.config.file]]
=== The [path]``user-data`` Configuration File


The configuration file [path]``user-data``
 is a YAML file used to configure users, SSH keys, time zone, etc.
Each part of the file is described in following sections. 

[[_user_data.config.header]]
==== [path]``user-data`` Header


Each [path]``user-data``
 file must start with `\#cloud-config` that indicates the `cloud-config` format.
In the snippet below you enable the debugging output and you disable passwordless authentication for {rootuser}
.
You will have to login with the {rootuser}
 credentials then. 

----
#cloud-config
debug: True
disable_root: False
----

[[_user_data.config.runcmd.statements]]
==== ` runcmd` Statements


In the [path]``user-data``
 you can use the `runcmd` statement to run various commands in your system.
The [path]``user-data``
 file can contain only one `runcmd` statement, thus in case you need to run several commands, group them into one statement: 

----
runcmd:
    - /usr/bin/systemctl enable --now ntpd
----


By using the `runcmd` statement, you can perform the following in your system: 

Configure keyboard layout::
configure the German keyboard layout with __nodeadkeys__: 
+

----
runcmd:
  - /usr/bin/localectl set-keymap de-latin1-nodeadkeys
----
Start services::
for example, start the NTP server as described in <<_user_data.config.ntp.server>>. 


[[_user_data.config.authorized_keys]]
==== SSH Keys Management


You can configure the behaviour of adding SSH keys to the [path]``authorized_keys``
 and the SSH login pattern. 

----
ssh_deletekeys: False
ssh_pwauth: True
ssh_authorized_keys:
  - ssh-rsa XXXKEY mail@example.com
----


The option `ssh_deletekeys` disables/enables automatic deletion of old private and public SSH keys of the host.
The default value is `true`{mdash}
the keys are deleted and new keys are generated.
We do not recommend using the default value, as there could be a problem reported by [command]``ssh`` that the keys are incorrect or has been changed after the `cloud-init` configuration has been changed. 

The option `ssh_pwauth: true` allows you to login by using SSH with a password, if the password is set. 

The option `ssh_authorized_keys` defines whether the SSH key will be added to the [path]``authorized_keys``
 file of the user.
If *not* specified otherwise, the default user is {rootuser}
. 

[[_user_data.config.setting.password]]
==== Setting Password


The [path]``user-data``
 file enables you to set default passwords by using the `chpasswd` option: 

----
chpasswd:
  list: |
    root:linux
  expire: True
----


In the example above you set a _linux_ password for {rootuser}
.
The `expire` option defines whether the user will be prompted to change the default password at the first login. 

[[_user_data.config.adding.custom.repository]]
==== Adding Custom Repository


You can add a custom software repository to your system by using the `zypp_repos` option: 

----
zypper:
  repos:
    - id: opensuse-oss
      name: os-oss
      baseurl: http://my.example.com/repo/SUSE-CAASP-{productnumber}-CUSTOM/
      enabled: 1
      autorefresh: 1
    - id: opensuse-oss-update
      name: os-oss-up
      baseurl: http://my.example.com/repo/SUSE-CAASP-{productnumber}-CUSTOM/update
----


The options available are:

`id`::
The local unique ID of the repository, also known as its alias.
(Mandatory.) 

`name`::
A more descriptive string describing the repository, used in the UI.
(Mandatory.) 

`baseurl`::
URL to the directory where the repository's `repodata` directory lives.
(Mandatory.) 

`type`::
Zypper is able to work with three types of repository: `yast2` and `rpm-md` (yum) repositories, as well as `plaindir` - plain directories containing `$$.$$rpm` files. 

`path`::
This is relative to the ``baseurl``; the default is ``/``. 

`gpgcheck`::
Defines whether the source signatures should be checked using GPG. 

`gpgkey`::
Defines the URL for a GPG key. 

`enabled`::
Defaults to `1` (on). Set to `0` to disable the repository: it will be known and listed, but not used. 

`autorefresh`::
Defaults to `1` (on). When on, the local package cache will be updated to the remote version whenever package management actions are performed. 

`priority`::
Defines a source priority, from `1` (lowest) to `200` (highest). The default is ``99``. 


[[_user_data.config.setting.timezone]]
==== Setting Timezone


You can set a default timezone.
Bear in mind that the configured value must exist in [path]``/usr/share/zoneinfo``
: 

----
timezone: Europe/Berlin
----

[[_user_data.config.keyboard.hostname]]
==== Setting Host name


You can set either a host name or, preferably, a fully-qualified domain name for the machine: 

----
hostname: myhost
----


or 

----
fqdn: myhost.example.com
----


The option `preserve_hostname` specifies whether any existing host name should be retained or not.
Enter `true` or `false` as required: 

----
preserve_hostname: true
----

[[_user_data.config.nameserver]]
==== Configuring Name server


You can configure the server to manage the [path]``resolv.conf``
 file and thus set values of the file: 

----
manage_resolv_conf: true
resolv_conf:
  nameservers: ['8.8.4.4', '8.8.8.8']
  searchdomains:
    - foo.example.com
    - bar.example.com
  domain: example.com
  options:
    rotate: true
    timeout: 1
----

[[_user_data.config.ntp.server]]
==== NTP Server Configuration


You can also configure the NTP server.
The following snippet configures three NTP servers during the first boot and the NTP service is enabled and started: 

----
ntp:
  servers:
    - ntp1.example.com
    - ntp2.example.com
    - ntp3.example.com
runcmd:
  - /usr/bin/systemctl enable --now ntpd
----

[[_user_data.config.salt.minion]]
==== {sminion} Configuration


You can use the file to set the {sminion}
and its communication with the {smaster}
. 

----
salt_minion:
  conf:
    master: saltmaster.example.com

  public_key: |
    -----BEGIN PUBLIC KEY-----
    XXX
    -----END PUBLIC KEY-----

  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    XXX
   -----END RSA PRIVATE KEY-----
----

[[_caasp.roles.assigment]]
==== Assigning Roles to the Cluster Nodes


You need to specify which node of your cluster will be used as the {admin_node}
and which nodes will be used as regular cluster nodes. 

To assign the {admin_node}
role to the cluster node, add the following to the configuration file: 

----
suse_caasp:
  role: admin
----


If the cluster node is assigned the {admin_node}
, all required containers are imported and started.
Bear in mind, that an NTP server must be configured on that machine. 

To other cluster nodes you assign the role ``cluster``.
The machine will register itself as {sminion}
 on the {admin_node}
 and configure a timesync service with {admin_node}
 as a reference.
You do not have to install any NTP server, but if you need to use one, you need to disable the [command]``systemd-timesyncd`` first.
An example of the `cluster` role assignment follows: 

----
suse_caasp:
  role: cluster
  admin_node: admin.example.com
----


where the `admin.example.com` is the host name of the {admin_node}
. 

[[_vendor_data.config.file]]
=== The [path]``vendor-data`` Configuration File


The [path]``vendor-data``
 is an optional configuration file that typically stores data related to the cloud you use.
The data are provided by the entity that launches the cloud instance. 

The format is the same as used for [path]``user-data``
. 