[[_installing.additional.features]]
= Software Installation with {helm}
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Software Installation with Helm
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images


Once your cluster is ready, you may want to deploy additional software that is not installed on {productname}
by default.
This chapter provides instructions on how to install and configure {helm}
, the {kube}
package  manager, and then how to install the {kube}
Dashboard.
If you intend to  deploy {scf}
on {productname}
, {helm}
is required. 

[[_installing.helm]]
== Deploying {helm} and {tiller}

{helm}
has two parts: {helm}
is the client and {tiller}
is the server component. {helm}
runs on your remote workstation that has access to your cluster, and {tiller}
is installed as a container on {productname}
when you run {dashboard}
for the first  time.
(See <<_sec.caasp.installquick.conf>>.) 

You should match the {helm}
version with the version of {tiller}
that is running on your cluster.
The {tiller}
binary cannot report its version, and you need the version that is packaged inside the {tiller}
container.
Run the following command from your workstation to query the logs: 

----
{prompt.user}kubectl logs -l name=tiller --namespace=kube-system | grep "Starting{tiller}"
  [main] 2018/04/04 16:48:27 Starting{tiller}v2.6.1 (tls=false)
----


If the log gets overwritten and loses this information, the following command  queries the [command]``rpm`` package manager inside the container.
This works only on {productname}
/{scf}
 installations: 

----
{prompt.user}kubectl exec -it $(kubectl get pods -n kube-system | awk '/tiller/{print$1}') -n kube-system -- rpm -q helm
  helm-2.6.1-1.6.x86_64
----


If the Linux distribution on your workstation doesn't provide the correct {helm}
version, or you are using some other platform, see the https://docs.helm.sh/using_helm/#quickstart[
         Helm Quickstart Guide] for installation instructions and basic  usage examples.
Download the matching {helm}
 binary into any directory that  is in your PATH on your workstation, such as your [path]``~/bin``
  directory.
Then initialize the client only: 

----
{prompt.user}helm init --client-only
----


The {tiller}
version that ships with {productname}
is supported by {suse}
.
While {suse}
does not provide support for third-party {helm}
charts, you can easily  use them if necessary. 

[[_installing.kube.dashboard]]
== Installing {kube} Dashboard

.Technology Preview
[IMPORTANT]
====
Even though you can install and use the community {kube}
dashboard, {productname}
currently fully supports only {dashboard}
. 
====

.Requirements
* Heapster version 1.3.0 or later needs to be installed on the cluster 
* Helm version 2.7.2+ and kubectl version 1.8.0+ recommended 


.Procedure: Installation of {kube}Dashboard
. {empty}
+

----
helm install --name heapster-default --namespace=kube-system stable/heapster --version=0.2.7 --set rbac.create=true
----
. {empty}
+

----
helm install --namespace=kube-system --name=kubernetes-dashboard stable/kubernetes-dashboard --version=0.6.1
----
. Connect to any cluster node using SSH. 
. Visit `http://127.0.0.1:8081/` in your browser. You will be greeted with by a welcome page containing a dialog to configure authentication. 
. Select menu:token[] authentication. To retrieve your token refer to the value in your kubeconfig file by running the command: 
+

----
grep "id-token" /path/to/kubeconfig  | awk '{print $2}'
----
. On login cluster resources and basic metrics are populated. 


.Procedure: Exposing the Dashboard
. {empty}
+

----
helm upgrade kubernetes-dashboard stable/kubernetes-dashboard --set service.type=NodePort
----
. Now you may visit the dashboard at `https://[replaceable]``WORKER_NODE_ADDRESS``:[replaceable]``NODE_PORT``` in your browser from outside of your cluster. 
