:sectnums!:

[appendix]
[[_app.kvm]]
= Appendix
:imagesdir: ./images



[[_deployment.appendix]]
== Installing an {Admin_Node} using {ay}


To assist with automating the installation of {productname}
clusters as much as possible, it is possible to automatically install the {admin_node}
with {ay}
, similarly to the process used for {worker_node}
s. 

Be aware, though, that this requires considerable customisation of the `autoyast.xml` file. 

Here is a sample file to create an {admin_node}
. 

----

----


Copy the above and paste it into a file named ``autoyast.xml``, then edit it as appropriate for your configuration.
After you have prepared the file, you will need to put it on a Web server that is accessible to the {productname}
 cluster. 

After this, install the admin node by following the same procedure as for a {worker_node}
in <<_sec.deploy.nodes.worker_install.manual.autoyast>>. 

For more information about using and customizing {ay}
, refer to https://www.suse.com/documentation/sles-12/book_autoyast/data/invoking_autoinst.html#commandline_ay. 

For more information about using pre-hashed passwords, refer to  <<_sec.deploy.cloud_init.user_data.password>>. 

:sectnums: