== Deployment on Existing SLES Installation

If you already have a running {sle} {base_os_version} installation, you can add {productname}
to this installation using SUSE Connect. You also need to enable the "Containers"
module because it contains some dependencies required by {productname}.

=== Requirements

.Preparation Required
[NOTE]
You must have completed <<deployment.preparations>> to proceed.

==== Dedicated Cluster Nodes

[IMPORTANT]
====
Adding a machine with an existing use case (e.g. web server) as a cluster node is not supported!
====

{productname} requires dedicated machines as cluster nodes.

The instructions in this document are meant to add {productname} to an existing {sle}
installation that has no other active use case.

For example: You have installed a machine with {sle} but it has not yet been commissioned to run
a specific application and you decide now to make it a {productname} cluster node.


==== Disabling Swap

When using a pre-existing {sle} installation, `swap` will be enabled. You must disable `swap`
for all cluster nodes before performing the cluster bootstrap.

On all nodes that are meant to join the cluster; run:
----
sudo swapoff -a
----

Then modify `/etc/fstab` on each node to remove the `swap` entries.

[IMPORTANT]
====
It is recommended to reboot the machine to finalize these changes and prevent accidental reactivation of
`swap` during an automated reboot of the machine later on.
====

=== Adding {productname} repositories

Retrieve your {productname} registration code and run the following.
Substitute `<CAASP_REGISTRATION_CODE>` for the code from <<registration_code>>.

[source,bash]
----
SUSEConnect -p sle-module-containers/15.1/x86_64

SUSEConnect -p caasp/4.0/x86_64 -r <CAASP_REGISTRATION_CODE>
----

Repeat all preparation steps for any cluster nodes you wish to join.
You can then proceed with <<bootstrap>>.
