include::entities.adoc[]
:isofile: SLE-15-SP1-Installer-DVD-x86_64-Build225.1-Media1.iso
:isolink: https://download.suse.com/Download?buildid=JOZpKbnuAuw~

== Deployment on Bare Metal

=== Environment description

[IMPORTANT]
====
These instructions currently do not describe how to set up a load balancer.
This will be added in future versions. You must provide your own load balancing
solution that directs access to the master nodes.
====

[NOTE]
====
The autoyast file found in skuba is a template. It has the base requirements. 
This autoyast file should act as a guide and should be updated with your companies standards.
====

[NOTE]
====
Hardware specific setup (legacy bios vs EFI, drive partitioning, networking etc) will need to be updated to 
match your hardware. More information on autoyast can be found link:https://doc.opensuse.org/projects/autoyast/[here]
====

=== Autoyast preparation

. Obtain example autoyast file from /usr/share/caasp/autoyast/bare-metal/autoyast.xml
+
----
. Update the autoyast file with your registration keys and company best practices.
. Update the file with your desired username and ssh keys. below we disable root and add a `sles` user with no password.
+
----
  <users config:type="list">
    <user>
      <username>root</username>
      <user_password>!</user_password>
      <encrypted config:type="boolean">true</encrypted>
    </user>
    <user>
      <username>sles</username>
      <user_password>!</user_password>
      <encrypted config:type="boolean">true</encrypted>
      <authorized_keys config:type="list">
        <authorized_key>[ssh public key]</authorized_key>
      </authorized_keys>
    </user>
  </users>
----
+
[NOTE]
====
If your users don't have a password like the above, ensure your user's sudoer's file is updated so that you can use sudo without a password. The example autoyast file has an example. The password for root can be enabled by using the `passwd` command.
====
. Host the autoyast file on a webserver reachable inside the network you will be setting up skuba in
. Add autoyast=https://[webserver/path/to/autoyast.xml] to your sles15 SP1 install

==== {sls} installation

[NOTE]
====
Use AutoYaST and ensure to use a staged frozen patchlevel via RMT/SUSE Manager to ensure 100% reproducible setup. 
link:https://www.suse.com/documentation/sles-15/singlehtml/book_rmt/book_rmt.html#cha.rmt_client[RMT Guide]
====

Once the machines have been installed using the autoyast file, you are now ready to boostrap your cluster
link:deployment-bootstrap.adoc[bootstrap guide]
