include::entities.adoc[]

== Deployment on Bare Metal

=== Environment description

[IMPORTANT]
====
These instructions currently do not describe how to set up a load balancer.
This will be added in future versions. You must provide your own load balancing
solution that directs access to the master nodes.
====

[NOTE]
====
The {ay} file found in `skuba` is a template. It has the base requirements.
This {ay} file should act as a guide and should be updated with your companies standards.
====

[NOTE]
====
To account for hardware/platform specific setup criteria (legacy BIOS vs. (U)EFI, drive partitioning, networking etc.),
you must adjust the {ay} file to your needs according to the requirements.

Refer to the official {ay} documentation for more information: link:https://www.suse.com/documentation/sles-15/singlehtml/book_autoyast/book_autoyast.html[{ay} Guide].
====

=== {ay} preparation

. Obtain example {ay} file from `/usr/share/caasp/autoyast/bare-metal/autoyast.xml`
+
. Update the {ay} file with your registration keys and company best practices and hardware configurations.
+
Refer to the official {ay} documentation for more information: link:https://www.suse.com/documentation/sles-15/singlehtml/book_autoyast/book_autoyast.html[{ay} Guide].
. Update the file with your desired username and ssh keys. Below we disable `root` and add a `sles` user with no password.
+
----
  <users config:type="list">
    <user>
      <username>root</username>
      <user_password>!</user_password>
      <encrypted config:type="boolean">true</encrypted>
    </user>
    <user>
      <username>sles</username>
      <user_password>!</user_password>
      <encrypted config:type="boolean">true</encrypted>
      <authorized_keys config:type="list">
        <authorized_key>[ssh public key]</authorized_key>
      </authorized_keys>
    </user>
  </users>
----
+
[NOTE]
====
If your users don't have a password like the above, ensure your user's `sudoers` file is updated so that you can use sudo without a password.
The default {ay} file provides an example for this scenario.

The password for root can be enabled by using the `passwd` command.
====
. Host the {ay} file on a webserver reachable inside the network your are installing the cluster in.
. Provide `autoyast=https://[webserver/path/to/autoyast.xml]` during the {sle} 15 SP1 installation.

==== {sls} installation

[NOTE]
====
Use AutoYaST and ensure to use a staged frozen patchlevel via RMT/SUSE Manager to ensure 100% reproducible setup.
link:https://www.suse.com/documentation/sles-15/singlehtml/book_rmt/book_rmt.html#cha.rmt_client[RMT Guide]
====

Once the machines have been installed using the {ay} file, you are now ready to boostrap your cluster
link:deployment-bootstrap.adoc[bootstrap guide].
