
== Network Security

=== Cilium

Cilium is open source software for transparently securing the network
connectivity between application services deployed using Linux container management platforms.
The main characteristic of Cilium is that it uses the extended Berkeley Packet Filter
as a mechanism for filtering incoming and outgoing packets in containers.
The Berkeley Packet Filter (BPF) is a bytecode interpreter inside the Linux kernel
which allows to write programs to analyze and filter network packets and to monitor system function
calls. Cilium translates network/security policies into BPF programs, which are loaded
into the kernel. This means that security policies can be applied and updated without any changes
to the application code or container configuration.

In {productname} {productversion}, Cilium is deployed automatically with the Platform installation.
Please refer to the official Cilium documentation for instructions on how to secure various
parts of your infrastructure.
The following chapters are specifically recommended for {productname} users.

General introduction to Cilium::
https://cilium.readthedocs.io/en/v1.5/intro/

Securing traffic for HTTP servers and APIs::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/http/

Restricting the network traffic to specific DNS queries or domains::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/dns/

Securing traffic for the Kafka protocol::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/kafka/

Securing applications using gRPC::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/grpc/

Securing Cassandra databases::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/cassandra/

Securing Memcached::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/memcached/

Making security policies on clusters on AWS::
https://cilium.readthedocs.io/en/v1.5/gettingstarted/aws/

[[cilium-disable-ipv6]]
==== Disable IPv6

. Switch to the cluster file directory (e.g `my-cluster`).

. In the cilium file `./addons/cni/cilium.yaml`, edit the args for the container
with the name `cilium-agent` within the DaemonSet `cilium` to add "--enable-ipv6=false".
This part should look like this (the args are subject to changes):
+
[source,yaml]
----
      containers:
      - image: registry.suse.com/caasp/v4/cilium
        imagePullPolicy: IfNotPresent
        name: cilium-agent
        command: [ "cilium-agent" ]
        args:
          - "--debug=$(CILIUM_DEBUG)"
          - "--disable-envoy-version-check"
          - "-t=vxlan"
          - "--kvstore=etcd"
          - "--kvstore-opt=etcd.config=/var/lib/etcd-config/etcd.config"
          - "--disable-ipv4=$(DISABLE_IPV4)"
          - "--container-runtime=crio"
          - "--enable-ipv6=false"
----

. There is nothing to do if this configuration is modified before the
bootstrap of the cluster as it will be automatically applied.
If the cluster is already bootstrapped, it is required to apply the changes:
+
[source,bash]
----
kubectl apply -f ./addons/cni/cilium.yaml
----
The cilium pods will then be recreated one by one with the new parameters.
