== Terraform Config Examples

[[tf.default]]
=== Terraform Default Configuration
# tag::tf_openstack[]
[source,json]
----
# Name of the image to use
image_name = "SLE-15-SP1-JeOS-GMC"

# Name of the internal network to be created
internal_net = "testing" // <1>

# Name of the external network to be used, the one used to allocate floating IPs
external_net = "floating"

# Identifier to make all your resources unique and avoid clashes with other users of this terraform project
stack_name = "testing" // <2>

# CIDR of the subnet for the internal network
subnet_cidr = "172.28.0.0/24"

# DNS servers for the nodes
"dns_nameservers" = [
    "172.28.0.2",
    "8.8.8.8",
    "8.8.8.4"
]

# Number of master nodes
masters = 1 // <3>

# Number of worker nodes
workers = 2 // <4>

# Size of the master nodes
master_size = "m1.medium"

# Size of the worker nodes
worker_size = "m1.medium"

# Attach persistent volumes to workers
workers_vol_enabled = 0

# Size of the worker volumes in GB
workers_vol_size = 5

# Name of DNS domain
dnsdomain = "testing.example.com"

# Set DNS Entry (0 is false, 1 is true)
dnsentry = 0

# Username for the cluster nodes. Must exist on base OS.
username = "sles" // <5>

# Password for the cluster nodes
password = "linux" // <6>

# Optional: Define the repositories to use
# repositories = [
#     { repository1 = "http://repo.example.com/repository1/" },
#     { repository2 = "http://repo.example.com/repository2/" }
# ]
repositories = [] // <7>

# Define required packages to be installed/removed. Do not change those.
packages = [  // <8>
  "kernel-default",
  "-kernel-default-base",
  "patterns-caasp-Node"
]

# ssh keys to inject into all the nodes
authorized_keys = [ // <9>
  ""
]

# IMPORTANT: Replace these ntp servers with ones from your infrastructure
ntp_servers = ["0.novell.pool.ntp.org", "1.novell.pool.ntp.org", "2.novell.pool.ntp.org", "3.novell.pool.ntp.org"] // <10>
----
<1> `internal_net` the internal network name that will be created/used for the cluster in {soc}.
<2> `stack_name`: Prefix for all machines of the cluster spawned by terraform.
*Note*: This string will be used to generate the human readable IDs in {soc}.
If you use a generic term it is very likely to fail deployment because the term is already in use by someone else. It's a good idea to use your username or other unique identifier.
<3> `masters`: Number of master nodes to be deployed.
<4> `workers`: Number of worker nodes to be deployed.
<5> `username`: Login username for the nodes.
*Note*: Leave this the default `sles`. The username must exist on the used base operating system. It will not be created.
<6> `password`: Login password for the defined username.
<7> `repositories`: A list of additional repositories to be added on each
machines - leave empty if no additional packages need to be installed.
<8> `packages`: Additional packages to be installed on the node.
*Note*: Do not remove any of the pre-filled values in the `packages` section. This can render
your cluster unusable. You can add more packages but do not remove any of the
default packages listed.
<9> `authorized_keys`: List of ssh-public-keys that will be able to login to the
deployed machines.
<10> `ntp_servers`: A list of `ntp` servers you would like to use with `chrony`.
# end::tf_openstack[]

[[tf.vmware]]
=== Terraform VMWare Configuration
# tag::tf_vmware[]
[source,json]
----
# datastore to use on the vSphere server
# EXAMPLE:
# vsphere_datastore = "STORAGE-0"
vsphere_datastore = "3PAR" // <1>

# datacenter to use on the vSphere server
# EXAMPLE:
# vsphere_datacenter = "DATACENTER"
vsphere_datacenter = "MYDATACENTER" // <2>

# network to use on the vSphere server
# EXAMPLE:
# vsphere_network = "VM Network"
vsphere_network = "VM Network" // <3>

# resource pool the machines will be running in
# EXAMPLE:
# vsphere_resource_pool = "My_RP"
vsphere_resource_pool = "My_RP" // <4>

# template name the machines will be copied from
# EXAMPLE:
# template_name = "SLES15-SP1-cloud-init"
template_name = "sles15-sp1-caasp" // <5>

# prefix that all of the booted machines will use
# IMPORTANT, please enter unique identifier below as value of
# stack_name variable to not interfere with other deployments
stack_name = "caasp-v4" // <6>

# Number of master nodes
masters = 1 // <7>

# Number of worker nodes
workers = 2 // <8>

# Username for the cluster nodes. Must exist on base OS.
# EXAMPLE:
# username = "sles"
username = "sles" // <9>

# define the repositories to use
# EXAMPLE:
# repositories = [
#   { repository1 = "http://repo.example.com/repository1/" },
#   { repository2 = "http://repo.example.com/repository2/" }
# ]
repositories = [] // <10>

# Minimum required packages. Do not remove them.
# Feel free to add more packages
packages = [ // <11>
  "patterns-caasp-Node"
]

# ssh keys to inject into all the nodes
# EXAMPLE:
# authorized_keys = [
#   "ssh-rsa <key-content>"
# ]
authorized_keys = [ // <12>
  "ssh-rsa <example_key> example@example.com"
]

# IMPORTANT: Replace these ntp servers with ones from your infrastructure
ntp_servers = ["0.novell.pool.ntp.org", "1.novell.pool.ntp.org", "2.novell.pool.ntp.org", "3.novell.pool.ntp.org"] // <13>
----
<1> `vsphere_datastore`: The datastore to use.
<2> `vsphere_datacenter`: The datacenter to use.
<3> `vsphere_network`: The network to use.
<4> `vsphere_resource_pool`: The resource pool to use.
<5> `template_name`: The name of the template created according to instructions.
<6> `stack_name`: Prefix for all machines of the cluster spawned by terraform.
*Note*: This string will be used to generate the human readable IDs in {soc}.
If you use a generic term it is very likely to fail deployment because the term is already in use by someone else. It's a good idea to use your username or other unique identifier.
<7> `masters`: Number of master nodes to be deployed.
<8> `workers`: Number of worker nodes to be deployed.
<9> `username`: Login username for the nodes.
*Note*: Leave this the default `sles`. The username must exist on the used base operating system. It will not be created.
<10> `repositories`: A list of additional repositories to be added on each
machines - leave empty if no additional packages need to be installed.
<11> `packages`: Additional packages to be installed on the node.
*Note*: Do not remove any of the pre-filled values in the `packages` section. This can render
your cluster unusable. You can add more packages but do not remove any of the
default packages listed.
<12> `authorized_keys`: List of ssh-public-keys that will be able to login to the
deployed machines.
<13> `ntp_servers`: A list of `ntp` servers you would like to use with `chrony`.
# end::tf_vmware[]
