:sectnums!:

[preface]
[[_pre.quick]]
= What is {productname}{productnumber} ?
= What is SUSE CaaS Platform 3?
:imagesdir: ./images

{suse}{productname}
is a Cloud-Native Computing Foundation (CNCF) certified {kube}
distribution on top of {suse}{mos}
. {suse}{mos}
is a minimalist operating system based on {sle}
12 SP3, dedicated to hosting containers. {suse}{mos}
OS inherits the benefits of {sle}
in the form of a smaller, simpler, and more robust operating system, optimized for large, clustered deployments.
It also features an atomic, transactional update mechanism, making the system more resilient against software-update-related problems. 

{productname}
automates the orchestration and management of containerized applications and services with powerful {kube}
capabilities, including: 

* Workload scheduling places containers according to their needs while improving resource utilization.
* Service discovery and load balancing provides an IP address for your services, and distributes load behind the scenes. 
* Application scaling up and down accommodates changing loads. 
* Non-disruptive rollout/rollback of new applications and updates enables frequent changes without downtime. 
* Health monitoring and management supports application self-healing and ensures application availability. 


In addition, {productname}
simplifies the platform operator`'s experience, with everything you need to get up and running quickly, and to manage the environment effectively in production.
It provides: 

* A complete container execution environment, including a purpose-built container host operating system ({suse}{mos} ), container runtime, and container image registries. 
* Enhanced datacenter integration features that enable you to plug {kube} into new or existing infrastructure, systems, and processes. 
* Application ecosystem support with {sle} container base images, and access to tools and services offered by {suse} Ready for CaaS Platform partners and the {kube} community. 
* End-to-End security, implemented holistically across the full stack. 
* Advanced platform management that simplifies platform installation, configuration, re-configuration, monitoring, maintenance, updates, and recovery. 
* Enterprise hardening including comprehensive interoperability testing, support for thousands of platforms, and world-class platform maintenance and technical support. 


You can deploy {productname}
onto physical servers or use it on virtual machines.
After deployment, it is immediately ready to run and provides a highly-scalable cluster. 

While {productname}
inherits benefits of {sle}
and uses tools and technologies well-known to system administrators such as `cloud-init` and Salt, the main innovation (compared to {sls}
) comes with **transactional updates**.
A transactional update is an update that can be installed when the system is running without any down-time.
A transactional update can be rolled back, so if the update fails or is not compatible with your infrastructure, you can restore the previous system state. 

{productname}
uses the {btrfs}
file system with the following characteristics: 

* The root file system and its snapshots are read-only. 
* Sub-volumes for data sharing are read-write. 
* {productname} introduces overlays of the `/etc` directories used by `cloud-init` and {salt} . 


For more information, including a list of the various components which make up {productname}
please refer to the Release Notes on https://www.suse.com/releasenotes/. 

:sectnums: