[[_cha.user.labels]]
= Using Labels
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
= Using Labels
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:imagesdir: ./images



[[_sec.user.labels.overview]]
== Overview


Labels are pairs of a key and a value attached to an object.
You can use them to specifically select the objects you want, for example pods or cluster nodes.
Keys must be unique for a given objects. 

For details, refer to https://v1-13.docs.kubernetes.io/docs/concepts/overview/working-with-objects/labels/. 

[[_sec.user.labels.attach_cli]]
== Attaching Labels to Objects


Labels can be specified in the `metadata.labels` block. 

To label an object with the [command]``kubectl`` command, use 

----
{prompt.user}``kubectl label OBJECT KEY=VALUE`` 
----

.Labeling and Selecting Nodes
====
You can label nodes with specific hardware characteristics, for example available GPUs.
You can then use the labels to run pods on these labeled nodes.
In this example, some nodes have NVidia Tesla P100 accelerators and some pods need to run specifically on these nodes. 

To attach a label `accelerator=tesla-p100` to a node, run: 

----
{prompt.user}``kubectl label nodes NODE accelerator=tesla-p100`` 
----

Then use the `nodeSelector` in the pod defintion to select the labeled nodes: 

----
apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  containers:
    - name: cuda-test
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
  nodeSelector:
    accelerator: tesla-p100
----
====

[[_sec.user.labels.attach_metadata]]
== Adding Labels in Object Description


You can use the `metadata.labels` block in an object description: 

----
apiVersion: v1
kind:`TYPE`metadata:
  labels:`KEY`:`VALUE`# More key-value pairs can follow
----

== Removing Label


To remove the label [replaceable]``KEY`` from an object, use: 

----
{prompt.user}``kubectl label TYPE NAME KEY-`` 
----